/**
 * cl-sii-activity-catalog.ts — descripción oficial de cada código de actividad
 * económica del SII de Chile (CIIU4.CL 2012, 6 dígitos).
 *
 * SOURCES-CL-SII-FREE-DISCOVERY-1. Puro: datos, sin I/O.
 *
 * ── De dónde sale ───────────────────────────────────────────────────────────
 *
 * El SII publica el código (PUB_NOM_ACTECOS) y, aparte, el texto de la actividad
 * (PUB_EMPRESAS_PJ). En `cl_sii_registry` (Prod, 05-10-2026, sólo lectura) cada
 * código tiene un texto claramente mayoritario (≥ 67 %; casi todos ≥ 90 %): ese
 * texto es la descripción oficial del código y es lo que guarda esta tabla
 * (659 códigos).
 *
 * ── Para qué sirve ──────────────────────────────────────────────────────────
 *
 * En una minoría de empresas el código y el texto NO coinciden (45 de las 5.695
 * con 200+ trabajadores: p. ej. código de farmacia con texto de seguridad
 * pública). La capa gratuita sólo ofrece una empresa si los dos dicen lo mismo,
 * para no ponerla en una industria equivocada.
 */

const RAW = `
011101|CULTIVO DE TRIGO
011102|CULTIVO DE MAIZ
011103|CULTIVO DE AVENA
011104|CULTIVO DE CEBADA
011105|CULTIVO DE OTROS CEREALES (EXCEPTO TRIGO, MAIZ, AVENA Y CEBADA)
011106|CULTIVO DE POROTOS
011107|CULTIVO DE LUPINO
011108|CULTIVO DE OTRAS LEGUMBRES (EXCEPTO POROTOS Y LUPINO)
011109|CULTIVO DE SEMILLAS DE RAPS
011110|CULTIVO DE SEMILLAS DE MARAVILLA (GIRASOL)
011111|CULTIVO DE SEMILLAS DE CEREALES, LEGUMBRES Y OLEAGINOSAS (EXCEPTO SEMILLAS DE RAPS Y MARAVILLA)
011200|CULTIVO DE ARROZ
011301|CULTIVO DE PAPAS
011302|CULTIVO DE CAMOTES
011303|CULTIVO DE OTROS TUBERCULOS (EXCEPTO PAPAS Y CAMOTES)
011304|CULTIVO DE REMOLACHA AZUCARERA
011305|CULTIVO DE SEMILLAS DE HORTALIZAS
011306|CULTIVO DE HORTALIZAS Y MELONES
011500|CULTIVO DE TABACO
011600|CULTIVO DE PLANTAS DE FIBRA
011901|CULTIVO DE FLORES
011902|CULTIVOS FORRAJEROS EN PRADERAS MEJORADAS O SEMBRADAS, CULTIVOS SUPLEMENTARIOS FORRAJEROS
011903|CULTIVOS DE SEMILLAS DE FLORES, CULTIVO DE SEMILLAS DE PLANTAS FORRAJERAS
012111|CULTIVO DE UVA DESTINADA A LA PRODUCCION DE PISCO Y AGUARDIENTE
012112|CULTIVO DE UVA DESTINADA A LA PRODUCCION DE VINO
012120|CULTIVO DE UVA PARA MESA
012200|CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES (INCLUYE EL CULTIVO DE PALTAS)
012300|CULTIVO DE CITRICOS
012400|CULTIVO DE FRUTAS DE PEPITA Y DE HUESO
012501|CULTIVO DE SEMILLAS DE FRUTAS
012502|CULTIVO DE OTROS FRUTOS Y NUECES DE ARBOLES Y ARBUSTOS
012600|CULTIVO DE FRUTOS OLEAGINOSOS (INCLUYE EL CULTIVO DE ACEITUNAS)
012700|CULTIVO DE PLANTAS CON LAS QUE SE PREPARAN BEBIDAS (INCLUYE EL CULTIVO DE CAFE, TE Y MATE)
012801|CULTIVO DE ESPECIAS
012802|CULTIVO DE PLANTAS AROMATICAS, MEDICINALES Y FARMACEUTICAS
012900|CULTIVO DE OTRAS PLANTAS PERENNES
013000|CULTIVO DE PLANTAS VIVAS INCLUIDA LA PRODUCCION EN VIVEROS (EXCEPTO VIVEROS FORESTALES)
014101|CRIA DE GANADO BOVINO PARA LA PRODUCCION LECHERA
014102|CRIA DE GANADO BOVINO PARA LA PRODUCCION DE CARNE O COMO GANADO REPRODUCTOR
014200|CRIA DE CABALLOS Y OTROS EQUINOS
014300|CRIA DE LLAMAS, ALPACAS, VICUÑAS, GUANACOS Y OTROS CAMELIDOS
014410|CRIA DE OVEJAS (OVINOS)
014420|CRIA DE CABRAS (CAPRINOS)
014500|CRIA DE CERDOS
014601|CRIA DE AVES DE CORRAL PARA LA PRODUCCION DE CARNE
014602|CRIA DE AVES DE CORRAL PARA LA PRODUCCION DE HUEVOS
014901|APICULTURA
014909|CRIA DE OTROS ANIMALES N.C.P.
015000|CULTIVO DE PRODUCTOS AGRICOLAS EN COMBINACION CON LA CRIA DE ANIMALES (EXPLOTACION MIXTA)
016100|ACTIVIDADES DE APOYO A LA AGRICULTURA
016200|ACTIVIDADES DE APOYO A LA GANADERIA
016300|ACTIVIDADES POSCOSECHA
016400|TRATAMIENTO DE SEMILLAS PARA PROPAGACION
017000|CAZA ORDINARIA Y MEDIANTE TRAMPAS Y ACTIVIDADES DE SERVICIOS CONEXAS
021001|EXPLOTACION DE VIVEROS FORESTALES
021002|SILVICULTURA Y OTRAS ACTIVIDADES FORESTALES (EXCEPTO EXPLOTACION DE VIVEROS FORESTALES)
022000|EXTRACCION DE MADERA
023000|RECOLECCION DE PRODUCTOS FORESTALES DISTINTOS DE LA MADERA
024001|SERVICIOS DE FORESTACION A CAMBIO DE UNA RETRIBUCION O POR CONTRATA
024002|SERVICIOS DE CORTA DE MADERA A CAMBIO DE UNA RETRIBUCION O POR CONTRATA
024003|SERVICIOS DE EXTINCION Y PREVENCION DE INCENDIOS FORESTALES
024009|OTROS SERVICIOS DE APOYO A LA SILVICULTURA N.C.P.
031110|PESCA MARITIMA INDUSTRIAL, EXCEPTO DE BARCOS FACTORIA
031120|PESCA MARITIMA ARTESANAL
031130|RECOLECCION Y EXTRACCION DE PRODUCTOS MARINOS
031140|SERVICIOS RELACIONADOS CON LA PESCA MARITIMA
031200|PESCA DE AGUA DULCE
032110|CULTIVO Y CRIANZA DE PECES MARINOS
032120|CULTIVO, REPRODUCCION Y MANEJO DE ALGAS MARINAS
032130|REPRODUCCION Y CRIA DE MOLUSCOS, CRUSTACEOS Y GUSANOS MARINOS
032140|SERVICIOS RELACIONADOS CON LA ACUICULTURA MARINA
032200|ACUICULTURA DE AGUA DULCE
040000|EXTRACCION Y PROCESAMIENTO DE COBRE
051000|EXTRACCION DE CARBON DE PIEDRA
061000|EXTRACCION DE PETROLEO CRUDO
071000|EXTRACCION DE MINERALES DE HIERRO
072100|EXTRACCION DE MINERALES DE URANIO Y TORIO
072910|EXTRACCION DE ORO Y PLATA
072991|EXTRACCION DE ZINC Y PLOMO
072992|EXTRACCION DE MANGANESO
072999|EXTRACCION DE OTROS MINERALES METALIFEROS NO FERROSOS N.C.P. (EXCEPTO ZINC, PLOMO Y MANGANESO)
081000|EXTRACCION DE PIEDRA, ARENA Y ARCILLA
089110|EXTRACCION Y PROCESAMIENTO DE LITIO
089190|EXTRACCION DE MINERALES PARA LA FABRICACION DE ABONOS Y PRODUCTOS QUIMICOS N.C.P.
089200|EXTRACCION DE TURBA
089300|EXTRACCION DE SAL
089900|EXPLOTACION DE OTRAS MINAS Y CANTERAS N.C.P.
091001|ACTIVIDADES DE APOYO PARA LA EXTRACCION DE PETROLEO Y GAS NATURAL PRESTADOS POR EMPRESAS
099001|ACTIVIDADES DE APOYO PARA LA EXPLOTACION DE OTRAS MINAS Y CANTERAS PRESTADOS POR EMPRESAS
099002|ACTIVIDADES DE APOYO PARA LA EXPLOTACION DE OTRAS MINAS Y CANTERAS PRESTADOS POR PROFESIONALES
101011|EXPLOTACION DE MATADEROS DE BOVINOS, OVINOS, EQUINOS, CAPRINOS, PORCINOS Y CAMELIDOS
101019|EXPLOTACION DE MATADEROS DE AVES Y DE OTROS TIPOS DE ANIMALES N.C.P.
101020|ELABORACION Y CONSERVACION DE CARNE Y PRODUCTOS CARNICOS
102010|PRODUCCION DE HARINA DE PESCADO
102020|ELABORACION Y CONSERVACION DE SALMONIDOS
102030|ELABORACION Y CONSERVACION DE OTROS PESCADOS, EN PLANTAS EN TIERRA (EXCEPTO BARCOS FACTORIA)
102040|ELABORACION Y CONSERVACION DE CRUSTACEOS, MOLUSCOS Y OTROS PRODUCTOS ACUATICOS, EN PLANTAS EN TIERRA
102050|ACTIVIDADES DE ELABORACION Y CONSERVACION DE PESCADO, REALIZADAS EN BARCOS FACTORIA
102060|ELABORACION Y PROCESAMIENTO DE ALGAS
103000|ELABORACION Y CONSERVACION DE FRUTAS, LEGUMBRES Y HORTALIZAS
104000|ELABORACION DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL (EXCEPTO ELABORACION DE MANTEQUILLA)
105000|ELABORACION DE PRODUCTOS LACTEOS
106101|MOLIENDA DE TRIGO: PRODUCCION DE HARINA, SEMOLA Y GRANULOS
106102|MOLIENDA DE ARROZ, PRODUCCION DE HARINA DE ARROZ
106109|ELABORACION DE OTROS PRODUCTOS DE MOLINERIA N.C.P.
106200|ELABORACION DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDON
107100|ELABORACION DE PRODUCTOS DE PANADERIA Y PASTELERIA
107200|ELABORACION DE AZUCAR
107300|ELABORACION DE CACAO, CHOCOLATE Y DE PRODUCTOS DE CONFITERIA
107400|ELABORACION DE MACARRONES, FIDEOS, ALCUZCUZ Y PRODUCTOS FARINACEOS SIMILARES
107500|ELABORACION DE COMIDAS Y PLATOS PREPARADOS ENVASADOS, ROTULADOS Y CON INFORMACION NUTRICIONAL
107901|ELABORACION DE TE, CAFE, MATE E INFUSIONES DE HIERBAS
107902|ELABORACION DE LEVADURAS NATURALES O ARTIFICIALES
107903|ELABORACION DE VINAGRES, MOSTAZAS, MAYONESAS Y CONDIMENTOS EN GENERAL
107909|ELABORACION DE OTROS PRODUCTOS ALIMENTICIOS N.C.P.
108000|ELABORACION DE PIENSOS PREPARADOS PARA ANIMALES
110110|ELABORACION DE PISCO (INDUSTRIAS PISQUERAS)
110120|DESTILACION, RECTIFICACION Y MEZCLAS DE BEBIDAS ALCOHOLICAS, EXCEPTO PISCO
110200|ELABORACION DE VINOS
110300|ELABORACION DE BEBIDAS MALTEADAS Y DE MALTA
110401|ELABORACION DE BEBIDAS NO ALCOHOLICAS
110402|PRODUCCION DE AGUAS MINERALES Y OTRAS AGUAS EMBOTELLADAS
120001|ELABORACION DE CIGARROS Y CIGARRILLOS
131100|PREPARACION E HILATURA DE FIBRAS TEXTILES
131200|TEJEDURA DE PRODUCTOS TEXTILES
131300|ACABADO DE PRODUCTOS TEXTILES
139100|FABRICACION DE TEJIDOS DE PUNTO Y GANCHILLO
139200|FABRICACION DE ARTICULOS CONFECCIONADOS DE MATERIALES TEXTILES, EXCEPTO PRENDAS DE VESTIR
139300|FABRICACION DE TAPICES Y ALFOMBRAS
139400|FABRICACION DE CUERDAS, CORDELES, BRAMANTES Y REDES
139900|FABRICACION DE OTROS PRODUCTOS TEXTILES N.C.P.
141001|FABRICACION DE PRENDAS DE VESTIR DE MATERIALES TEXTILES Y SIMILARES
141002|FABRICACION DE PRENDAS DE VESTIR DE CUERO NATURAL O ARTIFICIAL
141003|FABRICACION DE ACCESORIOS DE VESTIR
141004|FABRICACION DE ROPA DE TRABAJO
142000|FABRICACION DE ARTICULOS DE PIEL
143000|FABRICACION DE ARTICULOS DE PUNTO Y GANCHILLO
151100|CURTIDO Y ADOBO DE CUEROS, ADOBO Y TEÑIDO DE PIELES
151200|FABRICACION DE MALETAS, BOLSOS Y ARTICULOS SIMILARES, ARTICULOS DE TALABARTERIA Y GUARNICIONERIA
152000|FABRICACION DE CALZADO
161000|ASERRADO Y ACEPILLADURA DE MADERA
162100|FABRICACION DE HOJAS DE MADERA PARA ENCHAPADO Y TABLEROS A BASE DE MADERA
162200|FABRICACION DE PARTES Y PIEZAS DE CARPINTERIA PARA EDIFICIOS Y CONSTRUCCIONES
162300|FABRICACION DE RECIPIENTES DE MADERA
162900|FABRICACION DE OTROS PRODUCTOS DE MADERA, DE ARTICULOS DE CORCHO, PAJA Y MATERIALES TRENZABLES
170110|FABRICACION DE CELULOSA Y OTRAS PASTAS DE MADERA
170190|FABRICACION DE PAPEL Y CARTON PARA SU POSTERIOR USO INDUSTRIAL N.C.P.
170200|FABRICACION DE PAPEL Y CARTON ONDULADO Y DE ENVASES DE PAPEL Y CARTON
170900|FABRICACION DE OTROS ARTICULOS DE PAPEL Y CARTON
181101|IMPRESION DE LIBROS
181109|OTRAS ACTIVIDADES DE IMPRESION N.C.P.
181200|ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA IMPRESION
182000|REPRODUCCION DE GRABACIONES
191000|FABRICACION DE PRODUCTOS DE HORNOS DE COQUE
192000|FABRICACION DE PRODUCTOS DE LA REFINACION DEL PETROLEO
201101|FABRICACION DE CARBON VEGETAL (EXCEPTO ACTIVADO), FABRICACION DE BRIQUETAS DE CARBON VEGETAL
201109|FABRICACION DE OTRAS SUSTANCIAS QUIMICAS BASICAS N.C.P.
201200|FABRICACION DE ABONOS Y COMPUESTOS DE NITROGENO
201300|FABRICACION DE PLASTICOS Y CAUCHO SINTETICO EN FORMAS PRIMARIAS
202100|FABRICACION DE PLAGUICIDAS Y OTROS PRODUCTOS QUIMICOS DE USO AGROPECUARIO
202200|FABRICACION DE PINTURAS, BARNICES Y PRODUCTOS DE REVESTIMIENTO, TINTAS DE IMPRENTA Y MASILLAS
202300|FABRICACION DE JABONES Y DETERGENTES, PREPARADOS PARA LIMPIAR, PERFUMES Y PREPARADOS DE TOCADOR
202901|FABRICACION DE EXPLOSIVOS Y PRODUCTOS PIROTECNICOS
202909|FABRICACION DE OTROS PRODUCTOS QUIMICOS N.C.P.
203000|FABRICACION DE FIBRAS ARTIFICIALES
210000|FABRICACION DE PRODUCTOS FARMACEUTICOS, SUSTANCIAS QUIMICAS MEDICINALES Y PRODUCTOS BOTANICOS
221100|FABRICACION DE CUBIERTAS Y CAMARAS DE CAUCHO, RECAUCHUTADO Y RENOVACION DE CUBIERTAS DE CAUCHO
221900|FABRICACION DE OTROS PRODUCTOS DE CAUCHO
222000|FABRICACION DE PRODUCTOS DE PLASTICO
231001|FABRICACION DE VIDRIO PLANO
231002|FABRICACION DE VIDRIO HUECO
231003|FABRICACION DE FIBRAS DE VIDRIO
231009|FABRICACION DE PRODUCTOS DE VIDRIO N.C.P.
239100|FABRICACION DE PRODUCTOS REFRACTARIOS
239200|FABRICACION DE MATERIALES DE CONSTRUCCION DE ARCILLA
239300|FABRICACION DE OTROS PRODUCTOS DE PORCELANA Y DE CERAMICA
239400|FABRICACION DE CEMENTO, CAL Y YESO
239500|FABRICACION DE ARTICULOS DE HORMIGON, CEMENTO Y YESO
239600|CORTE, TALLA Y ACABADO DE LA PIEDRA
239900|FABRICACION DE OTROS PRODUCTOS MINERALES NO METALICOS N.C.P.
241000|INDUSTRIAS BASICAS DE HIERRO Y ACERO
242001|FABRICACION DE PRODUCTOS PRIMARIOS DE COBRE
242002|FABRICACION DE PRODUCTOS PRIMARIOS DE ALUMINIO
242009|FABRICACION DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y DE OTROS METALES NO FERROSOS N.C.P.
243100|FUNDICION DE HIERRO Y ACERO
243200|FUNDICION DE METALES NO FERROSOS
251100|FABRICACION DE PRODUCTOS METALICOS PARA USO ESTRUCTURAL
251201|FABRICACION DE RECIPIENTES DE METAL PARA GASES COMPRIMIDOS O LICUADOS
251209|FABRICACION DE TANQUES, DEPOSITOS Y RECIPIENTES DE METAL N.C.P.
251300|FABRICACION DE GENERADORES DE VAPOR, EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCION CENTRAL
252000|FABRICACION DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.
259100|FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METALES, PULVIMETALURGIA
259200|TRATAMIENTO Y REVESTIMIENTO DE METALES, MAQUINADO
259300|FABRICACION DE ARTICULOS DE CUCHILLERIA, HERRAMIENTAS DE MANO Y ARTICULOS DE FERRETERIA
259900|FABRICACION DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.
261000|FABRICACION DE COMPONENTES Y TABLEROS ELECTRONICOS
262000|FABRICACION DE COMPUTADORES Y EQUIPO PERIFERICO
263000|FABRICACION DE EQUIPO DE COMUNICACIONES
264000|FABRICACION DE APARATOS ELECTRONICOS DE CONSUMO
265100|FABRICACION DE EQUIPO DE MEDICION, PRUEBA, NAVEGACION Y CONTROL
265200|FABRICACION DE RELOJES
266000|FABRICACION DE EQUIPO DE IRRADIACION Y EQUIPO ELECTRONICO DE USO MEDICO Y TERAPEUTICO
267000|FABRICACION DE INSTRUMENTOS OPTICOS Y EQUIPO FOTOGRAFICO
268000|FABRICACION DE SOPORTES MAGNETICOS Y OPTICOS
271000|FABRICACION DE MOTORES, GENERADORES Y TRANSFORMADORES ELECTRICOS, APARATOS DE DISTRIBUCION Y CONTROL
272000|FABRICACION DE PILAS, BATERIAS Y ACUMULADORES
273100|FABRICACION DE CABLES DE FIBRA OPTICA
273200|FABRICACION DE OTROS HILOS Y CABLES ELECTRICOS
273300|FABRICACION DE DISPOSITIVOS DE CABLEADO
274000|FABRICACION DE EQUIPO ELECTRICO DE ILUMINACION
275000|FABRICACION DE APARATOS DE USO DOMESTICO
279000|FABRICACION DE OTROS TIPOS DE EQUIPO ELECTRICO
281100|FABRICACION DE MOTORES Y TURBINAS, EXCEPTO PARA AERONAVES, VEHICULOS AUTOMOTORES Y MOTOCICLETAS
281200|FABRICACION DE EQUIPO DE PROPULSION DE FLUIDOS
281300|FABRICACION DE OTRAS BOMBAS, COMPRESORES, GRIFOS Y VALVULAS
281400|FABRICACION DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISION
281500|FABRICACION DE HORNOS, CALDERAS Y QUEMADORES
281600|FABRICACION DE EQUIPO DE ELEVACION Y MANIPULACION
281700|FABRICACION DE MAQUINARIA Y EQUIPO DE OFICINA (EXCEPTO COMPUTADORES Y EQUIPO PERIFERICO)
281900|FABRICACION DE OTROS TIPOS DE MAQUINARIA DE USO GENERAL
282100|FABRICACION DE MAQUINARIA AGROPECUARIA Y FORESTAL
282200|FABRICACION DE MAQUINARIA PARA LA CONFORMACION DE METALES Y DE MAQUINAS HERRAMIENTA
282300|FABRICACION DE MAQUINARIA METALURGICA
282400|FABRICACION DE MAQUINARIA PARA LA EXPLOTACION DE MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCION
282500|FABRICACION DE MAQUINARIA PARA LA ELABORACION DE ALIMENTOS, BEBIDAS Y TABACO
282600|FABRICACION DE MAQUINARIA PARA LA ELABORACION DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CUEROS
282900|FABRICACION DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL
291000|FABRICACION DE VEHICULOS AUTOMOTORES
292000|FABRICACION DE CARROCERIAS PARA VEHICULOS AUTOMOTORES, FABRICACION DE REMOLQUES Y SEMIRREMOLQUES
293000|FABRICACION DE PARTES, PIEZAS Y ACCESORIOS PARA VEHICULOS AUTOMOTORES
301100|CONSTRUCCION DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES
301200|CONSTRUCCION DE EMBARCACIONES DE RECREO Y DE DEPORTE
302000|FABRICACION DE LOCOMOTORAS Y MATERIAL RODANTE
303000|FABRICACION DE AERONAVES, NAVES ESPACIALES Y MAQUINARIA CONEXA
309100|FABRICACION DE MOTOCICLETAS
309200|FABRICACION DE BICICLETAS Y DE SILLAS DE RUEDAS
309900|FABRICACION DE OTROS TIPOS DE EQUIPO DE TRANSPORTE N.C.P.
310001|FABRICACION DE MUEBLES PRINCIPALMENTE DE MADERA
310009|FABRICACION DE COLCHONES, FABRICACION DE OTROS MUEBLES N.C.P.
321100|FABRICACION DE JOYAS Y ARTICULOS CONEXOS
321200|FABRICACION DE BISUTERIA Y ARTICULOS CONEXOS
322000|FABRICACION DE INSTRUMENTOS MUSICALES
323000|FABRICACION DE ARTICULOS DE DEPORTE
324000|FABRICACION DE JUEGOS Y JUGUETES
325001|ACTIVIDADES DE LABORATORIOS DENTALES
325009|FABRICACION DE INSTRUMENTOS Y MATERIALES MEDICOS, OFTALMOLOGICOS Y ODONTOLOGICOS N.C.P.
329000|OTRAS INDUSTRIAS MANUFACTURERAS N.C.P.
331100|REPARACION DE PRODUCTOS ELABORADOS DE METAL
331201|REPARACION DE MAQUINARIA AGROPECUARIA Y FORESTAL
331202|REPARACION DE MAQUINARIA METALURGICA, PARA LA MINERIA, EXTRACCION DE PETROLEO Y PARA LA CONSTRUCCION
331203|REPARACION DE MAQUINARIA PARA LA ELABORACION DE ALIMENTOS, BEBIDAS Y TABACO
331204|REPARACION DE MAQUINARIA PARA PRODUCIR TEXTILES, PRENDAS DE VESTIR, ARTICULOS DE CUERO Y CALZADO
331209|REPARACION DE OTRO TIPO DE MAQUINARIA Y EQUIPOS INDUSTRIALES N.C.P.
331301|REPARACION DE EQUIPO DE MEDICION, PRUEBA, NAVEGACION Y CONTROL
331309|REPARACION DE OTROS EQUIPOS ELECTRONICOS Y OPTICOS N.C.P.
331400|REPARACION DE EQUIPO ELECTRICO (EXCEPTO REPARACION DE EQUIPO Y ENSERES DOMESTICOS)
331501|REPARACION DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES
331502|REPARACION DE AERONAVES Y NAVES ESPACIALES
331509|REPARACION DE OTROS EQUIPOS DE TRANSPORTE N.C.P., EXCEPTO VEHICULOS AUTOMOTORES
331900|REPARACION DE OTROS TIPOS DE EQUIPO
332000|INSTALACION DE MAQUINARIA Y EQUIPOS INDUSTRIALES
351011|GENERACION DE ENERGIA ELECTRICA EN CENTRALES HIDROELECTRICAS
351012|GENERACION DE ENERGIA ELECTRICA EN CENTRALES TERMOELECTRICAS
351019|GENERACION DE ENERGIA ELECTRICA EN OTRAS CENTRALES N.C.P.
351020|TRANSMISION DE ENERGIA ELECTRICA
351030|DISTRIBUCION DE ENERGIA ELECTRICA
352010|REGASIFICACION DE GAS NATURAL LICUADO (GNL)
352020|FABRICACION DE GAS, DISTRIBUCION DE COMBUSTIBLES GASEOSOS POR TUBERIA, EXCEPTO REGASIFICACION DE GNL
353001|SUMINISTRO DE VAPOR Y DE AIRE ACONDICIONADO
353002|ELABORACION DE HIELO (EXCEPTO FABRICACION DE HIELO SECO)
360000|CAPTACION, TRATAMIENTO Y DISTRIBUCION DE AGUA
370000|EVACUACION Y TRATAMIENTO DE AGUAS SERVIDAS
381100|RECOGIDA DE DESECHOS NO PELIGROSOS
381200|RECOGIDA DE DESECHOS PELIGROSOS
382100|TRATAMIENTO Y ELIMINACION DE DESECHOS NO PELIGROSOS
382200|TRATAMIENTO Y ELIMINACION DE DESECHOS PELIGROSOS
383001|RECUPERACION Y RECICLAMIENTO DE DESPERDICIOS Y DESECHOS METALICOS
383002|RECUPERACION Y RECICLAMIENTO DE PAPEL
383003|RECUPERACION Y RECICLAMIENTO DE VIDRIO
383009|RECUPERACION Y RECICLAMIENTO DE OTROS DESPERDICIOS Y DESECHOS N.C.P.
390000|ACTIVIDADES DE DESCONTAMINACION Y OTROS SERVICIOS DE GESTION DE DESECHOS
410010|CONSTRUCCION DE EDIFICIOS PARA USO RESIDENCIAL
410020|CONSTRUCCION DE EDIFICIOS PARA USO NO RESIDENCIAL
421000|CONSTRUCCION DE CARRETERAS Y LINEAS DE FERROCARRIL
422000|CONSTRUCCION DE PROYECTOS DE SERVICIO PUBLICO
429000|CONSTRUCCION DE OTRAS OBRAS DE INGENIERIA CIVIL
431100|DEMOLICION
431200|PREPARACION DEL TERRENO
432100|INSTALACIONES ELECTRICAS
432200|INSTALACIONES DE GASFITERIA, CALEFACCION Y AIRE ACONDICIONADO
432900|OTRAS INSTALACIONES PARA OBRAS DE CONSTRUCCION
433000|TERMINACION Y ACABADO DE EDIFICIOS
439000|OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCION
451001|VENTA AL POR MAYOR DE VEHICULOS AUTOMOTORES
451002|VENTA AL POR MENOR DE VEHICULOS AUTOMOTORES NUEVOS O USADOS (INCLUYE COMPRAVENTA)
452001|SERVICIO DE LAVADO DE VEHICULOS AUTOMOTORES
452002|MANTENIMIENTO Y REPARACION DE VEHICULOS AUTOMOTORES
453000|VENTA DE PARTES, PIEZAS Y ACCESORIOS PARA VEHICULOS AUTOMOTORES
454001|VENTA DE MOTOCICLETAS
454002|VENTA DE PARTES, PIEZAS Y ACCESORIOS DE MOTOCICLETAS
454003|MANTENIMIENTO Y REPARACION DE MOTOCICLETAS
461001|CORRETAJE AL POR MAYOR DE PRODUCTOS AGRICOLAS
461002|CORRETAJE AL POR MAYOR DE GANADO
461009|OTROS TIPOS DE CORRETAJES O REMATES AL POR MAYOR N.C.P.
462010|VENTA AL POR MAYOR DE MATERIAS PRIMAS AGRICOLAS
462020|VENTA AL POR MAYOR DE ANIMALES VIVOS
462090|VENTA AL POR MAYOR DE OTRAS MATERIAS PRIMAS AGROPECUARIAS N.C.P.
463011|VENTA AL POR MAYOR DE FRUTAS Y VERDURAS
463012|VENTA AL POR MAYOR DE CARNE Y PRODUCTOS CARNICOS
463013|VENTA AL POR MAYOR DE PRODUCTOS DEL MAR (PESCADOS, MARISCOS Y ALGAS)
463014|VENTA AL POR MAYOR DE PRODUCTOS DE CONFITERIA
463019|VENTA AL POR MAYOR DE HUEVOS, LACTEOS, ABARROTES Y DE OTROS ALIMENTOS N.C.P.
463020|VENTA AL POR MAYOR DE BEBIDAS ALCOHOLICAS Y NO ALCOHOLICAS
463030|VENTA AL POR MAYOR DE TABACO
464100|VENTA AL POR MAYOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO
464901|VENTA AL POR MAYOR DE MUEBLES, EXCEPTO MUEBLES DE OFICINA
464902|VENTA AL POR MAYOR DE ARTICULOS ELECTRICOS Y ELECTRONICOS PARA EL HOGAR
464903|VENTA AL POR MAYOR DE ARTICULOS DE PERFUMERIA, DE TOCADOR Y COSMETICOS
464904|VENTA AL POR MAYOR DE ARTICULOS DE PAPELERIA Y ESCRITORIO
464905|VENTA AL POR MAYOR DE LIBROS
464906|VENTA AL POR MAYOR DE DIARIOS Y REVISTAS
464907|VENTA AL POR MAYOR DE PRODUCTOS FARMACEUTICOS Y MEDICINALES
464908|VENTA AL POR MAYOR DE INSTRUMENTOS CIENTIFICOS Y QUIRURGICOS
464909|VENTA AL POR MAYOR DE OTROS ENSERES DOMESTICOS N.C.P.
465100|VENTA AL POR MAYOR DE COMPUTADORES, EQUIPO PERIFERICO Y PROGRAMAS INFORMATICOS
465200|VENTA AL POR MAYOR DE EQUIPO, PARTES Y PIEZAS ELECTRONICOS Y DE TELECOMUNICACIONES
465300|VENTA AL POR MAYOR DE MAQUINARIA, EQUIPO Y MATERIALES AGROPECUARIOS
465901|VENTA AL POR MAYOR DE MAQUINARIA METALURGICA, PARA LA MINERIA, EXTRACCION DE PETROLEO Y CONSTRUCCION
465902|VENTA AL POR MAYOR DE MAQUINARIA PARA LA ELABORACION DE ALIMENTOS, BEBIDAS Y TABACO
465903|VENTA AL POR MAYOR DE MAQUINARIA PARA LA INDUSTRIA TEXTIL, DEL CUERO Y DEL CALZADO
465904|VENTA AL POR MAYOR DE MAQUINARIA Y EQUIPO DE OFICINA, VENTA AL POR MAYOR DE MUEBLES DE OFICINA
465905|VENTA AL POR MAYOR DE EQUIPO DE TRANSPORTE(EXCEPTO VEHICULOS AUTOMOTORES, MOTOCICLETAS Y BICICLETAS)
465909|VENTA AL POR MAYOR DE OTROS TIPOS DE MAQUINARIA Y EQUIPO N.C.P.
466100|VENTA AL POR MAYOR DE COMBUSTIBLES SOLIDOS, LIQUIDOS Y GASEOSOS Y PRODUCTOS CONEXOS
466200|VENTA AL POR MAYOR DE METALES Y MINERALES METALIFEROS
466301|VENTA AL POR MAYOR DE MADERA EN BRUTO Y PRODUCTOS PRIMARIOS DE LA ELABORACION DE MADERA
466302|VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCION, ARTICULOS DE FERRETERIA, GASFITERIA Y CALEFACCION
466901|VENTA AL POR MAYOR DE PRODUCTOS QUIMICOS
466902|VENTA AL POR MAYOR DE DESECHOS METALICOS (CHATARRA)
466909|VENTA AL POR MAYOR DE DESPERDICIOS, DESECHOS Y OTROS PRODUCTOS N.C.P.
469000|VENTA AL POR MAYOR NO ESPECIALIZADA
471100|VENTA AL POR MENOR EN COMERCIOS DE ALIMENTOS, BEBIDAS O TABACO (SUPERMERCADOS E HIPERMERCADOS)
471910|VENTA AL POR MENOR EN COMERCIOS DE VESTUARIO Y PRODUCTOS PARA EL HOGAR (GRANDES TIENDAS)
471990|OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS N.C.P.
472101|VENTA AL POR MENOR DE ALIMENTOS EN COMERCIOS ESPECIALIZADOS (ALMACENES PEQUEÑOS Y MINIMARKET)
472102|VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE CARNE Y PRODUCTOS CARNICOS
472103|VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE FRUTAS Y VERDURAS (VERDULERIAS)
472104|VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PESCADO, MARISCOS Y PRODUCTOS CONEXOS
472105|VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PRODUCTOS DE PANADERIA Y PASTELERIA
472109|VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE HUEVOS, CONFITES Y PRODUCTOS ALIMENTICIOS N.C.P.
472200|VENTA AL POR MENOR DE BEBIDAS ALCOHOLICAS Y NO ALCOHOLICAS EN COMERCIOS ESPECIALIZADOS (BOTILLERIAS)
472300|VENTA AL POR MENOR DE TABACO Y PRODUCTOS DE TABACO EN COMERCIOS ESPECIALIZADOS
473000|VENTA AL POR MENOR DE COMBUSTIBLES PARA VEHICULOS AUTOMOTORES EN COMERCIOS ESPECIALIZADOS
474100|VENTA AL POR MENOR DE COMPUTADORES, EQUIPO PERIFERICO, PROGRAMAS INFORMATICOS Y EQUIPO DE TELECOM.
474200|VENTA AL POR MENOR DE EQUIPO DE SONIDO Y DE VIDEO EN COMERCIOS ESPECIALIZADOS
475100|VENTA AL POR MENOR DE TELAS, LANAS, HILOS Y SIMILARES EN COMERCIOS ESPECIALIZADOS
475201|VENTA AL POR MENOR DE ARTICULOS DE FERRETERIA Y MATERIALES DE CONSTRUCCION
475202|VENTA AL POR MENOR DE PINTURAS, BARNICES Y LACAS EN COMERCIOS ESPECIALIZADOS
475203|VENTA AL POR MENOR DE PRODUCTOS DE VIDRIO EN COMERCIOS ESPECIALIZADOS
475300|VENTA AL POR MENOR DE TAPICES, ALFOMBRAS Y CUBRIMIENTOS PARA PAREDES Y PISOS
475901|VENTA AL POR MENOR DE MUEBLES Y COLCHONES EN COMERCIOS ESPECIALIZADOS
475902|VENTA AL POR MENOR DE INSTRUMENTOS MUSICALES EN COMERCIOS ESPECIALIZADOS
475909|VENTA AL POR MENOR DE APARATOS ELECTRICOS, TEXTILES PARA EL HOGAR Y OTROS ENSERES DOMESTICOS N.C.P.
476101|VENTA AL POR MENOR DE LIBROS EN COMERCIOS ESPECIALIZADOS
476102|VENTA AL POR MENOR DE DIARIOS Y REVISTAS EN COMERCIOS ESPECIALIZADOS
476103|VENTA AL POR MENOR DE ARTICULOS DE PAPELERIA Y ESCRITORIO EN COMERCIOS ESPECIALIZADOS
476200|VENTA AL POR MENOR DE GRABACIONES DE MUSICA Y DE VIDEO EN COMERCIOS ESPECIALIZADOS
476301|VENTA AL POR MENOR DE ARTICULOS DE CAZA Y PESCA EN COMERCIOS ESPECIALIZADOS
476302|VENTA AL POR MENOR DE BICICLETAS Y SUS REPUESTOS EN COMERCIOS ESPECIALIZADOS
476309|VENTA AL POR MENOR DE OTROS ARTICULOS Y EQUIPOS DE DEPORTE N.C.P.
476400|VENTA AL POR MENOR DE JUEGOS Y JUGUETES EN COMERCIOS ESPECIALIZADOS
477101|VENTA AL POR MENOR DE CALZADO EN COMERCIOS ESPECIALIZADOS
477102|VENTA AL POR MENOR DE PRENDAS Y ACCESORIOS DE VESTIR EN COMERCIOS ESPECIALIZADOS
477103|VENTA AL POR MENOR DE CARTERAS, MALETAS Y OTROS ACCESORIOS DE VIAJE EN COMERCIOS ESPECIALIZADOS
477201|VENTA AL POR MENOR DE PRODUCTOS FARMACEUTICOS Y MEDICINALES EN COMERCIOS ESPECIALIZADOS
477202|VENTA AL POR MENOR DE ARTICULOS ORTOPEDICOS EN COMERCIOS ESPECIALIZADOS
477203|VENTA AL POR MENOR DE ARTICULOS DE PERFUMERIA, DE TOCADOR Y COSMETICOS EN COMERCIOS ESPECIALIZADOS
477310|VENTA AL POR MENOR DE GAS LICUADO EN BOMBONAS (CILINDROS) EN COMERCIOS ESPECIALIZADOS
477391|VENTA AL POR MENOR DE ALIMENTO Y ACCESORIOS PARA MASCOTAS EN COMERCIOS ESPECIALIZADOS
477392|VENTA AL POR MENOR DE ARMAS Y MUNICIONES EN COMERCIOS ESPECIALIZADOS
477393|VENTA AL POR MENOR DE ARTICULOS OPTICOS EN COMERCIOS ESPECIALIZADOS
477394|VENTA AL POR MENOR DE ARTICULOS DE JOYERIA, BISUTERIA Y RELOJERIA EN COMERCIOS ESPECIALIZADOS
477395|VENTA AL POR MENOR DE CARBON, LEÑA Y OTROS COMBUSTIBLES DE USO DOMESTICO EN COMERCIOS ESPECIALIZADOS
477396|VENTA AL POR MENOR DE RECUERDOS, ARTESANIAS Y ARTICULOS RELIGIOSOS EN COMERCIOS ESPECIALIZADOS
477397|VENTA AL POR MENOR DE FLORES, PLANTAS, ARBOLES, SEMILLAS Y ABONOS EN COMERCIOS ESPECIALIZADOS
477398|VENTA AL POR MENOR DE MASCOTAS EN COMERCIOS ESPECIALIZADOS
477399|VENTA AL POR MENOR DE OTROS PRODUCTOS EN COMERCIOS ESPECIALIZADOS N.C.P.
477401|VENTA AL POR MENOR DE ANTIGÜEDADES EN COMERCIOS
477402|VENTA AL POR MENOR DE ROPA USADA EN COMERCIOS
477409|VENTA AL POR MENOR DE OTROS ARTICULOS DE SEGUNDA MANO EN COMERCIOS N.C.P.
478100|VENTA AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)
478200|VENTA AL POR MENOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO EN PUESTOS DE VENTA Y MERCADOS
478900|VENTA AL POR MENOR DE OTROS PRODUCTOS EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)
479100|VENTA AL POR MENOR POR CORREO, POR INTERNET Y VIA TELEFONICA
479902|VENTA AL POR MENOR MEDIANTE MAQUINAS EXPENDEDORAS
479903|VENTA AL POR MENOR POR COMISIONISTAS (NO DEPENDIENTES DE COMERCIOS)
479909|OTRAS ACTIVIDADES DE VENTA POR MENOR NO REALIZADAS EN COMERCIOS, PUESTOS DE VENTA O MERCADOS N.C.P.
491100|TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRIL
491200|TRANSPORTE DE CARGA POR FERROCARRIL
492110|TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS VIA METRO Y METROTREN
492120|TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS VIA LOCOMOCION COLECTIVA
492130|TRANSPORTE DE PASAJEROS VIA TAXI COLECTIVO
492190|OTRAS ACTIVIDADES DE TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS POR VIA TERRESTRE N.C.P.
492210|SERVICIOS DE TRANSPORTE DE ESCOLARES
492220|SERVICIOS DE TRANSPORTE DE TRABAJADORES
492230|SERVICIOS DE TRANSPORTE DE PASAJEROS EN TAXIS LIBRES Y RADIOTAXIS
492240|SERVICIOS DE TRANSPORTE A TURISTAS
492250|TRANSPORTE DE PASAJEROS EN BUSES INTERURBANOS
492290|OTRAS ACTIVIDADES DE TRANSPORTE DE PASAJEROS POR VIA TERRESTRE N.C.P.
492300|TRANSPORTE DE CARGA POR CARRETERA
493010|TRANSPORTE POR OLEODUCTOS
493020|TRANSPORTE POR GASODUCTOS
493090|OTRAS ACTIVIDADES DE TRANSPORTE POR TUBERIAS N.C.P.
501100|TRANSPORTE DE PASAJEROS MARITIMO Y DE CABOTAJE
501200|TRANSPORTE DE CARGA MARITIMO Y DE CABOTAJE
502100|TRANSPORTE DE PASAJEROS POR VIAS DE NAVEGACION INTERIORES
502200|TRANSPORTE DE CARGA POR VIAS DE NAVEGACION INTERIORES
511000|TRANSPORTE DE PASAJEROS POR VIA AEREA
512000|TRANSPORTE DE CARGA POR VIA AEREA
521001|EXPLOTACION DE FRIGORIFICOS PARA ALMACENAMIENTO Y DEPOSITO
521009|OTROS SERVICIOS DE ALMACENAMIENTO Y DEPOSITO N.C.P.
522110|EXPLOTACION DE TERMINALES TERRESTRES DE PASAJEROS
522120|EXPLOTACION DE ESTACIONAMIENTOS DE VEHICULOS AUTOMOTORES Y PARQUIMETROS
522130|SERVICIOS PRESTADOS POR CONCESIONARIOS DE CARRETERAS
522190|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE TERRESTRE N.C.P.
522200|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE ACUATICO
522300|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE AEREO
522400|MANIPULACION DE LA CARGA
522910|AGENCIAS DE ADUANAS
522920|AGENCIAS DE NAVES
522990|OTRAS ACTIVIDADES DE APOYO AL TRANSPORTE N.C.P.
531000|ACTIVIDADES POSTALES
532000|ACTIVIDADES DE MENSAJERIA
551001|ACTIVIDADES DE HOTELES
551002|ACTIVIDADES DE MOTELES
551003|ACTIVIDADES DE RESIDENCIALES PARA TURISTAS
551009|OTRAS ACTIVIDADES DE ALOJAMIENTO PARA TURISTAS N.C.P.
552000|ACTIVIDADES DE CAMPING Y DE PARQUES PARA CASAS RODANTES
559001|ACTIVIDADES DE RESIDENCIALES PARA ESTUDIANTES Y TRABAJADORES
559009|OTRAS ACTIVIDADES DE ALOJAMIENTO N.C.P.
561000|ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MOVIL DE COMIDAS
562100|SUMINISTRO DE COMIDAS POR ENCARGO (SERVICIOS DE BANQUETERIA)
562900|SUMINISTRO INDUSTRIAL DE COMIDAS POR ENCARGO, CONCESION DE SERVICIOS DE ALIMENTACION
563001|ACTIVIDADES DE DISCOTECAS Y CABARET (NIGHT CLUB), CON PREDOMINIO DEL SERVICIO DE BEBIDAS
563009|OTRAS ACTIVIDADES DE SERVICIO DE BEBIDAS N.C.P.
581100|EDICION DE LIBROS
581200|EDICION DE DIRECTORIOS Y LISTAS DE CORREO
581300|EDICION DE DIARIOS, REVISTAS Y OTRAS PUBLICACIONES PERIODICAS
581900|OTRAS ACTIVIDADES DE EDICION
582000|EDICION DE PROGRAMAS INFORMATICOS
591100|ACTIVIDADES DE PRODUCCION DE PELICULAS CINEMATOGRAFICAS, VIDEOS Y PROGRAMAS DE TELEVISION
591200|ACTIVIDADES DE POSTPRODUCCION DE PELICULAS CINEMATOGRAFICAS, VIDEOS Y PROGRAMAS DE TELEVISION
591300|ACTIVIDADES DE DISTRIBUCION DE PELICULAS CINEMATOGRAFICAS, VIDEOS Y PROGRAMAS DE TELEVISION
591400|ACTIVIDADES DE EXHIBICION DE PELICULAS CINEMATOGRAFICAS Y CINTAS DE VIDEO
592000|ACTIVIDADES DE GRABACION DE SONIDO Y EDICION DE MUSICA
601000|TRANSMISIONES DE RADIO
602000|PROGRAMACION Y TRANSMISIONES DE TELEVISION
611010|TELEFONIA FIJA
611020|TELEFONIA LARGA DISTANCIA
611030|TELEVISION DE PAGO POR CABLE
611090|OTROS SERVICIOS DE TELECOMUNICACIONES ALAMBRICAS N.C.P.
612010|TELEFONIA MOVIL CELULAR
612020|RADIOCOMUNICACIONES MOVILES
612030|TELEVISION DE PAGO INALAMBRICA
612090|OTROS SERVICIOS DE TELECOMUNICACIONES INALAMBRICAS N.C.P.
613020|TELEVISION DE PAGO SATELITAL
613090|OTROS SERVICIOS DE TELECOMUNICACIONES POR SATELITE N.C.P.
619010|CENTROS DE LLAMADOS Y CENTROS DE ACCESO A INTERNET
619090|OTRAS ACTIVIDADES DE TELECOMUNICACIONES N.C.P.
620100|ACTIVIDADES DE PROGRAMACION INFORMATICA
620200|ACTIVIDADES DE CONSULTORIA DE INFORMATICA Y DE GESTION DE INSTALACIONES INFORMATICAS
620900|OTRAS ACTIVIDADES DE TECNOLOGIA DE LA INFORMACION Y DE SERVICIOS INFORMATICOS
631100|PROCESAMIENTO DE DATOS, HOSPEDAJE Y ACTIVIDADES CONEXAS
631200|PORTALES WEB
639100|ACTIVIDADES DE AGENCIAS DE NOTICIAS
639900|OTRAS ACTIVIDADES DE SERVICIOS DE INFORMACION N.C.P.
641910|ACTIVIDADES BANCARIAS
641990|OTROS TIPOS DE INTERMEDIACION MONETARIA N.C.P.
642000|ACTIVIDADES DE SOCIEDADES DE CARTERA
643000|FONDOS Y SOCIEDADES DE INVERSION Y ENTIDADES FINANCIERAS SIMILARES
649100|LEASING FINANCIERO
649201|FINANCIERAS
649202|ACTIVIDADES DE CREDITO PRENDARIO
649209|OTRAS ACTIVIDADES DE CONCESION DE CREDITO N.C.P.
649900|OTRAS ACTIVIDADES DE SERVICIOS FINANCIEROS, EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES N.C.P.
651100|SEGUROS DE VIDA
651210|SEGUROS GENERALES, EXCEPTO ACTIVIDADES DE ISAPRES
651220|ACTIVIDADES DE ISAPRES
652000|REASEGUROS
661100|ADMINISTRACION DE MERCADOS FINANCIEROS
661201|ACTIVIDADES DE SECURITIZADORAS
661202|CORREDORES DE BOLSA
661203|AGENTES DE VALORES
661204|ACTIVIDADES DE CASAS DE CAMBIO Y OPERADORES DE DIVISA
661209|OTROS SERVICIOS DE CORRETAJE DE VALORES Y COMMODITIES N.C.P.
661901|ACTIVIDADES DE CAMARAS DE COMPENSACION
661902|ADMINISTRACION DE TARJETAS DE CREDITO
661903|EMPRESAS DE ASESORIA Y CONSULTORIA EN INVERSION FINANCIERA, SOCIEDADES DE APOYO AL GIRO
661904|ACTIVIDADES DE CLASIFICADORAS DE RIESGO
661909|OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS N.C.P.
662100|EVALUACION DE RIESGOS Y DAÑOS (INCLUYE ACTIVIDADES DE LIQUIDADORES DE SEGUROS)
662200|ACTIVIDADES DE AGENTES Y CORREDORES DE SEGUROS
662900|OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SEGUROS Y FONDOS DE PENSIONES
663010|ADMINISTRADORAS DE FONDOS DE PENSIONES (AFP)
663091|ADMINISTRADORAS DE FONDOS DE INVERSION
663092|ADMINISTRADORAS DE FONDOS MUTUOS
663093|ADMINISTRADORAS DE FICES (FONDOS DE INVERSION DE CAPITAL EXTRANJERO)
663094|ADMINISTRADORAS DE FONDOS PARA LA VIVIENDA
663099|ADMINISTRADORAS DE FONDOS PARA OTROS FINES N.C.P.
681011|ALQUILER DE BIENES INMUEBLES AMOBLADOS O CON EQUIPOS Y MAQUINARIAS
681012|COMPRA, VENTA Y ALQUILER (EXCEPTO AMOBLADOS) DE INMUEBLES
681020|SERVICIOS IMPUTADOS DE ALQUILER DE VIVIENDAS
682000|ACTIVIDADES INMOBILIARIAS REALIZADAS A CAMBIO DE UNA RETRIBUCION O POR CONTRATA
691001|SERVICIOS DE ASESORAMIENTO Y REPRESENTACION JURIDICA
691002|SERVICIO NOTARIAL
691003|CONSERVADOR DE BIENES RAICES
691009|SERVICIOS DE ARBITRAJE, SINDICOS DE QUIEBRA Y PERITOS JUDICIALES, OTRAS ACTIVIDADES JURIDICAS N.C.P.
692000|ACTIVIDADES DE CONTABILIDAD, TENEDURIA DE LIBROS Y AUDITORIA, CONSULTORIA FISCAL
701000|ACTIVIDADES DE OFICINAS PRINCIPALES
702000|ACTIVIDADES DE CONSULTORIA DE GESTION
711001|SERVICIOS DE ARQUITECTURA (DISEÑO DE EDIFICIOS, DIBUJO DE PLANOS DE CONSTRUCCION, ENTRE OTROS)
711002|EMPRESAS DE SERVICIOS DE INGENIERIA Y ACTIVIDADES CONEXAS DE CONSULTORIA TECNICA
711003|SERVICIOS PROFESIONALES DE INGENIERIA Y ACTIVIDADES CONEXAS DE CONSULTORIA TECNICA
712001|ACTIVIDADES DE PLANTAS DE REVISION TECNICA PARA VEHICULOS AUTOMOTORES
712009|OTROS SERVICIOS DE ENSAYOS Y ANALISIS TECNICOS (EXCEPTO ACTIVIDADES DE PLANTAS DE REVISION TECNICA)
721000|INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES Y LA INGENIERIA
722000|INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES
731001|SERVICIOS DE PUBLICIDAD PRESTADOS POR EMPRESAS
731002|SERVICIOS DE PUBLICIDAD PRESTADOS POR PROFESIONALES
732000|ESTUDIOS DE MERCADO Y ENCUESTAS DE OPINION PUBLICA
741001|ACTIVIDADES DE DISEÑO DE VESTUARIO
741002|ACTIVIDADES DE DISEÑO Y DECORACION DE INTERIORES
741009|OTRAS ACTIVIDADES ESPECIALIZADAS DE DISEÑO N.C.P.
742001|SERVICIOS DE REVELADO, IMPRESION Y AMPLIACION DE FOTOGRAFIAS
742002|SERVICIOS Y ACTIVIDADES DE FOTOGRAFIA
742003|SERVICIOS PERSONALES DE FOTOGRAFIA
749001|ASESORIA Y GESTION EN LA COMPRA O VENTA DE PEQUEÑAS Y MEDIANAS EMPRESAS
749002|SERVICIOS DE TRADUCCION E INTERPRETACION PRESTADOS POR EMPRESAS
749003|SERVICIOS PERSONALES DE TRADUCCION E INTERPRETACION
749004|ACTIVIDADES DE AGENCIAS Y AGENTES DE REPRESENTACION DE ACTORES, DEPORTISTAS Y OTRAS FIGURAS PUBLICAS
749009|OTRAS ACTIVIDADES PROFESIONALES, CIENTIFICAS Y TECNICAS N.C.P.
750001|ACTIVIDADES DE CLINICAS VETERINARIAS
750002|ACTIVIDADES DE VETERINARIOS, TECNICOS Y OTRO PERSONAL AUXILIAR, PRESTADOS DE FORMA INDEPENDIENTE
771000|ALQUILER DE VEHICULOS AUTOMOTORES SIN CHOFER
772100|ALQUILER Y ARRENDAMIENTO DE EQUIPO RECREATIVO Y DEPORTIVO
772200|ALQUILER DE CINTAS DE VIDEO Y DISCOS
772900|ALQUILER DE OTROS EFECTOS PERSONALES Y ENSERES DOMESTICOS (INCLUYE MOBILIARIO PARA EVENTOS)
773001|ALQUILER DE EQUIPOS DE TRANSPORTE SIN OPERARIO, EXCEPTO VEHICULOS AUTOMOTORES
773002|ALQUILER DE MAQUINARIA Y EQUIPO AGROPECUARIO, FORESTAL, DE CONSTRUCCION E ING. CIVIL, SIN OPERARIOS
773003|ALQUILER DE MAQUINARIA Y EQUIPO DE OFICINA, SIN OPERARIOS (SIN SERVICIO ADMINISTRATIVO)
773009|ALQUILER DE OTROS TIPOS DE MAQUINARIAS Y EQUIPOS SIN OPERARIO N.C.P.
774000|ARRENDAMIENTO DE PROPIEDAD INTELECTUAL Y SIMILARES, EXCEPTO OBRAS PROTEGIDAS POR DERECHOS DE AUTOR
781000|ACTIVIDADES DE AGENCIAS DE EMPLEO
782000|ACTIVIDADES DE AGENCIAS DE EMPLEO TEMPORAL (INCLUYE EMPRESAS DE SERVICIOS TRANSITORIOS)
783000|OTRAS ACTIVIDADES DE DOTACION DE RECURSOS HUMANOS
791100|ACTIVIDADES DE AGENCIAS DE VIAJES
791200|ACTIVIDADES DE OPERADORES TURISTICOS
799000|OTROS SERVICIOS DE RESERVAS Y ACTIVIDADES CONEXAS (INCLUYE VENTA DE ENTRADAS PARA TEATRO, Y OTROS)
801001|SERVICIOS DE SEGURIDAD PRIVADA PRESTADOS POR EMPRESAS
801002|SERVICIO DE TRANSPORTE DE VALORES EN VEHICULOS BLINDADOS
801003|SERVICIOS DE SEGURIDAD PRIVADA PRESTADOS POR INDEPENDIENTES
802000|ACTIVIDADES DE SERVICIOS DE SISTEMAS DE SEGURIDAD (INCLUYE SERVICIOS DE CERRAJERIA)
803000|ACTIVIDADES DE INVESTIGACION (INCLUYE ACTIVIDADES DE INVESTIGADORES Y DETECTIVES PRIVADOS)
811000|ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES
812100|LIMPIEZA GENERAL DE EDIFICIOS
812901|DESRATIZACION, DESINFECCION Y EXTERMINIO DE PLAGAS NO AGRICOLAS
812909|OTRAS ACTIVIDADES DE LIMPIEZA DE EDIFICIOS E INSTALACIONES INDUSTRIALES N.C.P.
813000|ACTIVIDADES DE PAISAJISMO, SERVICIOS DE JARDINERIA Y SERVICIOS CONEXOS
821100|ACTIVIDADES COMBINADAS DE SERVICIOS ADMINISTRATIVOS DE OFICINA
821900|FOTOCOPIADO, PREPARACION DE DOCUMENTOS Y OTRAS ACTIVIDADES ESPECIALIZADAS DE APOYO DE OFICINA
822000|ACTIVIDADES DE CALL-CENTER
823000|ORGANIZACION DE CONVENCIONES Y EXPOSICIONES COMERCIALES
829110|ACTIVIDADES DE AGENCIAS DE COBRO
829120|ACTIVIDADES DE AGENCIAS DE CALIFICACION CREDITICIA
829200|ACTIVIDADES DE ENVASADO Y EMPAQUETADO
829900|OTRAS ACTIVIDADES DE SERVICIOS DE APOYO A LAS EMPRESAS N.C.P.
841100|ACTIVIDADES DE LA ADMINISTRACION PUBLICA EN GENERAL
841200|REGULACION DE LAS ACTIVIDADES DE ORGANISMOS QUE PRESTAN SERVICIOS SANITARIOS, EDUCATIVOS, CULTURALES
841300|REGULACION Y FACILITACION DE LA ACTIVIDAD ECONOMICA
842100|RELACIONES EXTERIORES
842200|ACTIVIDADES DE DEFENSA
842300|ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PUBLICO Y DE SEGURIDAD
843090|OTROS PLANES DE SEGURIDAD SOCIAL DE AFILIACION OBLIGATORIA N.C.P.
850011|ENSEÑANZA PREESCOLAR PUBLICA
850012|ENSEÑANZA PRIMARIA, SECUNDARIA CIENTIFICO HUMANISTA Y TECNICO PROFESIONAL PUBLICA
850021|ENSEÑANZA PREESCOLAR PRIVADA
850022|ENSEÑANZA PRIMARIA, SECUNDARIA CIENTIFICO HUMANISTA Y TECNICO PROFESIONAL PRIVADA
853110|ENSEÑANZA SUPERIOR EN UNIVERSIDADES PUBLICAS
853120|ENSEÑANZA SUPERIOR EN UNIVERSIDADES PRIVADAS
853201|ENSEÑANZA SUPERIOR EN INSTITUTOS PROFESIONALES
853202|ENSEÑANZA SUPERIOR EN CENTROS DE FORMACION TECNICA
854100|ENSEÑANZA DEPORTIVA Y RECREATIVA
854200|ENSEÑANZA CULTURAL
854901|ENSEÑANZA PREUNIVERSITARIA
854902|SERVICIOS PERSONALES DE EDUCACION
854909|OTROS TIPOS DE ENSEÑANZA N.C.P.
855000|ACTIVIDADES DE APOYO A LA ENSEÑANZA
861010|ACTIVIDADES DE HOSPITALES Y CLINICAS PUBLICAS
861020|ACTIVIDADES DE HOSPITALES Y CLINICAS PRIVADAS
862010|ACTIVIDADES DE CENTROS DE SALUD MUNICIPALIZADOS (SERVICIOS DE SALUD PUBLICA)
862021|CENTROS MEDICOS PRIVADOS (ESTABLECIMIENTOS DE ATENCION AMBULATORIA)
862022|CENTROS DE ATENCION ODONTOLOGICA PRIVADOS (ESTABLECIMIENTOS DE ATENCION AMBULATORIA)
862031|SERVICIOS DE MEDICOS PRESTADOS DE FORMA INDEPENDIENTE
862032|SERVICIOS DE ODONTOLOGOS PRESTADOS DE FORMA INDEPENDIENTE
869010|ACTIVIDADES DE LABORATORIOS CLINICOS Y BANCOS DE SANGRE
869091|OTROS SERVICIOS DE ATENCION DE LA SALUD HUMANA PRESTADOS POR EMPRESAS
869092|SERVICIOS PRESTADOS DE FORMA INDEPENDIENTE POR OTROS PROFESIONALES DE LA SALUD
871000|ACTIVIDADES DE ATENCION DE ENFERMERIA EN INSTITUCIONES
872000|ACTIVIDADES DE ATENCION EN INSTITUCIONES PARA PERSONAS CON DISCAPACIDAD MENTAL Y TOXICOMANOS
873000|ACTIVIDADES DE ATENCION EN INSTITUCIONES PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD FISICA
879000|OTRAS ACTIVIDADES DE ATENCION EN INSTITUCIONES
881000|ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD
889000|OTRAS ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO
900001|SERVICIOS DE PRODUCCION DE OBRAS DE TEATRO, CONCIERTOS, ESPECTACULOS DE DANZA, OTRAS PROD. ESCENICAS
900002|ACTIVIDADES ARTISTICAS REALIZADAS POR BANDAS DE MUSICA, COMPAÑIAS DE TEATRO, CIRCENSES Y SIMILARES
900003|ACTIVIDADES DE ARTISTAS REALIZADAS DE FORMA INDEPENDIENTE: ACTORES, MUSICOS, ESCRITORES, ENTRE OTROS
900004|SERVICIOS PRESTADOS POR PERIODISTAS INDEPENDIENTES
900009|OTRAS ACTIVIDADES CREATIVAS, ARTISTICAS Y DE ENTRETENIMIENTO N.C.P.
910100|ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS
910200|ACTIVIDADES DE MUSEOS, GESTION DE LUGARES Y EDIFICIOS HISTORICOS
910300|ACTIVIDADES DE JARDINES BOTANICOS, ZOOLOGICOS Y RESERVAS NATURALES
920010|ACTIVIDADES DE CASINOS DE JUEGOS
920090|OTRAS ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS N.C.P.
931101|HIPODROMOS
931102|GESTION DE SALAS DE BILLAR, GESTION DE SALAS DE BOLOS (BOWLING)
931109|GESTION DE OTRAS INSTALACIONES DEPORTIVAS N.C.P.
931201|ACTIVIDADES DE CLUBES DE FUTBOL AMATEUR Y PROFESIONAL
931209|ACTIVIDADES DE OTROS CLUBES DEPORTIVOS N.C.P.
931901|PROMOCION Y ORGANIZACION DE COMPETENCIAS DEPORTIVAS
931909|OTRAS ACTIVIDADES DEPORTIVAS N.C.P.
932100|ACTIVIDADES DE PARQUES DE ATRACCIONES Y PARQUES TEMATICOS
932901|GESTION DE SALAS DE POOL, GESTION (EXPLOTACION) DE JUEGOS ELECTRONICOS
932909|OTRAS ACTIVIDADES DE ESPARCIMIENTO Y RECREATIVAS N.C.P.
941100|ACTIVIDADES DE ASOCIACIONES EMPRESARIALES Y DE EMPLEADORES
941200|ACTIVIDADES DE ASOCIACIONES PROFESIONALES
942000|ACTIVIDADES DE SINDICATOS
949100|ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS
949200|ACTIVIDADES DE ORGANIZACIONES POLITICAS
949901|ACTIVIDADES DE CENTROS DE MADRES
949902|ACTIVIDADES DE CLUBES SOCIALES
949903|FUNDACIONES Y CORPORACIONES, ASOCIACIONES QUE PROMUEVEN ACTIVIDADES CULTURALES O RECREATIVAS
949904|CONSEJO DE ADMINISTRACION DE EDIFICIOS Y CONDOMINIOS
949909|ACTIVIDADES DE OTRAS ASOCIACIONES N.C.P.
951100|REPARACION DE COMPUTADORES Y EQUIPO PERIFERICO
951200|REPARACION DE EQUIPO DE COMUNICACIONES (INCLUYE LA REPARACION TELEFONOS CELULARES)
952100|REPARACION DE APARATOS ELECTRONICOS DE CONSUMO (INCLUYE APARATOS DE TELEVISION Y RADIO)
952200|REPARACION DE APARATOS DE USO DOMESTICO, EQUIPO DOMESTICO Y DE JARDINERIA
952300|REPARACION DE CALZADO Y DE ARTICULOS DE CUERO
952400|REPARACION DE MUEBLES Y ACCESORIOS DOMESTICOS
952900|REPARACION DE OTROS EFECTOS PERSONALES Y ENSERES DOMESTICOS
960100|LAVADO Y LIMPIEZA, INCLUIDA LA LIMPIEZA EN SECO, DE PRODUCTOS TEXTILES Y DE PIEL
960200|PELUQUERIA Y OTROS TRATAMIENTOS DE BELLEZA
960310|SERVICIOS FUNERARIOS
960320|SERVICIOS DE CEMENTERIOS
960901|SERVICIOS DE ADIESTRAMIENTO, GUARDERIA, PELUQUERIA, PASEO DE MASCOTAS (EXCEPTO ACT. VETERINARIAS)
960902|ACTIVIDADES DE SALONES DE MASAJES, BAÑOS TURCOS, SAUNAS, SERVICIO DE BAÑOS PUBLICOS
960909|OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.
970000|ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMESTICO
990000|ACTIVIDADES DE ORGANIZACIONES Y ORGANOS EXTRATERRITORIALES
`;

/** Código de actividad del SII (6 dígitos) → descripción oficial. */
export const CL_SII_ACTIVITY_DESCRIPTIONS: ReadonlyMap<string, string> = new Map(
  RAW.split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => {
      const at = line.indexOf('|');
      return [line.slice(0, at), line.slice(at + 1)] as const;
    }),
);

const normalizeText = (value: string): string => value.replace(/\s+/g, ' ').trim().toUpperCase();

/** Descripción oficial de un código, o `null` si el código no existe. */
export function describeClSiiActivity(code: string | null | undefined): string | null {
  if (typeof code !== 'string') return null;
  return CL_SII_ACTIVITY_DESCRIPTIONS.get(code.trim()) ?? null;
}

/**
 * ¿Dicen lo mismo el código (PUB_NOM_ACTECOS) y el texto (PUB_EMPRESAS_PJ)?
 * Falso si falta cualquiera de los dos o si el código no está en la tabla.
 */
export function clSiiActivityTextMatchesCode(
  code: string | null | undefined,
  activityText: string | null | undefined,
): boolean {
  const description = describeClSiiActivity(code);
  if (description === null || typeof activityText !== 'string') return false;
  return normalizeText(activityText) === normalizeText(description);
}
