/**
 * BR Receita CNPJ — FULL JOIN dry-run runner scaffold (BR-SOURCE-11A / 11C Option B).
 *
 * The first technical runner for the Receita CNPJ full join, implemented as a LOCAL
 * NO-WRITE / NO-RUNTIME scaffold. It composes the three BR-SOURCE-11A safety modules
 * — the no-write guard, the output sanitizer, and the failure-cleanup model — into a
 * single entry point that produces an AGGREGATE, sanitized report.
 *
 * ── Why this runner cannot execute the real dataset ─────────────────────────────
 * None of the eight approval gates is approved (legal/privacy, temporary storage
 * envelope, field allowlist, identity grain, output sanitization, failure cleanup,
 * operator runbook, no-write/no-runtime). So:
 *
 *   - `synthetic_fixture_only` (the DEFAULT) scores an injected or built-in SYNTHETIC
 *     fixture with no file I/O at all.
 *
 *   - `local_manifest_dry_run` is authorized ONLY under the BR-SOURCE-11C **Option B
 *     carve-out**: a SYNTHETIC TEMP MANIFEST generated by a test or by the controlled
 *     synthetic-temp CLI. Reading a REAL manifest, or a real Receita data file, is
 *     still exactly what GATE-1 (legal/privacy) and GATE-2 (temporary storage
 *     envelope) would have to authorize, and neither is approved — so any manifest
 *     whose trust is not `synthetic_temp_manifest_only` fails closed with
 *     `local_manifest_execution_not_authorized`.
 *
 * ── Option B is a NARROW carve-out ──────────────────────────────────────────────
 * `local_manifest_dry_run` proceeds only when EVERY one of these holds:
 *   `allowLocalManifest`, `manifestTrust === 'synthetic_temp_manifest_only'`,
 *   `optionBCarveoutAuthorized`, `strict`, `productionWrites === false`, an explicit
 *   `outputSanitizationVersion === 'not_approved'`, all four bounded caps present and
 *   within their Option B maxima, and an injected local-manifest reader. Anything
 *   missing or out of bounds fails closed with a value-free error code.
 *
 * The runner itself stays PURE: it never imports `node:fs` and never opens a file.
 * Reading the synthetic temp workspace is delegated to an INJECTED reader port
 * (`BrazilReceitaFullJoinLocalManifestReader`), implemented by
 * `br-receita-cnpj-synthetic-temp-manifest.ts`, which owns the temp directory it
 * created itself and nothing else.
 *
 * ── The runner NEVER ────────────────────────────────────────────────────────────
 *   - downloads, unzips, imports, or processes the full dataset.
 *   - opens a manifest, a CSV, a ZIP, or any file (no filesystem import at all).
 *   - opens a real manifest, or reads a real Receita data file, under any flag.
 *   - opens a Supabase client, reads env vars, or writes to any database.
 *   - integrates runtime, Agent 1, providers, HubSpot, or Slack.
 *   - constructs a `record_identity_key` or a `normalized_tax_id`.
 *   - returns a row, a cell value, a full CNPJ, a CNPJ básico, a CPF, a legal name, a
 *     trade name, an email, a phone, an address, a join key, a filesystem path, or a
 *     hash of any of them.
 *   - approves a gate, or declares Brazil ready for import, runtime, or Agent 1.
 *
 * Synthetic fixture rows carry OPAQUE structural refs (never dataset-shaped) that are
 * used for in-memory association only and are never counted into, or emitted by, the
 * report.
 */

import {
  BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE,
  BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY,
} from './br-receita-cnpj-manifest';
import {
  BR_RECEITA_CNPJ_JOIN_DEFAULT_MAX_COMPANY_SCAN_ROWS,
  BR_RECEITA_CNPJ_JOIN_MAX_COMPANY_SCAN_ROWS_LIMIT,
} from './br-receita-cnpj-company-establishment-join-dry-run';
import {
  BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  BR_RECEITA_CNPJ_PRIVACY_MAX_SAMPLE_ROWS_LIMIT,
} from './br-receita-cnpj-privacy-safe-classifier';
import {
  BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE,
  assertBrazilReceitaFullJoinNoWrite,
} from './br-receita-cnpj-full-join-no-write-guard';
import {
  BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE,
  sanitizeBrazilReceitaFullJoinReport,
} from './br-receita-cnpj-full-join-output-sanitizer';
import {
  planBrazilReceitaFullJoinCleanup,
  type BrazilReceitaFullJoinCleanupReport,
} from './br-receita-cnpj-full-join-cleanup';

// ─── Public constants ─────────────────────────────────────────────────────────

export const BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE = 'br_receita_full_join_dry_run' as const;

export type BrazilReceitaFullJoinRunMode = 'synthetic_fixture_only' | 'local_manifest_dry_run';

export const BRAZIL_RECEITA_FULL_JOIN_RUN_MODES: readonly BrazilReceitaFullJoinRunMode[] = [
  'synthetic_fixture_only',
  'local_manifest_dry_run',
];

/** The DEFAULT mode. A caller that states nothing gets the safest behaviour. */
export const BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE: BrazilReceitaFullJoinRunMode =
  'synthetic_fixture_only';

/**
 * Absolute ceiling on synthetic fixture size. A fixture beyond this is not a fixture
 * — it is a dataset, and it fails closed. Keeps "synthetic" structurally small.
 */
export const BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS = 10_000 as const;

/** The only output-sanitization version this hito recognizes: GATE-5 is not approved. */
export const BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION = 'not_approved' as const;

// ─── Option B carve-out contract (BR-SOURCE-11C) ──────────────────────────────

/**
 * How much a local manifest is trusted.
 *
 *   `not_applicable`                — no local manifest is involved at all.
 *   `synthetic_temp_manifest_only`  — the manifest was GENERATED by this codebase in a
 *                                     temp workspace it owns, from synthetic cells.
 *                                     The ONLY value Option B authorizes.
 *   `real_manifest_not_authorized`  — anything else, including an operator's real
 *                                     manifest. Always refused.
 */
export type BrazilReceitaFullJoinManifestTrust =
  | 'not_applicable'
  | 'synthetic_temp_manifest_only'
  | 'real_manifest_not_authorized';

/** The only manifest trust level the Option B carve-out authorizes. */
export const BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST =
  'synthetic_temp_manifest_only' as const;

/** The default trust for a local manifest whose provenance was not declared. */
export const BRAZIL_RECEITA_FULL_JOIN_DEFAULT_MANIFEST_TRUST: BrazilReceitaFullJoinManifestTrust =
  'real_manifest_not_authorized';

/** The only layout mode a local-manifest dry-run may declare (the official files). */
export const BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_LAYOUT_MODE = 'official_headerless' as const;

/**
 * File families a local-manifest dry-run may scan. SOCIOS / QSA / CPF are absent by
 * construction: they are a categorically excluded personal-data source, never a family.
 */
export const BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_ALLOWED_FAMILIES: readonly string[] = [
  'empresas',
  'estabelecimentos',
  'simples',
  'cnaes',
  'municipios',
  'naturezas',
];

/**
 * Hard Option B ceilings. These are STRICTER than the generic synthetic-fixture caps:
 * a synthetic temp-manifest run is plumbing verification, not a sampling exercise.
 * Every one of the four is REQUIRED — an omitted cap is a fail-closed error, never a
 * defaulted one, because a cap the caller never stated is a cap nobody agreed to.
 */
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_ROWS = 20 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_ESTABLISHMENT_ROWS = 20 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_SCAN_ROWS = 1_000 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_BYTES_PER_FILE = 1_000_000 as const;

// ─── Synthetic fixture contract ───────────────────────────────────────────────

export type BrazilReceitaFullJoinSyntheticEligibility =
  | 'eligible_for_future_import'
  | 'needs_legal_review'
  | 'excluded_privacy_signal'
  | 'excluded_legal_nature';

/**
 * One synthetic company row. `companyRef` is an OPAQUE structural reference used for
 * in-memory association only — it is deliberately not dataset-shaped, and it is never
 * counted into or emitted by the report.
 */
export interface BrazilReceitaFullJoinSyntheticCompanyRow {
  readonly companyRef: string;
  readonly eligibility: BrazilReceitaFullJoinSyntheticEligibility;
}

/** One synthetic establishment row. `companyRef: null` models a missing join ref. */
export interface BrazilReceitaFullJoinSyntheticEstablishmentRow {
  readonly companyRef: string | null;
  readonly privacySignal: boolean;
}

export interface BrazilReceitaFullJoinSyntheticFixture {
  readonly companies: readonly BrazilReceitaFullJoinSyntheticCompanyRow[];
  readonly establishments: readonly BrazilReceitaFullJoinSyntheticEstablishmentRow[];
}

/**
 * The built-in synthetic fixture: one of every join outcome, so a default run
 * exercises every branch. Refs are opaque labels, never dataset-shaped values.
 */
export function defaultBrazilReceitaFullJoinSyntheticFixture(): BrazilReceitaFullJoinSyntheticFixture {
  return {
    companies: [
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', eligibility: 'eligible_for_future_import' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_BRAVO', eligibility: 'needs_legal_review' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_CHARLIE', eligibility: 'excluded_privacy_signal' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_DELTA', eligibility: 'excluded_legal_nature' },
    ],
    establishments: [
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_BRAVO', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_CHARLIE', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_DELTA', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_ECHO_ABSENT', privacySignal: false },
      { companyRef: null, privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', privacySignal: true },
    ],
  };
}

// ─── Local manifest reader port (Option B) ────────────────────────────────────

/**
 * What the reader is allowed to ask for. Every cap is passed IN, so the reader
 * enforces the same bounds at read time that the runner enforces at gate time — a
 * bounded read is not a courtesy the reader may skip.
 */
export interface BrazilReceitaFullJoinLocalManifestReadRequest {
  readonly maxBytesPerFile: number;
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
}

/**
 * What the reader returns: STRUCTURAL scan metadata plus a synthetic fixture in the
 * runner's own shape. Deliberately no path, no filename, no raw line, and no cell —
 * the reader translates its workspace into aggregate-scoreable structure, so the
 * runner can stay pure and can never be handed dataset content to leak.
 *
 * The fields are typed loosely (`string`) on purpose: the reader sits at a trust
 * boundary, so the runner re-validates the trust level, the layout mode, and every
 * family name against its own allowlists rather than believing the declaration.
 */
export interface BrazilReceitaFullJoinLocalManifestScan {
  readonly manifestTrust: string;
  readonly layoutMode: string;
  /** Family labels scanned (`empresas`, `estabelecimentos`, …). Validated, then counted. */
  readonly familiesScanned: readonly string[];
  readonly filesScanned: number;
  /** True when the bounded per-file read ceiling was enforced during the read. */
  readonly bytesCapApplied: boolean;
  /** True when a file was LARGER than the per-file ceiling — a fail-closed condition. */
  readonly bytesCapExceeded: boolean;
  readonly fixture: BrazilReceitaFullJoinSyntheticFixture;
}

/** The injected port. The runner calls it at most ONCE per run, inside a try/catch. */
export type BrazilReceitaFullJoinLocalManifestReader = (
  request: BrazilReceitaFullJoinLocalManifestReadRequest,
) => BrazilReceitaFullJoinLocalManifestScan;

// ─── Input contract ───────────────────────────────────────────────────────────

/**
 * The runner's input. The escalation fields are literal-typed so no internal caller
 * can request a write, a runtime hop, an Agent 1 call, or an import without a type
 * error — and the no-write guard re-validates them at runtime anyway, because input
 * can arrive from a CLI boundary as `unknown`.
 */
export interface BrazilReceitaFullJoinDryRunInput {
  /** Accepted but NEVER opened by the runner: only the injected reader touches disk. */
  readonly manifest?: unknown;
  readonly mode?: BrazilReceitaFullJoinRunMode;
  readonly allowLocalManifest?: boolean;
  readonly maxCompanyRows?: number;
  readonly maxEstablishmentRows?: number;
  readonly maxCompanyScanRows?: number;
  readonly outputSanitizationVersion?: typeof BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION;
  /** Optional injected fixture; defaults to the built-in synthetic fixture. */
  readonly syntheticFixture?: BrazilReceitaFullJoinSyntheticFixture;

  // ── Option B carve-out (BR-SOURCE-11C). Only meaningful in local-manifest mode. ──
  /** The owner's explicit Option B authorization. Absent ⇒ local mode refuses. */
  readonly optionBCarveoutAuthorized?: boolean;
  /** Declared provenance of the manifest. Only the synthetic temp value is accepted. */
  readonly manifestTrust?: BrazilReceitaFullJoinManifestTrust;
  /** Option B runs are strict-only: a lenient local-manifest run does not exist. */
  readonly strict?: boolean;
  /** Required bounded per-file read ceiling. */
  readonly maxBytesPerFile?: number;
  /** The injected reader port. Absent ⇒ local mode refuses (the runner opens nothing). */
  readonly localManifestReader?: BrazilReceitaFullJoinLocalManifestReader;

  readonly noWriteMode: true;
  readonly runtimeIntegration: false;
  readonly agent1Integration: false;
  readonly supabaseWrite: false;
  readonly providerCalls?: false;
  readonly importExecuted?: false;
  readonly productionWrites?: false;
}

// ─── Report contract ──────────────────────────────────────────────────────────

/** Every gate stays `not_approved` in BR-SOURCE-11A — asserted, not computed. */
export interface BrazilReceitaFullJoinDecisionStatus {
  readonly gate_1_legal_privacy: 'not_approved';
  readonly gate_2_temporary_storage: 'not_approved';
  readonly gate_3_field_allowlist: 'not_approved';
  readonly gate_4_identity_grain: 'not_approved';
  readonly gate_5_output_sanitization: 'not_approved';
  readonly gate_6_failure_cleanup: 'not_approved';
  readonly gate_7_operator_runbook: 'not_approved';
  readonly gate_8_no_write_no_runtime: 'not_approved';
}

const DECISION_STATUS_ALL_NOT_APPROVED: BrazilReceitaFullJoinDecisionStatus = {
  gate_1_legal_privacy: 'not_approved',
  gate_2_temporary_storage: 'not_approved',
  gate_3_field_allowlist: 'not_approved',
  gate_4_identity_grain: 'not_approved',
  gate_5_output_sanitization: 'not_approved',
  gate_6_failure_cleanup: 'not_approved',
  gate_7_operator_runbook: 'not_approved',
  gate_8_no_write_no_runtime: 'not_approved',
};

export interface BrazilReceitaFullJoinRunScope {
  readonly full_dataset_processed: false;
  readonly import_executed: false;
  readonly supabase_write: false;
  readonly runtime_integration: false;
  readonly agent1_integration: false;
  readonly provider_calls: false;
  readonly production_writes: false;
}

const RUN_SCOPE_ALL_FALSE: BrazilReceitaFullJoinRunScope = {
  full_dataset_processed: false,
  import_executed: false,
  supabase_write: false,
  runtime_integration: false,
  agent1_integration: false,
  provider_calls: false,
  production_writes: false,
};

export interface BrazilReceitaFullJoinSafety {
  readonly raw_rows_printed: false;
  readonly cnpj_basico_printed: false;
  readonly cnpj_completo_printed: false;
  readonly cpf_printed: false;
  readonly join_keys_printed: false;
  readonly identity_keys_constructed: false;
  readonly identity_keys_printed: false;
  readonly record_identity_keys_printed: false;
  readonly normalized_tax_ids_printed: false;
  readonly person_data_printed: false;
  readonly hashes_of_identifiers_printed: false;
}

const SAFETY_ALL_FALSE: BrazilReceitaFullJoinSafety = {
  raw_rows_printed: false,
  cnpj_basico_printed: false,
  cnpj_completo_printed: false,
  cpf_printed: false,
  join_keys_printed: false,
  identity_keys_constructed: false,
  identity_keys_printed: false,
  record_identity_keys_printed: false,
  normalized_tax_ids_printed: false,
  person_data_printed: false,
  hashes_of_identifiers_printed: false,
};

/** Where in the run an error was raised. Fixed stage labels, never a path. */
export type BrazilReceitaFullJoinErrorStage =
  | 'no_write_guard'
  | 'mode_resolution'
  | 'option_b_gate'
  | 'limit_validation'
  | 'local_manifest_read'
  | 'fixture_validation'
  | 'synthetic_join'
  | 'output_sanitization';

/** Why the run failed. Fixed machine codes; a raw message is NEVER carried. */
export type BrazilReceitaFullJoinErrorCode =
  | typeof BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE
  | typeof BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE
  | 'invalid_run_mode'
  | 'allow_local_manifest_required'
  | 'local_manifest_execution_not_authorized'
  | 'sample_row_limit_exceeded'
  | 'company_scan_row_limit_exceeded'
  | 'full_dataset_processing_not_allowed'
  | 'output_sanitization_version_not_approved'
  | 'synthetic_fixture_invalid'
  // ── Option B (BR-SOURCE-11C) ──
  | 'option_b_carveout_not_authorized'
  | 'strict_mode_required'
  | 'production_writes_requested'
  | 'local_manifest_caps_required'
  | 'local_manifest_cap_exceeded'
  | 'local_manifest_reader_required'
  | 'local_manifest_read_failed'
  | 'local_manifest_scan_invalid'
  | 'local_manifest_layout_mode_not_authorized'
  | 'local_manifest_forbidden_file_family'
  | 'local_manifest_bytes_cap_exceeded';

export interface BrazilReceitaFullJoinReportError {
  readonly error_code: BrazilReceitaFullJoinErrorCode;
  readonly stage: BrazilReceitaFullJoinErrorStage;
}

export interface BrazilReceitaFullJoinDryRunReport {
  readonly ok: boolean;
  readonly mode: typeof BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE;
  readonly run_mode: BrazilReceitaFullJoinRunMode;
  /** Declared provenance of the manifest, if any. Never a path, never a filename. */
  readonly manifest_trust: BrazilReceitaFullJoinManifestTrust;
  /** Whether the owner's Option B carve-out was declared for THIS run. */
  readonly option_b_carveout_authorized: boolean;
  readonly source_key: typeof BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY;
  readonly country_code: typeof BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE;
  /**
   * Always null: a real manifest is never opened, and the synthetic temp manifest's
   * period is workspace metadata that the report has no reason to carry.
   */
  readonly source_period: string | null;
  readonly decision_status: BrazilReceitaFullJoinDecisionStatus;
  readonly run_scope: BrazilReceitaFullJoinRunScope;
  readonly safety: BrazilReceitaFullJoinSafety;
  readonly aggregate_counts: Record<string, number>;
  readonly eligibility_counts: Record<string, number>;
  readonly join_counts: Record<string, number>;
  readonly guardrail_counts: Record<string, number>;
  readonly cleanup: BrazilReceitaFullJoinCleanupReport;
  readonly errors: readonly BrazilReceitaFullJoinReportError[];
}

// ─── Count scaffolding ────────────────────────────────────────────────────────

const AGGREGATE_COUNT_KEYS = [
  'company_rows_scanned',
  'company_rows_sampled',
  'company_rows_indexed',
  'company_rows_excluded',
  'establishment_rows_scanned',
  'establishment_refs_held_in_memory',
  // Zero in `synthetic_fixture_only`; populated by an Option B synthetic temp read.
  'local_manifest_files_scanned',
  'local_manifest_families_scanned',
] as const;

const ELIGIBILITY_COUNT_KEYS = [
  'eligible_for_future_import',
  'needs_legal_review',
  'excluded_privacy_signal',
  'excluded_legal_nature',
] as const;

const JOIN_COUNT_KEYS = [
  'joined_with_company_context',
  'missing_company_context',
  'excluded_by_company_context',
  'excluded_by_establishment_privacy_signal',
  'pending_full_join_context',
] as const;

const GUARDRAIL_COUNT_KEYS = [
  'company_sample_cap_applied',
  'company_scan_cap_applied',
  'establishment_sample_cap_applied',
  'coverage_scan_limit_reached',
  'no_write_guard_violations',
  'forbidden_output_findings',
  // Option B: the bounded per-file read ceiling, and forbidden-family refusals.
  'local_manifest_bytes_cap_applied',
  'local_manifest_forbidden_family_findings',
] as const;

function zeroCounts(keys: readonly string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const key of keys) counts[key] = 0;
  return counts;
}

// ─── Limit validation ─────────────────────────────────────────────────────────

interface ResolvedLimits {
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
}

interface LimitFailure {
  readonly code: BrazilReceitaFullJoinErrorCode;
}

function resolveBoundedRows(
  requested: number | undefined,
  fallback: number,
): ResolvedLimitOutcome<number> {
  const value = requested ?? fallback;
  if (!Number.isFinite(value)) {
    return { ok: false, failure: { code: 'full_dataset_processing_not_allowed' } };
  }
  if (!Number.isInteger(value) || value < 0) {
    return { ok: false, failure: { code: 'sample_row_limit_exceeded' } };
  }
  if (value > BR_RECEITA_CNPJ_PRIVACY_MAX_SAMPLE_ROWS_LIMIT) {
    return { ok: false, failure: { code: 'sample_row_limit_exceeded' } };
  }
  return { ok: true, value };
}

function resolveCompanyScanRows(requested: number | undefined): ResolvedLimitOutcome<number> {
  const value = requested ?? BR_RECEITA_CNPJ_JOIN_DEFAULT_MAX_COMPANY_SCAN_ROWS;
  if (!Number.isFinite(value)) {
    return { ok: false, failure: { code: 'full_dataset_processing_not_allowed' } };
  }
  if (!Number.isInteger(value) || value < 0) {
    return { ok: false, failure: { code: 'company_scan_row_limit_exceeded' } };
  }
  if (value > BR_RECEITA_CNPJ_JOIN_MAX_COMPANY_SCAN_ROWS_LIMIT) {
    return { ok: false, failure: { code: 'company_scan_row_limit_exceeded' } };
  }
  return { ok: true, value };
}

type ResolvedLimitOutcome<T> = { ok: true; value: T } | { ok: false; failure: LimitFailure };

function resolveLimits(
  input: BrazilReceitaFullJoinDryRunInput,
): ResolvedLimitOutcome<ResolvedLimits> {
  const company = resolveBoundedRows(
    input.maxCompanyRows,
    BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  );
  if (!company.ok) return company;
  const establishment = resolveBoundedRows(
    input.maxEstablishmentRows,
    BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  );
  if (!establishment.ok) return establishment;
  const scan = resolveCompanyScanRows(input.maxCompanyScanRows);
  if (!scan.ok) return scan;
  return {
    ok: true,
    value: {
      maxCompanyRows: company.value,
      maxEstablishmentRows: establishment.value,
      maxCompanyScanRows: scan.value,
    },
  };
}

// ─── Synthetic join scoring (pure, aggregate-only) ────────────────────────────

type CompanyContextKind = 'usable_context' | 'blocked_context';

interface SyntheticJoinOutcome {
  readonly aggregate: Record<string, number>;
  readonly eligibility: Record<string, number>;
  readonly join: Record<string, number>;
  readonly coverageScanLimitReached: boolean;
}

function contextKindOf(eligibility: BrazilReceitaFullJoinSyntheticEligibility): CompanyContextKind {
  return eligibility === 'eligible_for_future_import' || eligibility === 'needs_legal_review'
    ? 'usable_context'
    : 'blocked_context';
}

/**
 * Scores the synthetic fixture into aggregate counts. PURE and value-free: company
 * refs live only in a local Map that is discarded on return, and no ref, label, or
 * fixture value is ever written into the returned counts.
 *
 * The company index is built over the bounded SCAN window (the deeper probe, mirroring
 * the BR-SOURCE-10H coverage strategy); `company_rows_sampled` separately reports the
 * shallower bounded sample so both bounds stay visible in the report.
 */
function scoreSyntheticJoin(
  fixture: BrazilReceitaFullJoinSyntheticFixture,
  limits: ResolvedLimits,
): SyntheticJoinOutcome {
  const aggregate = zeroCounts(AGGREGATE_COUNT_KEYS);
  const eligibility = zeroCounts(ELIGIBILITY_COUNT_KEYS);
  const join = zeroCounts(JOIN_COUNT_KEYS);

  const companyIndex = new Map<string, CompanyContextKind>();
  const scanWindow = fixture.companies.slice(0, limits.maxCompanyScanRows);
  for (const row of scanWindow) {
    aggregate.company_rows_scanned += 1;
    eligibility[row.eligibility] += 1;
    const kind = contextKindOf(row.eligibility);
    if (row.companyRef.trim() === '') {
      aggregate.company_rows_excluded += 1;
      continue;
    }
    if (!companyIndex.has(row.companyRef)) companyIndex.set(row.companyRef, kind);
    if (kind === 'usable_context') aggregate.company_rows_indexed += 1;
    else aggregate.company_rows_excluded += 1;
  }
  aggregate.company_rows_sampled = Math.min(fixture.companies.length, limits.maxCompanyRows);

  const establishmentWindow = fixture.establishments.slice(0, limits.maxEstablishmentRows);
  const refsHeld = new Set<string>();
  for (const row of establishmentWindow) {
    aggregate.establishment_rows_scanned += 1;

    if (row.privacySignal) {
      join.excluded_by_establishment_privacy_signal += 1;
      continue;
    }
    const ref = row.companyRef?.trim() ?? '';
    if (ref === '') {
      join.pending_full_join_context += 1;
      continue;
    }
    refsHeld.add(ref);
    if (companyIndex.size === 0) {
      join.pending_full_join_context += 1;
      continue;
    }
    const context = companyIndex.get(ref);
    if (context === undefined) {
      join.missing_company_context += 1;
      continue;
    }
    if (context === 'usable_context') join.joined_with_company_context += 1;
    else join.excluded_by_company_context += 1;
  }
  aggregate.establishment_refs_held_in_memory = refsHeld.size;

  return {
    aggregate,
    eligibility,
    join,
    coverageScanLimitReached: fixture.companies.length > limits.maxCompanyScanRows,
  };
}

// ─── Report assembly ──────────────────────────────────────────────────────────

/**
 * The run's declared provenance, carried through every exit path so a refused report
 * says the same thing about itself as a successful one.
 */
interface RunProvenance {
  readonly runMode: BrazilReceitaFullJoinRunMode;
  readonly manifestTrust: BrazilReceitaFullJoinManifestTrust;
  readonly optionBCarveoutAuthorized: boolean;
}

interface ReportDraft {
  readonly ok: boolean;
  readonly provenance: RunProvenance;
  readonly aggregate: Record<string, number>;
  readonly eligibility: Record<string, number>;
  readonly join: Record<string, number>;
  readonly guardrail: Record<string, number>;
  readonly cleanup: BrazilReceitaFullJoinCleanupReport;
  readonly errors: readonly BrazilReceitaFullJoinReportError[];
}

function assembleReport(draft: ReportDraft): BrazilReceitaFullJoinDryRunReport {
  return {
    ok: draft.ok,
    mode: BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE,
    run_mode: draft.provenance.runMode,
    manifest_trust: draft.provenance.manifestTrust,
    option_b_carveout_authorized: draft.provenance.optionBCarveoutAuthorized,
    source_key: BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY,
    country_code: BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE,
    source_period: null,
    decision_status: DECISION_STATUS_ALL_NOT_APPROVED,
    run_scope: RUN_SCOPE_ALL_FALSE,
    safety: SAFETY_ALL_FALSE,
    aggregate_counts: draft.aggregate,
    eligibility_counts: draft.eligibility,
    join_counts: draft.join,
    guardrail_counts: draft.guardrail,
    cleanup: draft.cleanup,
    errors: draft.errors,
  };
}

/**
 * Builds the fail-closed report for an aborted run: every count zero, cleanup marked
 * required, and the sanitized error recorded. No partial metric survives a failure.
 */
function failClosedReport(
  provenance: RunProvenance,
  errors: readonly BrazilReceitaFullJoinReportError[],
  guardViolations: number,
  sanitizerFindings: number,
  forbiddenFamilyFindings = 0,
): BrazilReceitaFullJoinDryRunReport {
  const guardrail = zeroCounts(GUARDRAIL_COUNT_KEYS);
  guardrail.no_write_guard_violations = guardViolations;
  guardrail.forbidden_output_findings = sanitizerFindings;
  guardrail.local_manifest_forbidden_family_findings = forbiddenFamilyFindings;

  return assembleReport({
    ok: false,
    provenance,
    aggregate: zeroCounts(AGGREGATE_COUNT_KEYS),
    eligibility: zeroCounts(ELIGIBILITY_COUNT_KEYS),
    join: zeroCounts(JOIN_COUNT_KEYS),
    guardrail,
    cleanup: planBrazilReceitaFullJoinCleanup({
      sanitizerFailed: sanitizerFindings > 0,
      guardFailed: guardViolations > 0,
      errorCount: errors.length,
    }),
    errors,
  });
}

// ─── Fixture validation ───────────────────────────────────────────────────────

function isValidFixture(fixture: BrazilReceitaFullJoinSyntheticFixture): boolean {
  if (!Array.isArray(fixture.companies) || !Array.isArray(fixture.establishments)) return false;
  for (const row of fixture.companies) {
    if (typeof row?.companyRef !== 'string') return false;
    if (!ELIGIBILITY_COUNT_KEYS.includes(row.eligibility)) return false;
  }
  for (const row of fixture.establishments) {
    if (row?.companyRef !== null && typeof row?.companyRef !== 'string') return false;
    if (typeof row?.privacySignal !== 'boolean') return false;
  }
  return true;
}

function exceedsSyntheticCeiling(fixture: BrazilReceitaFullJoinSyntheticFixture): boolean {
  return (
    fixture.companies.length > BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS ||
    fixture.establishments.length > BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS
  );
}

// ─── Guard config projection ──────────────────────────────────────────────────

/**
 * Projects the input into the object handed to the no-write guard: every declared
 * field EXCEPT the synthetic fixture (structural test data, not config), with the two
 * optional escalation flags defaulted to `false` so an omission is still a declaration.
 *
 * Passing the whole input matters: the guard's second job is detecting dangerous
 * indicators, and it can only find one if it is allowed to see it.
 */
function buildGuardConfig(input: BrazilReceitaFullJoinDryRunInput): Record<string, unknown> {
  const guardConfig: Record<string, unknown> = { providerCalls: false, importExecuted: false };
  for (const [key, value] of Object.entries(input)) {
    // Structural test data and the injected reader PORT are not configuration.
    if (key === 'syntheticFixture' || key === 'localManifestReader') continue;
    if (value === undefined) continue;
    guardConfig[key] = value;
  }
  return guardConfig;
}

// ─── Option B gate (BR-SOURCE-11C) ────────────────────────────────────────────

/** The bounded caps an Option B run must state explicitly. */
interface OptionBCaps {
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
  readonly maxBytesPerFile: number;
}

type OptionBGateOutcome =
  | { readonly ok: true; readonly caps: OptionBCaps }
  | { readonly ok: false; readonly code: BrazilReceitaFullJoinErrorCode };

/** True for a stated, non-negative, integral cap at or below its Option B ceiling. */
function isCapWithin(value: number | undefined, ceiling: number): boolean {
  return value !== undefined && Number.isInteger(value) && value >= 0 && value <= ceiling;
}

/**
 * Validates the FULL Option B contract before a single byte is read. Every condition
 * is independent and fail-closed, and the order is deliberate: manifest TRUST is
 * checked before the carve-out authorization, so a real manifest is refused as "real
 * manifest execution not authorized" whatever else the caller declared.
 */
function evaluateOptionBGate(
  input: BrazilReceitaFullJoinDryRunInput,
  manifestTrust: BrazilReceitaFullJoinManifestTrust,
): OptionBGateOutcome {
  if (input.allowLocalManifest !== true) {
    return { ok: false, code: 'allow_local_manifest_required' };
  }
  if (manifestTrust !== BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST) {
    return { ok: false, code: 'local_manifest_execution_not_authorized' };
  }
  if (input.optionBCarveoutAuthorized !== true) {
    return { ok: false, code: 'option_b_carveout_not_authorized' };
  }
  if (input.strict !== true) {
    return { ok: false, code: 'strict_mode_required' };
  }
  if (input.productionWrites !== undefined && input.productionWrites !== false) {
    return { ok: false, code: 'production_writes_requested' };
  }
  // GATE-5 is not approved, and an Option B run must SAY so rather than omit it.
  if (input.outputSanitizationVersion !== BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION) {
    return { ok: false, code: 'output_sanitization_version_not_approved' };
  }

  const stated = [
    input.maxCompanyRows,
    input.maxEstablishmentRows,
    input.maxCompanyScanRows,
    input.maxBytesPerFile,
  ];
  if (stated.some((cap) => cap === undefined)) {
    return { ok: false, code: 'local_manifest_caps_required' };
  }
  const withinBounds =
    isCapWithin(input.maxCompanyRows, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_ROWS) &&
    isCapWithin(
      input.maxEstablishmentRows,
      BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_ESTABLISHMENT_ROWS,
    ) &&
    isCapWithin(input.maxCompanyScanRows, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_SCAN_ROWS) &&
    isCapWithin(input.maxBytesPerFile, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_BYTES_PER_FILE);
  if (!withinBounds) {
    return { ok: false, code: 'local_manifest_cap_exceeded' };
  }
  if (typeof input.localManifestReader !== 'function') {
    return { ok: false, code: 'local_manifest_reader_required' };
  }

  return {
    ok: true,
    caps: {
      maxCompanyRows: input.maxCompanyRows as number,
      maxEstablishmentRows: input.maxEstablishmentRows as number,
      maxCompanyScanRows: input.maxCompanyScanRows as number,
      maxBytesPerFile: input.maxBytesPerFile as number,
    },
  };
}

interface ScanValidation {
  readonly code: BrazilReceitaFullJoinErrorCode;
  readonly forbiddenFamilyFindings: number;
}

/**
 * Re-validates what the reader claimed. The reader sits at a trust boundary, so its
 * declared trust level, layout mode, and family names are checked against the runner's
 * own allowlists — a reader cannot talk its way past the carve-out. Returns `null` when
 * the scan is acceptable.
 */
function validateLocalManifestScan(scan: unknown): ScanValidation | null {
  if (typeof scan !== 'object' || scan === null) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  const candidate = scan as Partial<BrazilReceitaFullJoinLocalManifestScan>;

  if (candidate.manifestTrust !== BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST) {
    return { code: 'local_manifest_execution_not_authorized', forbiddenFamilyFindings: 0 };
  }
  if (candidate.layoutMode !== BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_LAYOUT_MODE) {
    return { code: 'local_manifest_layout_mode_not_authorized', forbiddenFamilyFindings: 0 };
  }
  if (!Array.isArray(candidate.familiesScanned)) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  const forbidden = candidate.familiesScanned.filter(
    (family) =>
      typeof family !== 'string' ||
      !BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_ALLOWED_FAMILIES.includes(family),
  );
  if (forbidden.length > 0) {
    return {
      code: 'local_manifest_forbidden_file_family',
      forbiddenFamilyFindings: forbidden.length,
    };
  }
  if (candidate.bytesCapExceeded === true) {
    return { code: 'local_manifest_bytes_cap_exceeded', forbiddenFamilyFindings: 0 };
  }
  if (!Number.isInteger(candidate.filesScanned) || (candidate.filesScanned as number) < 0) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  if (typeof candidate.fixture !== 'object' || candidate.fixture === null) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  return null;
}

// ─── Public entry point ───────────────────────────────────────────────────────

/**
 * Runs the full join dry-run scaffold and returns an AGGREGATE, SANITIZED report.
 * Never throws for a policy violation — every refusal comes back as `ok: false` plus a
 * value-free error code, so a caller can print the report safely.
 *
 * Order of operations is deliberate and fail-closed at every step:
 *   1. no-write/no-runtime guard (nothing else runs if the contract is not declared);
 *   2. output-sanitization version check (GATE-5 is not approved);
 *   3. run-mode resolution;
 *   4a. `local_manifest_dry_run`: the full Option B gate, then ONE injected read whose
 *       result is re-validated against the runner's own allowlists;
 *   4b. `synthetic_fixture_only`: bounded-limit validation against the generic caps;
 *   5. fixture validation and scoring (identical for both modes);
 *   6. output sanitization of the assembled report — a leak discards the metrics.
 */
export function runBrazilReceitaFullJoinDryRun(
  input: BrazilReceitaFullJoinDryRunInput,
): BrazilReceitaFullJoinDryRunReport {
  const requestedMode = input.mode ?? BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE;
  const knownMode = BRAZIL_RECEITA_FULL_JOIN_RUN_MODES.includes(requestedMode);
  // An unknown mode is still reported against the SAFE default, never echoed back.
  const reportedMode = knownMode ? requestedMode : BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE;

  const manifestTrust: BrazilReceitaFullJoinManifestTrust =
    reportedMode === 'local_manifest_dry_run'
      ? (input.manifestTrust ?? BRAZIL_RECEITA_FULL_JOIN_DEFAULT_MANIFEST_TRUST)
      : 'not_applicable';
  const provenance: RunProvenance = {
    runMode: reportedMode,
    manifestTrust,
    optionBCarveoutAuthorized: input.optionBCarveoutAuthorized === true,
  };

  // 1) No-write / no-runtime guard. The WHOLE input is handed to the guard (minus the
  //    synthetic fixture and the reader port, which are structural rather than config)
  //    so that a dangerous indicator smuggled alongside the declared contract — a
  //    service-role key, a Supabase URL, a runtime endpoint — is detected, not ignored.
  const guard = assertBrazilReceitaFullJoinNoWrite(buildGuardConfig(input));
  if (!guard.ok) {
    return failClosedReport(
      provenance,
      [{ error_code: BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE, stage: 'no_write_guard' }],
      guard.violations.length,
      0,
    );
  }

  // 2) Output-sanitization version: GATE-5 is not approved, so nothing else is valid.
  if (
    input.outputSanitizationVersion !== undefined &&
    input.outputSanitizationVersion !== BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION
  ) {
    return failClosedReport(
      provenance,
      [{ error_code: 'output_sanitization_version_not_approved', stage: 'mode_resolution' }],
      0,
      0,
    );
  }

  // 3) Run mode.
  if (!knownMode) {
    return failClosedReport(
      provenance,
      [{ error_code: 'invalid_run_mode', stage: 'mode_resolution' }],
      0,
      0,
    );
  }

  let fixture: BrazilReceitaFullJoinSyntheticFixture;
  let limits: ResolvedLimits;
  const localManifest = { filesScanned: 0, familiesScanned: 0, bytesCapApplied: false };

  if (requestedMode === 'local_manifest_dry_run') {
    // 4a) Option B: the narrow synthetic-temp-manifest carve-out.
    const gate = evaluateOptionBGate(input, manifestTrust);
    if (!gate.ok) {
      return failClosedReport(
        provenance,
        [{ error_code: gate.code, stage: 'option_b_gate' }],
        0,
        0,
      );
    }

    let scan: BrazilReceitaFullJoinLocalManifestScan;
    try {
      // The ONE read of the run. The reader owns the temp workspace it created; the
      // runner passes the caps in and never learns a path.
      scan = input.localManifestReader!({
        maxBytesPerFile: gate.caps.maxBytesPerFile,
        maxCompanyRows: gate.caps.maxCompanyRows,
        maxEstablishmentRows: gate.caps.maxEstablishmentRows,
        maxCompanyScanRows: gate.caps.maxCompanyScanRows,
      });
    } catch {
      // The underlying error is DISCARDED: a reader failure could carry a path or a
      // cell in its message, so only the fixed stage/code survive.
      return failClosedReport(
        provenance,
        [{ error_code: 'local_manifest_read_failed', stage: 'local_manifest_read' }],
        0,
        0,
      );
    }

    const scanFailure = validateLocalManifestScan(scan);
    if (scanFailure !== null) {
      return failClosedReport(
        provenance,
        [{ error_code: scanFailure.code, stage: 'local_manifest_read' }],
        0,
        0,
        scanFailure.forbiddenFamilyFindings,
      );
    }

    fixture = scan.fixture;
    limits = {
      maxCompanyRows: gate.caps.maxCompanyRows,
      maxEstablishmentRows: gate.caps.maxEstablishmentRows,
      maxCompanyScanRows: gate.caps.maxCompanyScanRows,
    };
    localManifest.filesScanned = scan.filesScanned;
    localManifest.familiesScanned = scan.familiesScanned.length;
    localManifest.bytesCapApplied = scan.bytesCapApplied === true;
  } else {
    // 4b) Synthetic fixture mode: the generic bounded caps.
    const resolved = resolveLimits(input);
    if (!resolved.ok) {
      return failClosedReport(
        provenance,
        [{ error_code: resolved.failure.code, stage: 'limit_validation' }],
        0,
        0,
      );
    }
    limits = resolved.value;
    fixture = input.syntheticFixture ?? defaultBrazilReceitaFullJoinSyntheticFixture();
  }

  // 5) Fixture validation and scoring — identical for both modes, so a synthetic temp
  //    read cannot take a shortcut around the structural checks.
  if (!isValidFixture(fixture)) {
    return failClosedReport(
      provenance,
      [{ error_code: 'synthetic_fixture_invalid', stage: 'fixture_validation' }],
      0,
      0,
    );
  }
  if (exceedsSyntheticCeiling(fixture)) {
    return failClosedReport(
      provenance,
      [{ error_code: 'full_dataset_processing_not_allowed', stage: 'fixture_validation' }],
      0,
      0,
    );
  }

  const outcome = scoreSyntheticJoin(fixture, limits);
  const aggregate = { ...outcome.aggregate };
  aggregate.local_manifest_files_scanned = localManifest.filesScanned;
  aggregate.local_manifest_families_scanned = localManifest.familiesScanned;

  const guardrail = zeroCounts(GUARDRAIL_COUNT_KEYS);
  guardrail.company_sample_cap_applied = fixture.companies.length > limits.maxCompanyRows ? 1 : 0;
  guardrail.company_scan_cap_applied = outcome.coverageScanLimitReached ? 1 : 0;
  guardrail.establishment_sample_cap_applied =
    fixture.establishments.length > limits.maxEstablishmentRows ? 1 : 0;
  guardrail.coverage_scan_limit_reached = outcome.coverageScanLimitReached ? 1 : 0;
  guardrail.local_manifest_bytes_cap_applied = localManifest.bytesCapApplied ? 1 : 0;

  const candidate = assembleReport({
    ok: true,
    provenance,
    aggregate,
    eligibility: outcome.eligibility,
    join: outcome.join,
    guardrail,
    cleanup: planBrazilReceitaFullJoinCleanup({
      sanitizerFailed: false,
      guardFailed: false,
      errorCount: 0,
    }),
    errors: [],
  });

  // 6) Output sanitization. A leak discards every metric — the report never ships
  //    partially-sanitized data, and the offending value is never surfaced.
  const sanitized = sanitizeBrazilReceitaFullJoinReport(candidate);
  if (!sanitized.ok) {
    return failClosedReport(
      provenance,
      [
        {
          error_code: BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE,
          stage: 'output_sanitization',
        },
      ],
      0,
      sanitized.findings.length,
    );
  }

  return candidate;
}
