/**
 * BR Receita CNPJ — FULL JOIN dry-run runner scaffold (BR-SOURCE-11A / 11C Option B).
 *
 * The first technical runner for the Receita CNPJ full join, implemented as a LOCAL
 * NO-WRITE / NO-RUNTIME scaffold. It composes the three BR-SOURCE-11A safety modules
 * — the no-write guard, the output sanitizer, and the failure-cleanup model — into a
 * single entry point that produces an AGGREGATE, sanitized report.
 *
 * ── Why this runner cannot execute the real dataset ─────────────────────────────
 * None of the eight approval gates is approved (legal/privacy, temporary storage
 * envelope, field allowlist, identity grain, output sanitization, failure cleanup,
 * operator runbook, no-write/no-runtime). So:
 *
 *   - `synthetic_fixture_only` (the DEFAULT) scores an injected or built-in SYNTHETIC
 *     fixture with no file I/O at all.
 *
 *   - `local_manifest_dry_run` is authorized under exactly TWO narrow carve-outs, each
 *     selected by its own declared manifest TRUST and gated by its own owner flag:
 *
 *       · BR-SOURCE-11C **Option B** — `synthetic_temp_manifest_only`: a SYNTHETIC TEMP
 *         MANIFEST generated by a test or by the controlled synthetic-temp CLI, plus
 *         synthetic headerless CSVs, read under four bounded caps.
 *
 *       · BR-SOURCE-11D-META-IMPL — `real_manifest_metadata_only`: ONE real local
 *         manifest opened as a CONTROL DOCUMENT and parsed for schema-level metadata.
 *         **No file it references is ever opened or stat-ed**, and no row is read.
 *
 *     Any other trust — including a real manifest offered for EXECUTION — fails closed
 *     with `local_manifest_execution_not_authorized`. Reading a real Receita data file
 *     remains exactly what GATE-1 (legal/privacy) and GATE-2 (temporary storage
 *     envelope) would have to authorize, and neither is approved.
 *
 * ── Both carve-outs are NARROW, and neither substitutes for the other ───────────
 * The synthetic-temp branch proceeds only when EVERY one of these holds:
 *   `allowLocalManifest`, `manifestTrust === 'synthetic_temp_manifest_only'`,
 *   `optionBCarveoutAuthorized`, `strict`, `productionWrites === false`, an explicit
 *   `outputSanitizationVersion === 'not_approved'`, all four bounded caps present and
 *   within their Option B maxima, and an injected local-manifest reader.
 *
 * The metadata-only branch proceeds only when EVERY one of these holds:
 *   `allowLocalManifest`, `manifestTrust === 'real_manifest_metadata_only'`,
 *   `realManifestMetadataOnlyOptionBAuthorized`, `strict`, `productionWrites === false`,
 *   an explicit `outputSanitizationVersion === 'not_approved'`, both metadata caps
 *   (`maxManifestBytes`, `maxDeclaredFiles`) present and within their maxima, and an
 *   injected metadata reader.
 *
 * The owner phrases are separate, single-scope, and non-transferable, so the FLAGS are
 * separate too: `optionBCarveoutAuthorized` buys nothing on the metadata path, and
 * `realManifestMetadataOnlyOptionBAuthorized` buys nothing on the synthetic path.
 * Anything missing or out of bounds fails closed with a value-free error code.
 *
 * ── BR-SOURCE-11E: which manifest DOCUMENT may be named ─────────────────────────
 * A third flag, `realManifestMetadataOnlyExecutionAuthorized`, records that this run may
 * name the OPERATOR'S OWN prepared manifest rather than a synthetic one. It is a
 * WHICH-DOCUMENT authorization and nothing more: it relaxes no cap, opens no referenced
 * file, reads no row, computes no join, and does not satisfy the metadata gate above.
 *
 * The runner resolves no paths, so it cannot enforce the waiver — the reader does. What the
 * runner enforces is that the two declarations AGREE: a scan reporting
 * `operatorPreparedManifestAuthorized: true` on a run that did not declare the execution
 * authorization is refused with `real_manifest_metadata_execution_not_authorized`, and
 * carries no metadata block.
 *
 * The runner itself stays PURE: it never imports `node:fs` and never opens a file.
 * Reading is delegated to INJECTED reader ports — implemented by
 * `br-receita-cnpj-synthetic-temp-manifest.ts` (which owns the temp directory it created
 * itself and nothing else) and by `br-receita-cnpj-real-manifest-metadata-reader.ts`
 * (which resolves exactly one path, the manifest, and has no code path that opens a
 * second one).
 *
 * ── The runner NEVER ────────────────────────────────────────────────────────────
 *   - downloads, unzips, imports, or processes the full dataset.
 *   - opens a manifest, a CSV, a ZIP, or any file (no filesystem import at all).
 *   - opens a file a manifest references, or reads a real Receita data file, under any
 *     flag — including under the metadata-only carve-out.
 *   - reads, samples, counts, or hashes a row of real data under any flag.
 *   - opens a Supabase client, reads env vars, or writes to any database.
 *   - integrates runtime, Agent 1, providers, HubSpot, or Slack.
 *   - constructs a `record_identity_key` or a `normalized_tax_id`.
 *   - returns a row, a cell value, a full CNPJ, a CNPJ básico, a CPF, a legal name, a
 *     trade name, an email, a phone, an address, a join key, a filesystem path, or a
 *     hash of any of them.
 *   - approves a gate, or declares Brazil ready for import, runtime, or Agent 1.
 *
 * Synthetic fixture rows carry OPAQUE structural refs (never dataset-shaped) that are
 * used for in-memory association only and are never counted into, or emitted by, the
 * report.
 */

import {
  BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE,
  BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY,
} from './br-receita-cnpj-manifest';
import {
  BR_RECEITA_CNPJ_JOIN_DEFAULT_MAX_COMPANY_SCAN_ROWS,
  BR_RECEITA_CNPJ_JOIN_MAX_COMPANY_SCAN_ROWS_LIMIT,
} from './br-receita-cnpj-company-establishment-join-dry-run';
import {
  BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  BR_RECEITA_CNPJ_PRIVACY_MAX_SAMPLE_ROWS_LIMIT,
} from './br-receita-cnpj-privacy-safe-classifier';
import {
  BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE,
  assertBrazilReceitaFullJoinNoWrite,
} from './br-receita-cnpj-full-join-no-write-guard';
import {
  BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE,
  sanitizeBrazilReceitaFullJoinReport,
} from './br-receita-cnpj-full-join-output-sanitizer';
import {
  planBrazilReceitaFullJoinCleanup,
  type BrazilReceitaFullJoinCleanupReport,
} from './br-receita-cnpj-full-join-cleanup';

// ─── Public constants ─────────────────────────────────────────────────────────

export const BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE = 'br_receita_full_join_dry_run' as const;

export type BrazilReceitaFullJoinRunMode = 'synthetic_fixture_only' | 'local_manifest_dry_run';

export const BRAZIL_RECEITA_FULL_JOIN_RUN_MODES: readonly BrazilReceitaFullJoinRunMode[] = [
  'synthetic_fixture_only',
  'local_manifest_dry_run',
];

/** The DEFAULT mode. A caller that states nothing gets the safest behaviour. */
export const BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE: BrazilReceitaFullJoinRunMode =
  'synthetic_fixture_only';

/**
 * Absolute ceiling on synthetic fixture size. A fixture beyond this is not a fixture
 * — it is a dataset, and it fails closed. Keeps "synthetic" structurally small.
 */
export const BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS = 10_000 as const;

/** The only output-sanitization version this hito recognizes: GATE-5 is not approved. */
export const BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION = 'not_approved' as const;

// ─── Option B carve-out contract (BR-SOURCE-11C) ──────────────────────────────

/**
 * How much a local manifest is trusted.
 *
 *   `not_applicable`                — no local manifest is involved at all.
 *   `synthetic_temp_manifest_only`  — the manifest was GENERATED by this codebase in a
 *                                     temp workspace it owns, from synthetic cells. The
 *                                     only value the BR-SOURCE-11C carve-out authorizes.
 *   `real_manifest_metadata_only`   — a REAL local manifest, opened as a CONTROL
 *                                     DOCUMENT only: parsed for schema-level metadata,
 *                                     with no file it references ever opened or stat-ed.
 *                                     The only value the BR-SOURCE-11D-META-IMPL
 *                                     carve-out authorizes, and it authorizes NO row
 *                                     read (see `realManifestMetadataOnlyOptionBAuthorized`).
 *   `real_manifest_not_authorized`  — anything else, including an operator's real
 *                                     manifest offered for execution. Always refused.
 */
export type BrazilReceitaFullJoinManifestTrust =
  | 'not_applicable'
  | 'synthetic_temp_manifest_only'
  | 'real_manifest_metadata_only'
  | 'real_manifest_not_authorized';

/** The only manifest trust level the BR-SOURCE-11C synthetic carve-out authorizes. */
export const BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST =
  'synthetic_temp_manifest_only' as const;

/**
 * The only manifest trust level the BR-SOURCE-11D-META-IMPL metadata-only carve-out
 * authorizes. Deliberately a DIFFERENT value, gated by a DIFFERENT flag, from the
 * synthetic temp-manifest carve-out: the two owner phrases are separate, single-scope,
 * and non-transferable (decision record § 5.1), so neither trust level nor flag may
 * stand in for the other.
 */
export const BRAZIL_RECEITA_FULL_JOIN_REAL_MANIFEST_METADATA_ONLY_TRUST =
  'real_manifest_metadata_only' as const;

/** The default trust for a local manifest whose provenance was not declared. */
export const BRAZIL_RECEITA_FULL_JOIN_DEFAULT_MANIFEST_TRUST: BrazilReceitaFullJoinManifestTrust =
  'real_manifest_not_authorized';

/** The only layout mode a local-manifest dry-run may declare (the official files). */
export const BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_LAYOUT_MODE = 'official_headerless' as const;

/**
 * File families a local-manifest dry-run may scan. SOCIOS / QSA / CPF are absent by
 * construction: they are a categorically excluded personal-data source, never a family.
 */
export const BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_ALLOWED_FAMILIES: readonly string[] = [
  'empresas',
  'estabelecimentos',
  'simples',
  'cnaes',
  'municipios',
  'naturezas',
];

/**
 * Hard Option B ceilings. These are STRICTER than the generic synthetic-fixture caps:
 * a synthetic temp-manifest run is plumbing verification, not a sampling exercise.
 * Every one of the four is REQUIRED — an omitted cap is a fail-closed error, never a
 * defaulted one, because a cap the caller never stated is a cap nobody agreed to.
 */
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_ROWS = 20 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_ESTABLISHMENT_ROWS = 20 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_SCAN_ROWS = 1_000 as const;
export const BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_BYTES_PER_FILE = 1_000_000 as const;

// ─── Metadata-only carve-out contract (BR-SOURCE-11D-META-IMPL) ────────────────

/**
 * Hard ceilings for a real-manifest METADATA-ONLY run (decision record § 8). They bound
 * the ONE read that happens — the manifest document — and the parse loop over its
 * declared entries. Like the Option B caps, both are REQUIRED of the caller: a cap
 * nobody stated is a cap nobody agreed to.
 *
 * These numbers carry no implication whatsoever for real-data ceilings, which are a
 * GATE-2 deliverable and are neither proposed nor anticipated here.
 */
export const BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_MAX_MANIFEST_BYTES = 1_000_000 as const;
export const BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_MAX_DECLARED_FILES = 20 as const;

// ─── Synthetic fixture contract ───────────────────────────────────────────────

export type BrazilReceitaFullJoinSyntheticEligibility =
  | 'eligible_for_future_import'
  | 'needs_legal_review'
  | 'excluded_privacy_signal'
  | 'excluded_legal_nature';

/**
 * One synthetic company row. `companyRef` is an OPAQUE structural reference used for
 * in-memory association only — it is deliberately not dataset-shaped, and it is never
 * counted into or emitted by the report.
 */
export interface BrazilReceitaFullJoinSyntheticCompanyRow {
  readonly companyRef: string;
  readonly eligibility: BrazilReceitaFullJoinSyntheticEligibility;
}

/** One synthetic establishment row. `companyRef: null` models a missing join ref. */
export interface BrazilReceitaFullJoinSyntheticEstablishmentRow {
  readonly companyRef: string | null;
  readonly privacySignal: boolean;
}

export interface BrazilReceitaFullJoinSyntheticFixture {
  readonly companies: readonly BrazilReceitaFullJoinSyntheticCompanyRow[];
  readonly establishments: readonly BrazilReceitaFullJoinSyntheticEstablishmentRow[];
}

/**
 * The built-in synthetic fixture: one of every join outcome, so a default run
 * exercises every branch. Refs are opaque labels, never dataset-shaped values.
 */
export function defaultBrazilReceitaFullJoinSyntheticFixture(): BrazilReceitaFullJoinSyntheticFixture {
  return {
    companies: [
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', eligibility: 'eligible_for_future_import' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_BRAVO', eligibility: 'needs_legal_review' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_CHARLIE', eligibility: 'excluded_privacy_signal' },
      { companyRef: 'SYNTHETIC_COMPANY_REF_DELTA', eligibility: 'excluded_legal_nature' },
    ],
    establishments: [
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_BRAVO', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_CHARLIE', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_DELTA', privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_ECHO_ABSENT', privacySignal: false },
      { companyRef: null, privacySignal: false },
      { companyRef: 'SYNTHETIC_COMPANY_REF_ALPHA', privacySignal: true },
    ],
  };
}

// ─── Local manifest reader port (Option B) ────────────────────────────────────

/**
 * What the reader is allowed to ask for. Every cap is passed IN, so the reader
 * enforces the same bounds at read time that the runner enforces at gate time — a
 * bounded read is not a courtesy the reader may skip.
 */
export interface BrazilReceitaFullJoinLocalManifestReadRequest {
  readonly maxBytesPerFile: number;
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
}

/**
 * What the reader returns: STRUCTURAL scan metadata plus a synthetic fixture in the
 * runner's own shape. Deliberately no path, no filename, no raw line, and no cell —
 * the reader translates its workspace into aggregate-scoreable structure, so the
 * runner can stay pure and can never be handed dataset content to leak.
 *
 * The fields are typed loosely (`string`) on purpose: the reader sits at a trust
 * boundary, so the runner re-validates the trust level, the layout mode, and every
 * family name against its own allowlists rather than believing the declaration.
 */
export interface BrazilReceitaFullJoinLocalManifestScan {
  readonly manifestTrust: string;
  readonly layoutMode: string;
  /** Family labels scanned (`empresas`, `estabelecimentos`, …). Validated, then counted. */
  readonly familiesScanned: readonly string[];
  readonly filesScanned: number;
  /** True when the bounded per-file read ceiling was enforced during the read. */
  readonly bytesCapApplied: boolean;
  /** True when a file was LARGER than the per-file ceiling — a fail-closed condition. */
  readonly bytesCapExceeded: boolean;
  readonly fixture: BrazilReceitaFullJoinSyntheticFixture;
}

/** The injected port. The runner calls it at most ONCE per run, inside a try/catch. */
export type BrazilReceitaFullJoinLocalManifestReader = (
  request: BrazilReceitaFullJoinLocalManifestReadRequest,
) => BrazilReceitaFullJoinLocalManifestScan;

// ─── Real manifest metadata-only reader port (BR-SOURCE-11D-META-IMPL) ─────────

/**
 * What the metadata-only reader is asked for. Both caps are passed IN, so the reader
 * enforces at read time the same bounds the runner enforced at gate time.
 */
export interface BrazilReceitaFullJoinRealManifestMetadataReadRequest {
  readonly maxManifestBytes: number;
  readonly maxDeclaredFiles: number;
}

/**
 * What the metadata-only reader returns: SCHEMA-LEVEL metadata about a real manifest,
 * and nothing else. No path, no filename, no declared period value, no raw document, no
 * row, no cell — the reader translates the control document into aggregate structure so
 * the runner can stay pure and can never be handed content to leak.
 *
 * Typed loosely (`string`) on purpose: the reader sits at a trust boundary, so the
 * runner re-validates the trust level, the layout classification, and the structural
 * `referenced*` assertions against its own expectations rather than believing them.
 */
export interface BrazilReceitaFullJoinRealManifestMetadataScan {
  readonly manifestTrust: string;
  readonly layoutMode: string;
  readonly schemaVersionPresent: boolean;
  readonly sourcePeriodPresent: boolean;
  readonly declaredFileCount: number;
  /** Keys are allowlisted family labels plus `other`. A forbidden label is never a key. */
  readonly declaredFamilyCounts: Readonly<Record<string, number>>;
  readonly requiredFamilyCount: number;
  readonly missingRequiredFamilyCount: number;
  readonly forbiddenFamilyCount: number;
  readonly manifestBytesReadBucket: string;
  /**
   * Whether the reader relaxed its staging-segment / prepared-basename path checks under
   * the BR-SOURCE-11E execution declaration. Optional because a reader written before 11E
   * cannot state it; absent is read as `false`, which is the fail-closed direction.
   */
  readonly operatorPreparedManifestAuthorized?: boolean;
  readonly referencedDataFilesOpened: boolean;
  readonly referencedDataFilesStatted: boolean;
  /** A manifest-CONTENT refusal reported rather than thrown. `null` when acceptable. */
  readonly refusalCode: string | null;
}

/** The injected metadata-only port. Called at most ONCE per run, inside a try/catch. */
export type BrazilReceitaFullJoinRealManifestMetadataReader = (
  request: BrazilReceitaFullJoinRealManifestMetadataReadRequest,
) => BrazilReceitaFullJoinRealManifestMetadataScan;

/** The layout classification a metadata-only run must see to proceed. */
export const BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_LAYOUT_MODE = 'official_headerless' as const;

/** Family labels a metadata-only report may key a count under. */
export const BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_ALLOWED_FAMILY_KEYS: readonly string[] = [
  'empresas',
  'estabelecimentos',
  'simples',
  'cnaes',
  'municipios',
  'naturezas',
  'other',
];

/** The two byte buckets a metadata-only report may state. Never a byte figure. */
export const BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_BYTES_BUCKETS: readonly string[] = [
  'lte_1mb',
  'over_limit_blocked',
];

// ─── Input contract ───────────────────────────────────────────────────────────

/**
 * The runner's input. The escalation fields are literal-typed so no internal caller
 * can request a write, a runtime hop, an Agent 1 call, or an import without a type
 * error — and the no-write guard re-validates them at runtime anyway, because input
 * can arrive from a CLI boundary as `unknown`.
 */
export interface BrazilReceitaFullJoinDryRunInput {
  /** Accepted but NEVER opened by the runner: only the injected reader touches disk. */
  readonly manifest?: unknown;
  readonly mode?: BrazilReceitaFullJoinRunMode;
  readonly allowLocalManifest?: boolean;
  readonly maxCompanyRows?: number;
  readonly maxEstablishmentRows?: number;
  readonly maxCompanyScanRows?: number;
  readonly outputSanitizationVersion?: typeof BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION;
  /** Optional injected fixture; defaults to the built-in synthetic fixture. */
  readonly syntheticFixture?: BrazilReceitaFullJoinSyntheticFixture;

  // ── Option B carve-out (BR-SOURCE-11C). Only meaningful in local-manifest mode. ──
  /** The owner's explicit Option B authorization. Absent ⇒ local mode refuses. */
  readonly optionBCarveoutAuthorized?: boolean;
  /** Declared provenance of the manifest. Only the synthetic temp value is accepted. */
  readonly manifestTrust?: BrazilReceitaFullJoinManifestTrust;
  /** Option B runs are strict-only: a lenient local-manifest run does not exist. */
  readonly strict?: boolean;
  /** Required bounded per-file read ceiling. */
  readonly maxBytesPerFile?: number;
  /** The injected reader port. Absent ⇒ local mode refuses (the runner opens nothing). */
  readonly localManifestReader?: BrazilReceitaFullJoinLocalManifestReader;

  // ── Metadata-only carve-out (BR-SOURCE-11D-META-IMPL). Only meaningful when
  //    `manifestTrust === 'real_manifest_metadata_only'`. ──
  /**
   * The owner's REAL-MANIFEST METADATA-ONLY authorization, as a declared boolean. It is
   * a DISTINCT field from `optionBCarveoutAuthorized` on purpose: the synthetic
   * temp-manifest phrase authorizes nothing here, and this one authorizes nothing there.
   */
  readonly realManifestMetadataOnlyOptionBAuthorized?: boolean;
  /**
   * The owner's BR-SOURCE-11E EXECUTION authorization, as a declared boolean: this run may
   * name the OPERATOR'S OWN prepared manifest document instead of a synthetic one.
   *
   * A THIRD distinct field, and the narrowest of the three. It widens nothing about what
   * is done with the manifest — no referenced file, no row, no join, no cap relief — and it
   * does not stand in for `realManifestMetadataOnlyOptionBAuthorized`, which still gates
   * the metadata path. The runner does not resolve paths, so this flag buys the CALLER
   * nothing here; it exists so the report states which authorization was spent, and so a
   * reader that relaxed its path checks without the run declaring it is REFUSED.
   */
  readonly realManifestMetadataOnlyExecutionAuthorized?: boolean;
  /** Required ceiling on the ONE manifest read. */
  readonly maxManifestBytes?: number;
  /** Required ceiling on the declared-entry parse loop. */
  readonly maxDeclaredFiles?: number;
  /** The injected metadata-only port. Absent ⇒ metadata-only mode refuses. */
  readonly realManifestMetadataReader?: BrazilReceitaFullJoinRealManifestMetadataReader;

  readonly noWriteMode: true;
  readonly runtimeIntegration: false;
  readonly agent1Integration: false;
  readonly supabaseWrite: false;
  readonly providerCalls?: false;
  readonly importExecuted?: false;
  readonly productionWrites?: false;
}

// ─── Report contract ──────────────────────────────────────────────────────────

/** Every gate stays `not_approved` in BR-SOURCE-11A — asserted, not computed. */
export interface BrazilReceitaFullJoinDecisionStatus {
  readonly gate_1_legal_privacy: 'not_approved';
  readonly gate_2_temporary_storage: 'not_approved';
  readonly gate_3_field_allowlist: 'not_approved';
  readonly gate_4_identity_grain: 'not_approved';
  readonly gate_5_output_sanitization: 'not_approved';
  readonly gate_6_failure_cleanup: 'not_approved';
  readonly gate_7_operator_runbook: 'not_approved';
  readonly gate_8_no_write_no_runtime: 'not_approved';
}

const DECISION_STATUS_ALL_NOT_APPROVED: BrazilReceitaFullJoinDecisionStatus = {
  gate_1_legal_privacy: 'not_approved',
  gate_2_temporary_storage: 'not_approved',
  gate_3_field_allowlist: 'not_approved',
  gate_4_identity_grain: 'not_approved',
  gate_5_output_sanitization: 'not_approved',
  gate_6_failure_cleanup: 'not_approved',
  gate_7_operator_runbook: 'not_approved',
  gate_8_no_write_no_runtime: 'not_approved',
};

export interface BrazilReceitaFullJoinRunScope {
  readonly full_dataset_processed: false;
  readonly import_executed: false;
  readonly supabase_write: false;
  readonly runtime_integration: false;
  readonly agent1_integration: false;
  readonly provider_calls: false;
  readonly production_writes: false;
}

const RUN_SCOPE_ALL_FALSE: BrazilReceitaFullJoinRunScope = {
  full_dataset_processed: false,
  import_executed: false,
  supabase_write: false,
  runtime_integration: false,
  agent1_integration: false,
  provider_calls: false,
  production_writes: false,
};

export interface BrazilReceitaFullJoinSafety {
  readonly raw_rows_printed: false;
  readonly cnpj_basico_printed: false;
  readonly cnpj_completo_printed: false;
  readonly cpf_printed: false;
  readonly join_keys_printed: false;
  readonly identity_keys_constructed: false;
  readonly identity_keys_printed: false;
  readonly record_identity_keys_printed: false;
  readonly normalized_tax_ids_printed: false;
  readonly person_data_printed: false;
  readonly hashes_of_identifiers_printed: false;
}

const SAFETY_ALL_FALSE: BrazilReceitaFullJoinSafety = {
  raw_rows_printed: false,
  cnpj_basico_printed: false,
  cnpj_completo_printed: false,
  cpf_printed: false,
  join_keys_printed: false,
  identity_keys_constructed: false,
  identity_keys_printed: false,
  record_identity_keys_printed: false,
  normalized_tax_ids_printed: false,
  person_data_printed: false,
  hashes_of_identifiers_printed: false,
};

/** Where in the run an error was raised. Fixed stage labels, never a path. */
export type BrazilReceitaFullJoinErrorStage =
  | 'no_write_guard'
  | 'mode_resolution'
  | 'option_b_gate'
  | 'limit_validation'
  | 'local_manifest_read'
  | 'fixture_validation'
  | 'synthetic_join'
  | 'output_sanitization'
  // ── Metadata-only carve-out (BR-SOURCE-11D-META-IMPL) ──
  | 'real_manifest_metadata_gate'
  | 'real_manifest_metadata_read';

/** Why the run failed. Fixed machine codes; a raw message is NEVER carried. */
export type BrazilReceitaFullJoinErrorCode =
  | typeof BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE
  | typeof BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE
  | 'invalid_run_mode'
  | 'allow_local_manifest_required'
  | 'local_manifest_execution_not_authorized'
  | 'sample_row_limit_exceeded'
  | 'company_scan_row_limit_exceeded'
  | 'full_dataset_processing_not_allowed'
  | 'output_sanitization_version_not_approved'
  | 'synthetic_fixture_invalid'
  // ── Option B (BR-SOURCE-11C) ──
  | 'option_b_carveout_not_authorized'
  | 'strict_mode_required'
  | 'production_writes_requested'
  | 'local_manifest_caps_required'
  | 'local_manifest_cap_exceeded'
  | 'local_manifest_reader_required'
  | 'local_manifest_read_failed'
  | 'local_manifest_scan_invalid'
  | 'local_manifest_layout_mode_not_authorized'
  | 'local_manifest_forbidden_file_family'
  | 'local_manifest_bytes_cap_exceeded'
  // ── Metadata-only carve-out (BR-SOURCE-11D-META-IMPL) ──
  | 'real_manifest_metadata_only_not_authorized'
  | 'real_manifest_metadata_caps_required'
  | 'real_manifest_metadata_cap_exceeded'
  | 'real_manifest_metadata_reader_required'
  | 'real_manifest_metadata_read_failed'
  | 'real_manifest_metadata_scan_invalid'
  | 'real_manifest_metadata_layout_mode_not_authorized'
  | 'real_manifest_metadata_forbidden_family_detected'
  | 'real_manifest_metadata_missing_required_family'
  | 'real_manifest_metadata_referenced_file_access_detected'
  // ── Operator-prepared manifest execution (BR-SOURCE-11E) ──
  | 'real_manifest_metadata_execution_not_authorized';

export interface BrazilReceitaFullJoinReportError {
  readonly error_code: BrazilReceitaFullJoinErrorCode;
  readonly stage: BrazilReceitaFullJoinErrorStage;
}

/**
 * The AGGREGATE metadata block for a real-manifest metadata-only run. Every field is a
 * boolean, a count, or a class label — never a path, a filename, a declared period
 * value, or a fragment of the document. The four `*_opened` / `*_statted` / `*_printed`
 * assertions are held-absence claims: they are structurally always false, and they are
 * stated rather than omitted so a reader of the report can see that they hold.
 *
 * `null` on every non-metadata run. A metadata-only run reads NO row, so the join,
 * eligibility, and aggregate row counts on the surrounding report all stay zero — and
 * nothing in this block is citable as GATE-1 or GATE-2 evidence, or as evidence about
 * the real dataset's coverage, join rates, or eligibility.
 */
export interface BrazilReceitaFullJoinManifestMetadataReport {
  readonly schema_version_present: boolean;
  readonly source_period_present: boolean;
  readonly layout_mode: string;
  readonly declared_file_count: number;
  readonly required_family_count: number;
  readonly missing_required_family_count: number;
  readonly forbidden_family_count: number;
  /** Keys are allowlisted family labels plus `other`. A forbidden label is never a key. */
  readonly declared_family_counts: Record<string, number>;
  readonly required_families_present: boolean;
  readonly forbidden_families_present: boolean;
  readonly manifest_bytes_read_bucket: string;
  /**
   * Whether the manifest DOCUMENT that was read was an operator-prepared one, named under
   * the BR-SOURCE-11E execution declaration. Derived from the reader's own report rather
   * than from the caller's declaration, so this field cannot overclaim: it says a waiver
   * was spent only when the reader actually spent one. It says nothing about the dataset.
   */
  readonly operator_prepared_manifest_authorized: boolean;
  readonly referenced_data_files_opened: false;
  readonly referenced_data_files_statted: false;
  readonly raw_manifest_printed: false;
  readonly absolute_paths_printed: false;
}

export interface BrazilReceitaFullJoinDryRunReport {
  readonly ok: boolean;
  readonly mode: typeof BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE;
  readonly run_mode: BrazilReceitaFullJoinRunMode;
  /** Declared provenance of the manifest, if any. Never a path, never a filename. */
  readonly manifest_trust: BrazilReceitaFullJoinManifestTrust;
  /** Whether the owner's Option B carve-out was declared for THIS run. */
  readonly option_b_carveout_authorized: boolean;
  /** Whether the owner's METADATA-ONLY carve-out was declared for THIS run. */
  readonly real_manifest_metadata_only_option_b_authorized: boolean;
  /**
   * Whether the owner's BR-SOURCE-11E EXECUTION authorization — naming the operator's own
   * prepared manifest document — was declared for THIS run. `false` everywhere else.
   */
  readonly real_manifest_metadata_only_execution_authorized: boolean;
  readonly source_key: typeof BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY;
  readonly country_code: typeof BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE;
  /**
   * Always null: a real manifest is never opened, and the synthetic temp manifest's
   * period is workspace metadata that the report has no reason to carry.
   */
  readonly source_period: string | null;
  readonly decision_status: BrazilReceitaFullJoinDecisionStatus;
  readonly run_scope: BrazilReceitaFullJoinRunScope;
  readonly safety: BrazilReceitaFullJoinSafety;
  readonly aggregate_counts: Record<string, number>;
  readonly eligibility_counts: Record<string, number>;
  readonly join_counts: Record<string, number>;
  readonly guardrail_counts: Record<string, number>;
  /** Populated ONLY by a real-manifest metadata-only run; `null` everywhere else. */
  readonly manifest_metadata: BrazilReceitaFullJoinManifestMetadataReport | null;
  readonly cleanup: BrazilReceitaFullJoinCleanupReport;
  readonly errors: readonly BrazilReceitaFullJoinReportError[];
}

// ─── Count scaffolding ────────────────────────────────────────────────────────

const AGGREGATE_COUNT_KEYS = [
  'company_rows_scanned',
  'company_rows_sampled',
  'company_rows_indexed',
  'company_rows_excluded',
  'establishment_rows_scanned',
  'establishment_refs_held_in_memory',
  // Zero in `synthetic_fixture_only`; populated by an Option B synthetic temp read.
  'local_manifest_files_scanned',
  'local_manifest_families_scanned',
] as const;

const ELIGIBILITY_COUNT_KEYS = [
  'eligible_for_future_import',
  'needs_legal_review',
  'excluded_privacy_signal',
  'excluded_legal_nature',
] as const;

const JOIN_COUNT_KEYS = [
  'joined_with_company_context',
  'missing_company_context',
  'excluded_by_company_context',
  'excluded_by_establishment_privacy_signal',
  'pending_full_join_context',
] as const;

const GUARDRAIL_COUNT_KEYS = [
  'company_sample_cap_applied',
  'company_scan_cap_applied',
  'establishment_sample_cap_applied',
  'coverage_scan_limit_reached',
  'no_write_guard_violations',
  'forbidden_output_findings',
  // Option B: the bounded per-file read ceiling, and forbidden-family refusals.
  'local_manifest_bytes_cap_applied',
  'local_manifest_forbidden_family_findings',
] as const;

function zeroCounts(keys: readonly string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const key of keys) counts[key] = 0;
  return counts;
}

// ─── Limit validation ─────────────────────────────────────────────────────────

interface ResolvedLimits {
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
}

interface LimitFailure {
  readonly code: BrazilReceitaFullJoinErrorCode;
}

function resolveBoundedRows(
  requested: number | undefined,
  fallback: number,
): ResolvedLimitOutcome<number> {
  const value = requested ?? fallback;
  if (!Number.isFinite(value)) {
    return { ok: false, failure: { code: 'full_dataset_processing_not_allowed' } };
  }
  if (!Number.isInteger(value) || value < 0) {
    return { ok: false, failure: { code: 'sample_row_limit_exceeded' } };
  }
  if (value > BR_RECEITA_CNPJ_PRIVACY_MAX_SAMPLE_ROWS_LIMIT) {
    return { ok: false, failure: { code: 'sample_row_limit_exceeded' } };
  }
  return { ok: true, value };
}

function resolveCompanyScanRows(requested: number | undefined): ResolvedLimitOutcome<number> {
  const value = requested ?? BR_RECEITA_CNPJ_JOIN_DEFAULT_MAX_COMPANY_SCAN_ROWS;
  if (!Number.isFinite(value)) {
    return { ok: false, failure: { code: 'full_dataset_processing_not_allowed' } };
  }
  if (!Number.isInteger(value) || value < 0) {
    return { ok: false, failure: { code: 'company_scan_row_limit_exceeded' } };
  }
  if (value > BR_RECEITA_CNPJ_JOIN_MAX_COMPANY_SCAN_ROWS_LIMIT) {
    return { ok: false, failure: { code: 'company_scan_row_limit_exceeded' } };
  }
  return { ok: true, value };
}

type ResolvedLimitOutcome<T> = { ok: true; value: T } | { ok: false; failure: LimitFailure };

function resolveLimits(
  input: BrazilReceitaFullJoinDryRunInput,
): ResolvedLimitOutcome<ResolvedLimits> {
  const company = resolveBoundedRows(
    input.maxCompanyRows,
    BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  );
  if (!company.ok) return company;
  const establishment = resolveBoundedRows(
    input.maxEstablishmentRows,
    BR_RECEITA_CNPJ_PRIVACY_DEFAULT_MAX_SAMPLE_ROWS,
  );
  if (!establishment.ok) return establishment;
  const scan = resolveCompanyScanRows(input.maxCompanyScanRows);
  if (!scan.ok) return scan;
  return {
    ok: true,
    value: {
      maxCompanyRows: company.value,
      maxEstablishmentRows: establishment.value,
      maxCompanyScanRows: scan.value,
    },
  };
}

// ─── Synthetic join scoring (pure, aggregate-only) ────────────────────────────

type CompanyContextKind = 'usable_context' | 'blocked_context';

interface SyntheticJoinOutcome {
  readonly aggregate: Record<string, number>;
  readonly eligibility: Record<string, number>;
  readonly join: Record<string, number>;
  readonly coverageScanLimitReached: boolean;
}

function contextKindOf(eligibility: BrazilReceitaFullJoinSyntheticEligibility): CompanyContextKind {
  return eligibility === 'eligible_for_future_import' || eligibility === 'needs_legal_review'
    ? 'usable_context'
    : 'blocked_context';
}

/**
 * Scores the synthetic fixture into aggregate counts. PURE and value-free: company
 * refs live only in a local Map that is discarded on return, and no ref, label, or
 * fixture value is ever written into the returned counts.
 *
 * The company index is built over the bounded SCAN window (the deeper probe, mirroring
 * the BR-SOURCE-10H coverage strategy); `company_rows_sampled` separately reports the
 * shallower bounded sample so both bounds stay visible in the report.
 */
function scoreSyntheticJoin(
  fixture: BrazilReceitaFullJoinSyntheticFixture,
  limits: ResolvedLimits,
): SyntheticJoinOutcome {
  const aggregate = zeroCounts(AGGREGATE_COUNT_KEYS);
  const eligibility = zeroCounts(ELIGIBILITY_COUNT_KEYS);
  const join = zeroCounts(JOIN_COUNT_KEYS);

  const companyIndex = new Map<string, CompanyContextKind>();
  const scanWindow = fixture.companies.slice(0, limits.maxCompanyScanRows);
  for (const row of scanWindow) {
    aggregate.company_rows_scanned += 1;
    eligibility[row.eligibility] += 1;
    const kind = contextKindOf(row.eligibility);
    if (row.companyRef.trim() === '') {
      aggregate.company_rows_excluded += 1;
      continue;
    }
    if (!companyIndex.has(row.companyRef)) companyIndex.set(row.companyRef, kind);
    if (kind === 'usable_context') aggregate.company_rows_indexed += 1;
    else aggregate.company_rows_excluded += 1;
  }
  aggregate.company_rows_sampled = Math.min(fixture.companies.length, limits.maxCompanyRows);

  const establishmentWindow = fixture.establishments.slice(0, limits.maxEstablishmentRows);
  const refsHeld = new Set<string>();
  for (const row of establishmentWindow) {
    aggregate.establishment_rows_scanned += 1;

    if (row.privacySignal) {
      join.excluded_by_establishment_privacy_signal += 1;
      continue;
    }
    const ref = row.companyRef?.trim() ?? '';
    if (ref === '') {
      join.pending_full_join_context += 1;
      continue;
    }
    refsHeld.add(ref);
    if (companyIndex.size === 0) {
      join.pending_full_join_context += 1;
      continue;
    }
    const context = companyIndex.get(ref);
    if (context === undefined) {
      join.missing_company_context += 1;
      continue;
    }
    if (context === 'usable_context') join.joined_with_company_context += 1;
    else join.excluded_by_company_context += 1;
  }
  aggregate.establishment_refs_held_in_memory = refsHeld.size;

  return {
    aggregate,
    eligibility,
    join,
    coverageScanLimitReached: fixture.companies.length > limits.maxCompanyScanRows,
  };
}

// ─── Report assembly ──────────────────────────────────────────────────────────

/**
 * The run's declared provenance, carried through every exit path so a refused report
 * says the same thing about itself as a successful one.
 */
interface RunProvenance {
  readonly runMode: BrazilReceitaFullJoinRunMode;
  readonly manifestTrust: BrazilReceitaFullJoinManifestTrust;
  readonly optionBCarveoutAuthorized: boolean;
  readonly realManifestMetadataOnlyOptionBAuthorized: boolean;
  readonly realManifestMetadataOnlyExecutionAuthorized: boolean;
}

interface ReportDraft {
  readonly ok: boolean;
  readonly provenance: RunProvenance;
  readonly aggregate: Record<string, number>;
  readonly eligibility: Record<string, number>;
  readonly join: Record<string, number>;
  readonly guardrail: Record<string, number>;
  readonly manifestMetadata?: BrazilReceitaFullJoinManifestMetadataReport | null;
  readonly cleanup: BrazilReceitaFullJoinCleanupReport;
  readonly errors: readonly BrazilReceitaFullJoinReportError[];
}

function assembleReport(draft: ReportDraft): BrazilReceitaFullJoinDryRunReport {
  return {
    ok: draft.ok,
    mode: BRAZIL_RECEITA_FULL_JOIN_DRY_RUN_MODE,
    run_mode: draft.provenance.runMode,
    manifest_trust: draft.provenance.manifestTrust,
    option_b_carveout_authorized: draft.provenance.optionBCarveoutAuthorized,
    real_manifest_metadata_only_option_b_authorized:
      draft.provenance.realManifestMetadataOnlyOptionBAuthorized,
    real_manifest_metadata_only_execution_authorized:
      draft.provenance.realManifestMetadataOnlyExecutionAuthorized,
    source_key: BR_RECEITA_CNPJ_MANIFEST_SOURCE_KEY,
    country_code: BR_RECEITA_CNPJ_MANIFEST_COUNTRY_CODE,
    source_period: null,
    decision_status: DECISION_STATUS_ALL_NOT_APPROVED,
    run_scope: RUN_SCOPE_ALL_FALSE,
    safety: SAFETY_ALL_FALSE,
    aggregate_counts: draft.aggregate,
    eligibility_counts: draft.eligibility,
    join_counts: draft.join,
    guardrail_counts: draft.guardrail,
    manifest_metadata: draft.manifestMetadata ?? null,
    cleanup: draft.cleanup,
    errors: draft.errors,
  };
}

/**
 * Builds the fail-closed report for an aborted run: every count zero, cleanup marked
 * required, and the sanitized error recorded. No partial metric survives a failure.
 */
function failClosedReport(
  provenance: RunProvenance,
  errors: readonly BrazilReceitaFullJoinReportError[],
  guardViolations: number,
  sanitizerFindings: number,
  forbiddenFamilyFindings = 0,
  manifestMetadata: BrazilReceitaFullJoinManifestMetadataReport | null = null,
): BrazilReceitaFullJoinDryRunReport {
  const guardrail = zeroCounts(GUARDRAIL_COUNT_KEYS);
  guardrail.no_write_guard_violations = guardViolations;
  guardrail.forbidden_output_findings = sanitizerFindings;
  guardrail.local_manifest_forbidden_family_findings = forbiddenFamilyFindings;

  return assembleReport({
    ok: false,
    provenance,
    aggregate: zeroCounts(AGGREGATE_COUNT_KEYS),
    eligibility: zeroCounts(ELIGIBILITY_COUNT_KEYS),
    join: zeroCounts(JOIN_COUNT_KEYS),
    guardrail,
    // A metadata-only refusal still reports the AGGREGATE metadata that explains it: a
    // forbidden family is reported as a count, not silently filtered out. No row count,
    // eligibility figure, or join figure survives a failure.
    manifestMetadata,
    cleanup: planBrazilReceitaFullJoinCleanup({
      sanitizerFailed: sanitizerFindings > 0,
      guardFailed: guardViolations > 0,
      errorCount: errors.length,
    }),
    errors,
  });
}

// ─── Fixture validation ───────────────────────────────────────────────────────

function isValidFixture(fixture: BrazilReceitaFullJoinSyntheticFixture): boolean {
  if (!Array.isArray(fixture.companies) || !Array.isArray(fixture.establishments)) return false;
  for (const row of fixture.companies) {
    if (typeof row?.companyRef !== 'string') return false;
    if (!ELIGIBILITY_COUNT_KEYS.includes(row.eligibility)) return false;
  }
  for (const row of fixture.establishments) {
    if (row?.companyRef !== null && typeof row?.companyRef !== 'string') return false;
    if (typeof row?.privacySignal !== 'boolean') return false;
  }
  return true;
}

function exceedsSyntheticCeiling(fixture: BrazilReceitaFullJoinSyntheticFixture): boolean {
  return (
    fixture.companies.length > BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS ||
    fixture.establishments.length > BRAZIL_RECEITA_FULL_JOIN_MAX_SYNTHETIC_ROWS
  );
}

// ─── Guard config projection ──────────────────────────────────────────────────

/**
 * Projects the input into the object handed to the no-write guard: every declared
 * field EXCEPT the synthetic fixture (structural test data, not config), with the two
 * optional escalation flags defaulted to `false` so an omission is still a declaration.
 *
 * Passing the whole input matters: the guard's second job is detecting dangerous
 * indicators, and it can only find one if it is allowed to see it.
 */
function buildGuardConfig(input: BrazilReceitaFullJoinDryRunInput): Record<string, unknown> {
  const guardConfig: Record<string, unknown> = { providerCalls: false, importExecuted: false };
  for (const [key, value] of Object.entries(input)) {
    // Structural test data and the injected reader PORTS are not configuration.
    if (
      key === 'syntheticFixture' ||
      key === 'localManifestReader' ||
      key === 'realManifestMetadataReader'
    ) {
      continue;
    }
    if (value === undefined) continue;
    guardConfig[key] = value;
  }
  return guardConfig;
}

// ─── Option B gate (BR-SOURCE-11C) ────────────────────────────────────────────

/** The bounded caps an Option B run must state explicitly. */
interface OptionBCaps {
  readonly maxCompanyRows: number;
  readonly maxEstablishmentRows: number;
  readonly maxCompanyScanRows: number;
  readonly maxBytesPerFile: number;
}

type OptionBGateOutcome =
  | { readonly ok: true; readonly caps: OptionBCaps }
  | { readonly ok: false; readonly code: BrazilReceitaFullJoinErrorCode };

/** True for a stated, non-negative, integral cap at or below its Option B ceiling. */
function isCapWithin(value: number | undefined, ceiling: number): boolean {
  return value !== undefined && Number.isInteger(value) && value >= 0 && value <= ceiling;
}

/**
 * Validates the FULL Option B contract before a single byte is read. Every condition
 * is independent and fail-closed, and the order is deliberate: manifest TRUST is
 * checked before the carve-out authorization, so a real manifest is refused as "real
 * manifest execution not authorized" whatever else the caller declared.
 */
function evaluateOptionBGate(
  input: BrazilReceitaFullJoinDryRunInput,
  manifestTrust: BrazilReceitaFullJoinManifestTrust,
): OptionBGateOutcome {
  if (input.allowLocalManifest !== true) {
    return { ok: false, code: 'allow_local_manifest_required' };
  }
  if (manifestTrust !== BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST) {
    return { ok: false, code: 'local_manifest_execution_not_authorized' };
  }
  if (input.optionBCarveoutAuthorized !== true) {
    return { ok: false, code: 'option_b_carveout_not_authorized' };
  }
  if (input.strict !== true) {
    return { ok: false, code: 'strict_mode_required' };
  }
  if (input.productionWrites !== undefined && input.productionWrites !== false) {
    return { ok: false, code: 'production_writes_requested' };
  }
  // GATE-5 is not approved, and an Option B run must SAY so rather than omit it.
  if (input.outputSanitizationVersion !== BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION) {
    return { ok: false, code: 'output_sanitization_version_not_approved' };
  }

  const stated = [
    input.maxCompanyRows,
    input.maxEstablishmentRows,
    input.maxCompanyScanRows,
    input.maxBytesPerFile,
  ];
  if (stated.some((cap) => cap === undefined)) {
    return { ok: false, code: 'local_manifest_caps_required' };
  }
  const withinBounds =
    isCapWithin(input.maxCompanyRows, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_ROWS) &&
    isCapWithin(
      input.maxEstablishmentRows,
      BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_ESTABLISHMENT_ROWS,
    ) &&
    isCapWithin(input.maxCompanyScanRows, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_COMPANY_SCAN_ROWS) &&
    isCapWithin(input.maxBytesPerFile, BRAZIL_RECEITA_FULL_JOIN_OPTION_B_MAX_BYTES_PER_FILE);
  if (!withinBounds) {
    return { ok: false, code: 'local_manifest_cap_exceeded' };
  }
  if (typeof input.localManifestReader !== 'function') {
    return { ok: false, code: 'local_manifest_reader_required' };
  }

  return {
    ok: true,
    caps: {
      maxCompanyRows: input.maxCompanyRows as number,
      maxEstablishmentRows: input.maxEstablishmentRows as number,
      maxCompanyScanRows: input.maxCompanyScanRows as number,
      maxBytesPerFile: input.maxBytesPerFile as number,
    },
  };
}

interface ScanValidation {
  readonly code: BrazilReceitaFullJoinErrorCode;
  readonly forbiddenFamilyFindings: number;
}

/**
 * Re-validates what the reader claimed. The reader sits at a trust boundary, so its
 * declared trust level, layout mode, and family names are checked against the runner's
 * own allowlists — a reader cannot talk its way past the carve-out. Returns `null` when
 * the scan is acceptable.
 */
function validateLocalManifestScan(scan: unknown): ScanValidation | null {
  if (typeof scan !== 'object' || scan === null) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  const candidate = scan as Partial<BrazilReceitaFullJoinLocalManifestScan>;

  if (candidate.manifestTrust !== BRAZIL_RECEITA_FULL_JOIN_SYNTHETIC_TEMP_MANIFEST_TRUST) {
    return { code: 'local_manifest_execution_not_authorized', forbiddenFamilyFindings: 0 };
  }
  if (candidate.layoutMode !== BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_LAYOUT_MODE) {
    return { code: 'local_manifest_layout_mode_not_authorized', forbiddenFamilyFindings: 0 };
  }
  if (!Array.isArray(candidate.familiesScanned)) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  const forbidden = candidate.familiesScanned.filter(
    (family) =>
      typeof family !== 'string' ||
      !BRAZIL_RECEITA_FULL_JOIN_LOCAL_MANIFEST_ALLOWED_FAMILIES.includes(family),
  );
  if (forbidden.length > 0) {
    return {
      code: 'local_manifest_forbidden_file_family',
      forbiddenFamilyFindings: forbidden.length,
    };
  }
  if (candidate.bytesCapExceeded === true) {
    return { code: 'local_manifest_bytes_cap_exceeded', forbiddenFamilyFindings: 0 };
  }
  if (!Number.isInteger(candidate.filesScanned) || (candidate.filesScanned as number) < 0) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  if (typeof candidate.fixture !== 'object' || candidate.fixture === null) {
    return { code: 'local_manifest_scan_invalid', forbiddenFamilyFindings: 0 };
  }
  return null;
}

// ─── Metadata-only gate (BR-SOURCE-11D-META-IMPL) ─────────────────────────────

/** The two bounded caps a metadata-only run must state explicitly. */
interface MetadataOnlyCaps {
  readonly maxManifestBytes: number;
  readonly maxDeclaredFiles: number;
}

type MetadataOnlyGateOutcome =
  | { readonly ok: true; readonly caps: MetadataOnlyCaps }
  | { readonly ok: false; readonly code: BrazilReceitaFullJoinErrorCode };

/**
 * Validates the FULL metadata-only contract before a single byte is read. Every
 * condition is independent and fail-closed.
 *
 * Note what this gate does NOT accept: `optionBCarveoutAuthorized`. The synthetic
 * temp-manifest phrase is a different, already-spent authorization for a different
 * carve-out, and it buys nothing here — a caller holding only that flag is refused with
 * `real_manifest_metadata_only_not_authorized`.
 */
function evaluateMetadataOnlyGate(
  input: BrazilReceitaFullJoinDryRunInput,
): MetadataOnlyGateOutcome {
  if (input.allowLocalManifest !== true) {
    return { ok: false, code: 'allow_local_manifest_required' };
  }
  if (input.realManifestMetadataOnlyOptionBAuthorized !== true) {
    return { ok: false, code: 'real_manifest_metadata_only_not_authorized' };
  }
  if (input.strict !== true) {
    return { ok: false, code: 'strict_mode_required' };
  }
  if (input.productionWrites !== undefined && input.productionWrites !== false) {
    return { ok: false, code: 'production_writes_requested' };
  }
  // GATE-5 is not approved, and a metadata-only run must SAY so rather than omit it.
  if (input.outputSanitizationVersion !== BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION) {
    return { ok: false, code: 'output_sanitization_version_not_approved' };
  }
  if (input.maxManifestBytes === undefined || input.maxDeclaredFiles === undefined) {
    return { ok: false, code: 'real_manifest_metadata_caps_required' };
  }
  const withinBounds =
    isCapWithin(input.maxManifestBytes, BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_MAX_MANIFEST_BYTES) &&
    isCapWithin(input.maxDeclaredFiles, BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_MAX_DECLARED_FILES);
  if (!withinBounds) {
    return { ok: false, code: 'real_manifest_metadata_cap_exceeded' };
  }
  if (typeof input.realManifestMetadataReader !== 'function') {
    return { ok: false, code: 'real_manifest_metadata_reader_required' };
  }
  return {
    ok: true,
    caps: {
      maxManifestBytes: input.maxManifestBytes,
      maxDeclaredFiles: input.maxDeclaredFiles,
    },
  };
}

/** True for a finite, non-negative integer count arriving from the trust boundary. */
function isCount(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value >= 0;
}

/**
 * Projects a validated metadata scan into the report block. Only counts, booleans, and
 * class labels cross over; the family-count keys are re-filtered against the runner's
 * own allowlist so a reader cannot introduce a key the report never agreed to carry.
 */
function projectManifestMetadata(
  scan: BrazilReceitaFullJoinRealManifestMetadataScan,
): BrazilReceitaFullJoinManifestMetadataReport {
  const counts: Record<string, number> = {};
  for (const key of BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_ALLOWED_FAMILY_KEYS) counts[key] = 0;
  for (const [key, value] of Object.entries(scan.declaredFamilyCounts ?? {})) {
    if (BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_ALLOWED_FAMILY_KEYS.includes(key) && isCount(value)) {
      counts[key] = value;
    }
  }
  return {
    schema_version_present: scan.schemaVersionPresent === true,
    source_period_present: scan.sourcePeriodPresent === true,
    layout_mode: scan.layoutMode,
    declared_file_count: scan.declaredFileCount,
    required_family_count: scan.requiredFamilyCount,
    missing_required_family_count: scan.missingRequiredFamilyCount,
    forbidden_family_count: scan.forbiddenFamilyCount,
    declared_family_counts: counts,
    required_families_present: scan.missingRequiredFamilyCount === 0,
    forbidden_families_present: scan.forbiddenFamilyCount > 0,
    manifest_bytes_read_bucket: scan.manifestBytesReadBucket,
    operator_prepared_manifest_authorized: scan.operatorPreparedManifestAuthorized === true,
    referenced_data_files_opened: false,
    referenced_data_files_statted: false,
    raw_manifest_printed: false,
    absolute_paths_printed: false,
  };
}

/** Maps a reader-reported content refusal onto the runner's own error vocabulary. */
const METADATA_REFUSAL_CODES: Readonly<Record<string, BrazilReceitaFullJoinErrorCode>> = {
  manifest_forbidden_family_detected: 'real_manifest_metadata_forbidden_family_detected',
  manifest_missing_required_family: 'real_manifest_metadata_missing_required_family',
  manifest_layout_unsupported: 'real_manifest_metadata_layout_mode_not_authorized',
  manifest_metadata_cap_exceeded: 'real_manifest_metadata_cap_exceeded',
};

/**
 * Re-validates what the metadata reader claimed, structurally FIRST and by content
 * second. The reader sits at a trust boundary, so its declared trust level, its byte
 * bucket, its counts, and above all its `referenced*` assertions are checked against the
 * runner's own expectations — a reader cannot talk its way past the carve-out, and a
 * reader that admits (or is coerced into claiming) it touched a referenced file is
 * refused outright. Returns `null` when the scan is acceptable.
 */
function validateMetadataScan(
  scan: unknown,
  input: BrazilReceitaFullJoinDryRunInput,
): BrazilReceitaFullJoinErrorCode | null {
  if (typeof scan !== 'object' || scan === null) return 'real_manifest_metadata_scan_invalid';
  const candidate = scan as Partial<BrazilReceitaFullJoinRealManifestMetadataScan>;

  if (candidate.manifestTrust !== BRAZIL_RECEITA_FULL_JOIN_REAL_MANIFEST_METADATA_ONLY_TRUST) {
    return 'local_manifest_execution_not_authorized';
  }
  // BR-SOURCE-11E cross-check. The reader owns the path, so only the reader can report
  // that it named an OPERATOR-PREPARED manifest. If it did, the RUN must have declared the
  // execution authorization independently — two declarations that have to agree, so a
  // reader cannot quietly spend an authorization the caller never claimed. The reverse
  // (declared but unspent) is not a breach: it is a wider declaration than the run needed.
  if (
    candidate.operatorPreparedManifestAuthorized === true &&
    input.realManifestMetadataOnlyExecutionAuthorized !== true
  ) {
    return 'real_manifest_metadata_execution_not_authorized';
  }
  // The load-bearing invariant of the whole carve-out: exactly one path is resolved, and
  // no referenced data file is opened or stat-ed.
  if (candidate.referencedDataFilesOpened !== false || candidate.referencedDataFilesStatted !== false) {
    return 'real_manifest_metadata_referenced_file_access_detected';
  }
  if (
    typeof candidate.manifestBytesReadBucket !== 'string' ||
    !BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_BYTES_BUCKETS.includes(candidate.manifestBytesReadBucket)
  ) {
    return 'real_manifest_metadata_scan_invalid';
  }
  if (
    !isCount(candidate.declaredFileCount) ||
    !isCount(candidate.requiredFamilyCount) ||
    !isCount(candidate.missingRequiredFamilyCount) ||
    !isCount(candidate.forbiddenFamilyCount)
  ) {
    return 'real_manifest_metadata_scan_invalid';
  }
  if (typeof candidate.declaredFamilyCounts !== 'object' || candidate.declaredFamilyCounts === null) {
    return 'real_manifest_metadata_scan_invalid';
  }
  if (typeof candidate.layoutMode !== 'string') return 'real_manifest_metadata_scan_invalid';

  // A refusal the reader reported rather than threw. Mapped, never passed through raw.
  if (candidate.refusalCode !== null && candidate.refusalCode !== undefined) {
    return (
      METADATA_REFUSAL_CODES[candidate.refusalCode] ?? 'real_manifest_metadata_scan_invalid'
    );
  }
  // Belt and braces: the runner enforces the layout authority itself, so a reader that
  // forgot to report the refusal is still refused.
  if (candidate.layoutMode !== BRAZIL_RECEITA_FULL_JOIN_METADATA_ONLY_LAYOUT_MODE) {
    return 'real_manifest_metadata_layout_mode_not_authorized';
  }
  if (candidate.forbiddenFamilyCount > 0) {
    return 'real_manifest_metadata_forbidden_family_detected';
  }
  if (candidate.missingRequiredFamilyCount > 0) {
    return 'real_manifest_metadata_missing_required_family';
  }
  return null;
}

// ─── Metadata-only run (BR-SOURCE-11D-META-IMPL) ──────────────────────────────

/**
 * Runs the real-manifest METADATA-ONLY carve-out: gate, ONE injected read of the
 * manifest document, re-validation of what the reader claimed, and an aggregate report.
 *
 * No row is read, so every row/eligibility/join count stays zero by construction — this
 * path never reaches the fixture scorer at all. The only thing that can be learned is
 * whether the operator's manifest is well-formed, and that is not evidence about the
 * dataset, its coverage, its join rates, its eligibility, GATE-1, or GATE-2.
 */
function runRealManifestMetadataOnly(
  input: BrazilReceitaFullJoinDryRunInput,
  provenance: RunProvenance,
): BrazilReceitaFullJoinDryRunReport {
  const gate = evaluateMetadataOnlyGate(input);
  if (!gate.ok) {
    return failClosedReport(
      provenance,
      [{ error_code: gate.code, stage: 'real_manifest_metadata_gate' }],
      0,
      0,
    );
  }

  let scan: BrazilReceitaFullJoinRealManifestMetadataScan;
  try {
    // The ONE read of the run. The reader owns the single path it validated; the runner
    // passes the caps in and never learns a path.
    scan = input.realManifestMetadataReader!({
      maxManifestBytes: gate.caps.maxManifestBytes,
      maxDeclaredFiles: gate.caps.maxDeclaredFiles,
    });
  } catch {
    // The underlying error is DISCARDED: a reader failure could carry a path or a
    // fragment of the document in its message, so only the fixed stage/code survive.
    return failClosedReport(
      provenance,
      [{ error_code: 'real_manifest_metadata_read_failed', stage: 'real_manifest_metadata_read' }],
      0,
      0,
    );
  }

  const refusal = validateMetadataScan(scan, input);
  // A structurally-invalid or UNAUTHORIZED scan carries no reportable metadata; a CONTENT
  // refusal does, and reporting it as an aggregate is exactly what the carve-out permits.
  const metadata =
    refusal === 'real_manifest_metadata_scan_invalid' ||
    refusal === 'local_manifest_execution_not_authorized' ||
    refusal === 'real_manifest_metadata_referenced_file_access_detected' ||
    refusal === 'real_manifest_metadata_execution_not_authorized'
      ? null
      : projectManifestMetadata(scan);

  if (refusal !== null) {
    return failClosedReport(
      provenance,
      [{ error_code: refusal, stage: 'real_manifest_metadata_read' }],
      0,
      0,
      metadata?.forbidden_family_count ?? 0,
      metadata,
    );
  }

  const candidate = assembleReport({
    ok: true,
    provenance,
    aggregate: zeroCounts(AGGREGATE_COUNT_KEYS),
    eligibility: zeroCounts(ELIGIBILITY_COUNT_KEYS),
    join: zeroCounts(JOIN_COUNT_KEYS),
    guardrail: zeroCounts(GUARDRAIL_COUNT_KEYS),
    manifestMetadata: metadata,
    cleanup: planBrazilReceitaFullJoinCleanup({
      sanitizerFailed: false,
      guardFailed: false,
      errorCount: 0,
    }),
    errors: [],
  });

  // Output sanitization. A leak discards the metadata block too — the report never ships
  // partially-sanitized content, and the offending value is never surfaced.
  const sanitized = sanitizeBrazilReceitaFullJoinReport(candidate);
  if (!sanitized.ok) {
    return failClosedReport(
      provenance,
      [{ error_code: BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE, stage: 'output_sanitization' }],
      0,
      sanitized.findings.length,
    );
  }
  return candidate;
}

// ─── Public entry point ───────────────────────────────────────────────────────

/**
 * Runs the full join dry-run scaffold and returns an AGGREGATE, SANITIZED report.
 * Never throws for a policy violation — every refusal comes back as `ok: false` plus a
 * value-free error code, so a caller can print the report safely.
 *
 * Order of operations is deliberate and fail-closed at every step:
 *   1. no-write/no-runtime guard (nothing else runs if the contract is not declared);
 *   2. output-sanitization version check (GATE-5 is not approved);
 *   3. run-mode resolution, then dispatch by declared manifest TRUST;
 *   3b. `real_manifest_metadata_only`: the metadata-only gate, then ONE injected read of
 *       the manifest DOCUMENT. Reads no row, so it returns before the fixture path.
 *   4a. `synthetic_temp_manifest_only`: the full Option B gate, then ONE injected read
 *       whose result is re-validated against the runner's own allowlists;
 *   4b. `synthetic_fixture_only`: bounded-limit validation against the generic caps;
 *   5. fixture validation and scoring (identical for both fixture-bearing modes);
 *   6. output sanitization of the assembled report — a leak discards the metrics.
 */
export function runBrazilReceitaFullJoinDryRun(
  input: BrazilReceitaFullJoinDryRunInput,
): BrazilReceitaFullJoinDryRunReport {
  const requestedMode = input.mode ?? BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE;
  const knownMode = BRAZIL_RECEITA_FULL_JOIN_RUN_MODES.includes(requestedMode);
  // An unknown mode is still reported against the SAFE default, never echoed back.
  const reportedMode = knownMode ? requestedMode : BRAZIL_RECEITA_FULL_JOIN_DEFAULT_RUN_MODE;

  const manifestTrust: BrazilReceitaFullJoinManifestTrust =
    reportedMode === 'local_manifest_dry_run'
      ? (input.manifestTrust ?? BRAZIL_RECEITA_FULL_JOIN_DEFAULT_MANIFEST_TRUST)
      : 'not_applicable';
  const provenance: RunProvenance = {
    runMode: reportedMode,
    manifestTrust,
    optionBCarveoutAuthorized: input.optionBCarveoutAuthorized === true,
    realManifestMetadataOnlyOptionBAuthorized:
      input.realManifestMetadataOnlyOptionBAuthorized === true,
    realManifestMetadataOnlyExecutionAuthorized:
      input.realManifestMetadataOnlyExecutionAuthorized === true,
  };

  // 1) No-write / no-runtime guard. The WHOLE input is handed to the guard (minus the
  //    synthetic fixture and the reader port, which are structural rather than config)
  //    so that a dangerous indicator smuggled alongside the declared contract — a
  //    service-role key, a Supabase URL, a runtime endpoint — is detected, not ignored.
  const guard = assertBrazilReceitaFullJoinNoWrite(buildGuardConfig(input));
  if (!guard.ok) {
    return failClosedReport(
      provenance,
      [{ error_code: BRAZIL_RECEITA_FULL_JOIN_NO_WRITE_GUARD_ERROR_CODE, stage: 'no_write_guard' }],
      guard.violations.length,
      0,
    );
  }

  // 2) Output-sanitization version: GATE-5 is not approved, so nothing else is valid.
  if (
    input.outputSanitizationVersion !== undefined &&
    input.outputSanitizationVersion !== BRAZIL_RECEITA_FULL_JOIN_OUTPUT_SANITIZATION_VERSION
  ) {
    return failClosedReport(
      provenance,
      [{ error_code: 'output_sanitization_version_not_approved', stage: 'mode_resolution' }],
      0,
      0,
    );
  }

  // 3) Run mode.
  if (!knownMode) {
    return failClosedReport(
      provenance,
      [{ error_code: 'invalid_run_mode', stage: 'mode_resolution' }],
      0,
      0,
    );
  }

  // 3b) The two local-manifest carve-outs are dispatched by declared TRUST, so neither
  //     authorization can satisfy the other's gate. A metadata-only run reads no row and
  //     therefore never reaches the fixture path below.
  if (
    requestedMode === 'local_manifest_dry_run' &&
    manifestTrust === BRAZIL_RECEITA_FULL_JOIN_REAL_MANIFEST_METADATA_ONLY_TRUST
  ) {
    return runRealManifestMetadataOnly(input, provenance);
  }

  let fixture: BrazilReceitaFullJoinSyntheticFixture;
  let limits: ResolvedLimits;
  const localManifest = { filesScanned: 0, familiesScanned: 0, bytesCapApplied: false };

  if (requestedMode === 'local_manifest_dry_run') {
    // 4a) Option B: the narrow synthetic-temp-manifest carve-out.
    const gate = evaluateOptionBGate(input, manifestTrust);
    if (!gate.ok) {
      return failClosedReport(
        provenance,
        [{ error_code: gate.code, stage: 'option_b_gate' }],
        0,
        0,
      );
    }

    let scan: BrazilReceitaFullJoinLocalManifestScan;
    try {
      // The ONE read of the run. The reader owns the temp workspace it created; the
      // runner passes the caps in and never learns a path.
      scan = input.localManifestReader!({
        maxBytesPerFile: gate.caps.maxBytesPerFile,
        maxCompanyRows: gate.caps.maxCompanyRows,
        maxEstablishmentRows: gate.caps.maxEstablishmentRows,
        maxCompanyScanRows: gate.caps.maxCompanyScanRows,
      });
    } catch {
      // The underlying error is DISCARDED: a reader failure could carry a path or a
      // cell in its message, so only the fixed stage/code survive.
      return failClosedReport(
        provenance,
        [{ error_code: 'local_manifest_read_failed', stage: 'local_manifest_read' }],
        0,
        0,
      );
    }

    const scanFailure = validateLocalManifestScan(scan);
    if (scanFailure !== null) {
      return failClosedReport(
        provenance,
        [{ error_code: scanFailure.code, stage: 'local_manifest_read' }],
        0,
        0,
        scanFailure.forbiddenFamilyFindings,
      );
    }

    fixture = scan.fixture;
    limits = {
      maxCompanyRows: gate.caps.maxCompanyRows,
      maxEstablishmentRows: gate.caps.maxEstablishmentRows,
      maxCompanyScanRows: gate.caps.maxCompanyScanRows,
    };
    localManifest.filesScanned = scan.filesScanned;
    localManifest.familiesScanned = scan.familiesScanned.length;
    localManifest.bytesCapApplied = scan.bytesCapApplied === true;
  } else {
    // 4b) Synthetic fixture mode: the generic bounded caps.
    const resolved = resolveLimits(input);
    if (!resolved.ok) {
      return failClosedReport(
        provenance,
        [{ error_code: resolved.failure.code, stage: 'limit_validation' }],
        0,
        0,
      );
    }
    limits = resolved.value;
    fixture = input.syntheticFixture ?? defaultBrazilReceitaFullJoinSyntheticFixture();
  }

  // 5) Fixture validation and scoring — identical for both modes, so a synthetic temp
  //    read cannot take a shortcut around the structural checks.
  if (!isValidFixture(fixture)) {
    return failClosedReport(
      provenance,
      [{ error_code: 'synthetic_fixture_invalid', stage: 'fixture_validation' }],
      0,
      0,
    );
  }
  if (exceedsSyntheticCeiling(fixture)) {
    return failClosedReport(
      provenance,
      [{ error_code: 'full_dataset_processing_not_allowed', stage: 'fixture_validation' }],
      0,
      0,
    );
  }

  const outcome = scoreSyntheticJoin(fixture, limits);
  const aggregate = { ...outcome.aggregate };
  aggregate.local_manifest_files_scanned = localManifest.filesScanned;
  aggregate.local_manifest_families_scanned = localManifest.familiesScanned;

  const guardrail = zeroCounts(GUARDRAIL_COUNT_KEYS);
  guardrail.company_sample_cap_applied = fixture.companies.length > limits.maxCompanyRows ? 1 : 0;
  guardrail.company_scan_cap_applied = outcome.coverageScanLimitReached ? 1 : 0;
  guardrail.establishment_sample_cap_applied =
    fixture.establishments.length > limits.maxEstablishmentRows ? 1 : 0;
  guardrail.coverage_scan_limit_reached = outcome.coverageScanLimitReached ? 1 : 0;
  guardrail.local_manifest_bytes_cap_applied = localManifest.bytesCapApplied ? 1 : 0;

  const candidate = assembleReport({
    ok: true,
    provenance,
    aggregate,
    eligibility: outcome.eligibility,
    join: outcome.join,
    guardrail,
    cleanup: planBrazilReceitaFullJoinCleanup({
      sanitizerFailed: false,
      guardFailed: false,
      errorCount: 0,
    }),
    errors: [],
  });

  // 6) Output sanitization. A leak discards every metric — the report never ships
  //    partially-sanitized data, and the offending value is never surfaced.
  const sanitized = sanitizeBrazilReceitaFullJoinReport(candidate);
  if (!sanitized.ok) {
    return failClosedReport(
      provenance,
      [
        {
          error_code: BRAZIL_RECEITA_FULL_JOIN_SANITIZER_ERROR_CODE,
          stage: 'output_sanitization',
        },
      ],
      0,
      sanitized.findings.length,
    );
  }

  return candidate;
}
