/**
 * pe-sunat-ciiu4-activity-catalog.ts — código CIIU Rev. 4 (clase, 4 dígitos) de
 * cada actividad económica que publica el Padrón RUC de SUNAT en datos abiertos.
 *
 * SOURCES-PE-FREE-DISCOVERY-1. Puro: datos, sin I/O.
 *
 * ── De dónde sale ───────────────────────────────────────────────────────────
 *
 * El Padrón RUC de datos abiertos (`PadronRUC_AAAAMM.zip`, datosabiertos.gob.pe)
 * trae la actividad principal CIIU Rev. 4 sólo como TEXTO, sin el código. Ese
 * texto es el título oficial de la clase CIIU Rev. 4 en mayúsculas, sin tildes ni
 * signos (y «n.c.p.» escrito «NO CLASIFICADOS PREVIAMENTE»). Se cruzó con la
 * estructura oficial en español de Naciones Unidas (ISIC_Rev_4_Spanish_structure,
 * 419 clases): 392 textos coinciden exactamente y los 23 restantes difieren sólo
 * en «n.c.p.» o en erratas del padrón («ALAMBICAS», «ACTIDADES»), revisados uno a
 * uno el 06-10-2026. Son los 415 textos distintos de las 867.475 sociedades
 * activas y habidas del corte 2026-09. «NO DISPONIBLE» no tiene código.
 *
 * Un texto que no esté aquí no tiene código: la empresa nunca entra en la capa
 * gratuita por industria (no se adivina).
 */

const RAW = `
0111|CULTIVO DE CEREALES (EXCEPTO ARROZ) LEGUMBRES Y SEMILLAS OLEAGINOSAS
0112|CULTIVO DE ARROZ
0113|CULTIVO DE HORTALIZAS Y MELONES RAICES Y TUBERCULOS
0114|CULTIVO DE CAÑA DE AZUCAR
0115|CULTIVO DE TABACO
0116|CULTIVO DE PLANTAS DE FIBRA
0119|CULTIVO DE OTRAS PLANTAS NO PERENNES
0121|CULTIVO DE UVA
0122|CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES
0123|CULTIVO DE CITRICOS
0124|CULTIVO DE FRUTAS DE PEPITA Y DE HUESO
0125|CULTIVO DE OTROS FRUTOS Y NUECES DE ARBOLES Y ARBUSTOS
0126|CULTIVO DE FRUTOS OLEAGINOSOS
0127|CULTIVO DE PLANTAS CON LAS QUE SE PREPARAN BEBIDAS
0128|CULTIVO DE ESPECIAS Y DE PLANTAS AROMATICAS MEDICINALES Y FARMACEUTICAS
0129|CULTIVO DE OTRAS PLANTAS PERENNES
0130|PROPAGACION DE PLANTAS
0141|CRIA DE GANADO BOVINO Y BUFALOS
0142|CRIA DE CABALLOS Y OTROS EQUINOS
0143|CRIA DE CAMELLOS Y OTROS CAMELIDOS
0144|CRIA DE OVEJAS Y CABRAS
0145|CRIA DE CERDOS
0146|CRIA DE AVES DE CORRAL
0149|CRIA DE OTROS ANIMALES
0150|CULTIVO DE PRODUCTOS AGRICOLAS EN COMBINACION CON LA CRIA DE ANIMALES (EXPLOTACION MIXTA)
0161|ACTIVIDADES DE APOYO A LA AGRICULTURA
0162|ACTIVIDADES DE APOYO A LA GANADERIA
0163|ACTIVIDADES POSCOSECHA
0164|TRATAMIENTO DE SEMILLAS PARA PROPAGACION
0170|CAZA ORDINARIA Y MEDIANTE TRAMPAS Y ACTIVIDADES DE SERVICIOS CONEXAS
0210|SILVICULTURA Y OTRAS ACTIVIDADES FORESTALES
0220|EXTRACCION DE MADERA
0230|RECOLECCION DE PRODUCTOS FORESTALES DISTINTOS DE LA MADERA
0240|SERVICIOS DE APOYO A LA SILVICULTURA
0311|PESCA MARITIMA
0312|PESCA DE AGUA DULCE
0321|ACUICULTURA MARINA
0322|ACUICULTURA DE AGUA DULCE
0510|EXTRACCION DE CARBON DE PIEDRA
0610|EXTRACCION DE PETROLEO CRUDO
0620|EXTRACCION DE GAS NATURAL
0710|EXTRACCION DE MINERALES DE HIERRO
0721|EXTRACCION DE MINERALES DE URANIO Y TORIO
0729|EXTRACCION DE OTROS MINERALES METALIFEROS NO FERROSOS
0810|EXTRACCION DE PIEDRA ARENA Y ARCILLA
0891|EXTRACCION DE MINERALES PARA LA FABRICACION DE ABONOS Y PRODUCTOS QUIMICOS
0893|EXTRACCION DE SAL
0899|EXPLOTACION DE OTRAS MINAS Y CANTERAS NO CLASIFICADOS PREVIAMENTE
0910|ACTIVIDADES DE APOYO PARA LA EXTRACCION DE PETROLEO Y GAS NATURAL
0990|ACTIVIDADES DE APOYO PARA OTRAS ACTIVIDADES DE EXPLOTACION DE MINAS Y CANTERAS
1010|ELABORACION Y CONSERVACION DE CARNE
1020|ELABORACION Y CONSERVACION DE PESCADO CRUSTACEOS Y MOLUSCOS
1030|ELABORACION Y CONSERVACION DE FRUTAS LEGUMBRES Y HORTALIZAS
1040|ELABORACION DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL
1050|ELABORACION DE PRODUCTOS LACTEOS
1061|ELABORACION DE PRODUCTOS DE MOLINERIA
1062|ELABORACION DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDON
1071|ELABORACION DE PRODUCTOS DE PANADERIA
1072|ELABORACION DE AZUCAR
1073|ELABORACION DE CACAO Y CHOCOLATE Y DE PRODUCTOS DE CONFITERIA
1074|ELABORACION DE MACARRONES FIDEOS ALCUZCUZ Y PRODUCTOS FARINACEOS SIMILARES
1075|ELABORACION DE COMIDAS Y PLATOS PREPARADOS
1079|ELABORACION DE OTROS PRODUCTOS ALIMENTICIOS NO CLASIFICADOS PREVIAMENTE
1080|ELABORACION DE PIENSOS PREPARADOS PARA ANIMALES
1101|DESTILACION RECTIFICACION Y MEZCLA DE BEBIDAS ALCOHOLICAS
1102|ELABORACION DE VINOS
1103|ELABORACION DE BEBIDAS MALTEADAS Y DE MALTA
1104|ELABORACION DE BEBIDAS NO ALCOHOLICAS; PRODUCCION DE AGUAS MINERALES Y OTRAS AGUAS EMBOTELLADAS
1200|ELABORACION DE PRODUCTOS DE TABACO
1311|PREPARACION E HILATURA DE FIBRAS TEXTILES
1312|TEJEDURA DE PRODUCTOS TEXTILES
1313|ACABADO DE PRODUCTOS TEXTILES
1391|FABRICACION DE TEJIDOS DE PUNTO Y GANCHILLO
1392|FABRICACION DE ARTICULOS CONFECCIONADOS DE MATERIALES TEXTILES EXCEPTO PRENDAS DE VESTIR
1393|FABRICACION DE TAPICES Y ALFOMBRAS
1394|FABRICACION DE CUERDAS CORDELES BRAMANTES Y REDES
1399|FABRICACION DE OTROS PRODUCTOS TEXTILES NO CLASIFICADOS PREVIAMENTE
1410|FABRICACION DE PRENDAS DE VESTIR EXCEPTO PRENDAS DE PIEL
1420|FABRICACION DE ARTICULOS DE PIEL
1430|FABRICACION DE ARTICULOS DE PUNTO Y GANCHILLO
1511|CURTIDO Y ADOBO DE CUEROS; ADOBO Y TEÑIDO DE PIELES
1512|FABRICACION DE MALETAS BOLSOS DE MANO Y ARTICULOS SIMILARES Y DE ARTICULOS DE TALABARTERIA Y GUARNICIONERIA
1520|FABRICACION DE CALZADO
1610|ASERRADO Y ACEPILLADURA DE MADERA
1621|FABRICACION DE HOJAS DE MADERA PARA ENCHAPADO Y TABLEROS A BASE DE MADERA
1622|FABRICACION DE PARTES Y PIEZAS DE CARPINTERIA PARA EDIFICIOS Y CONSTRUCCIONES
1623|FABRICACION DE RECIPIENTES DE MADERA
1629|FABRICACION DE OTROS PRODUCTOS DE MADERA; FABRICACION DE ARTICULOS DE CORCHO PAJA Y MATERIALES TRENZABLES
1701|FABRICACION DE PASTA DE MADERA PAPEL Y CARTON
1702|FABRICACION DE PAPEL Y CARTON ONDULADO Y DE ENVASES DE PAPEL Y CARTON
1709|FABRICACION DE OTROS ARTICULOS DE PAPEL Y CARTON
1811|IMPRESION
1812|ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA IMPRESION
1820|REPRODUCCION DE GRABACIONES
1910|FABRICACION DE PRODUCTOS DE HORNOS DE COQUE
1920|FABRICACION DE PRODUCTOS DE LA REFINACION DEL PETROLEO
2011|FABRICACION DE SUSTANCIAS QUIMICAS BASICAS
2012|FABRICACION DE ABONOS Y COMPUESTOS DE NITROGENO
2013|FABRICACION DE PLASTICOS Y CAUCHO SINTETICO EN FORMAS PRIMARIAS
2021|FABRICACION DE PLAGUICIDAS Y OTROS PRODUCTOS QUIMICOS DE USO AGROPECUARIO
2022|FABRICACION DE PINTURAS BARNICES Y PRODUCTOS DE REVESTIMIENTO SIMILARES TINTAS DE IMPRENTA Y MASILLAS
2023|FABRICACION DE JABONES Y DETERGENTES PREPARADOS PARA LIMPIAR Y PULIR PERFUMES Y PREPARADOS DE TOCADOR
2029|FABRICACION DE OTROS PRODUCTOS QUIMICOS NO CLASIFICADOS PREVIAMENTE
2030|FABRICACION DE FIBRAS ARTIFICIALES
2100|FABRICACION DE PRODUCTOS FARMACEUTICOS SUSTANCIAS QUIMICAS MEDICINALES Y PRODUCTOS BOTANICOS DE USO FARMACEUTICO
2211|FABRICACION DE CUBIERTAS Y CAMARAS DE CAUCHO; RECAUCHUTADO Y RENOVACION DE CUBIERTAS DE CAUCHO
2219|FABRICACION DE OTROS PRODUCTOS DE CAUCHO
2220|FABRICACION DE PRODUCTOS DE PLASTICO
2310|FABRICACION DE VIDRIO Y PRODUCTOS DE VIDRIO
2391|FABRICACION DE PRODUCTOS REFRACTARIOS
2392|FABRICACION DE MATERIALES DE CONSTRUCCION DE ARCILLA
2393|FABRICACION DE OTROS PRODUCTOS DE PORCELANA Y DE CERAMICA
2394|FABRICACION DE CEMENTO CAL Y YESO
2395|FABRICACION DE ARTICULOS DE HORMIGON CEMENTO Y YESO
2396|CORTE TALLA Y ACABADO DE LA PIEDRA
2399|FABRICACION DE OTROS PRODUCTOS MINERALES NO METALICOS NO CLASIFICADOS PREVIAMENTE
2410|INDUSTRIAS BASICAS DE HIERRO Y ACERO
2420|FABRICACION DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y OTROS METALES NO FERROSOS
2431|FUNDICION DE HIERRO Y ACERO
2432|FUNDICION DE METALES NO FERROSOS
2511|FABRICACION DE PRODUCTOS METALICOS PARA USO ESTRUCTURAL
2512|FABRICACION DE TANQUES DEPOSITOS Y RECIPIENTES DE METAL
2513|FABRICACION DE GENERADORES DE VAPOR EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCION CENTRAL
2520|FABRICACION DE ARMAS Y MUNICIONES
2591|FORJA PRENSADO ESTAMPADO Y LAMINADO DE METALES; PULVIMETALURGIA
2592|TRATAMIENTO Y REVESTIMIENTO DE METALES; MAQUINADO
2593|FABRICACION DE ARTICULOS DE CUCHILLERIA HERRAMIENTAS DE MANO Y ARTICULOS DE FERRETERIA
2599|FABRICACION DE OTROS PRODUCTOS ELABORADOS DE METAL NO CLASIFICADOS PREVIAMENTE
2610|FABRICACION DE COMPONENTES Y TABLEROS ELECTRONICOS
2620|FABRICACION DE ORDENADORES Y EQUIPO PERIFERICO
2630|FABRICACION DE EQUIPO DE COMUNICACIONES
2640|FABRICACION DE APARATOS ELECTRONICOS DE CONSUMO
2651|FABRICACION DE EQUIPO DE MEDICION PRUEBA NAVEGACION Y CONTROL
2652|FABRICACION DE RELOJES
2660|FABRICACION DE EQUIPO DE IRRADIACION Y EQUIPO ELECTRONICO DE USO MEDICO Y TERAPEUTICO
2670|FABRICACION DE INSTRUMENTOS OPTICOS Y EQUIPO FOTOGRAFICO
2680|FABRICACION DE SOPORTES MAGNETICOS Y OPTICOS
2710|FABRICACION DE MOTORES GENERADORES Y TRANSFORMADORES ELECTRICOS Y APARATOS DE DISTRIBUCION Y CONTROL DE LA ENERGIA ELECTRICA
2720|FABRICACION DE PILAS BATERIAS Y ACUMULADORES
2731|FABRICACION DE CABLES DE FIBRA OPTICA
2732|FABRICACION DE OTROS HILOS Y CABLES ELECTRICOS
2733|FABRICACION DE DISPOSITIVOS DE CABLEADO
2740|FABRICACION DE EQUIPO ELECTRICO DE ILUMINACION
2750|FABRICACION DE APARATOS DE USO DOMESTICO
2790|FABRICACION DE OTROS TIPOS DE EQUIPO ELECTRICO
2811|FABRICACION DE MOTORES Y TURBINAS EXCEPTO MOTORES PARA AERONAVES VEHICULOS AUTOMOTORES Y MOTOCICLETAS
2812|FABRICACION DE EQUIPO DE PROPULSION DE FLUIDOS
2813|FABRICACION DE OTRAS BOMBAS COMPRESORES GRIFOS Y VALVULAS
2814|FABRICACION DE COJINETES ENGRANAJES TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISION
2815|FABRICACION DE HORNOS HOGARES Y QUEMADORES
2816|FABRICACION DE EQUIPO DE ELEVACION Y MANIPULACION
2817|FABRICACION DE MAQUINARIA Y EQUIPO DE OFICINA (EXCEPTO ORDENADORES Y EQUIPO PERIFERICO)
2818|FABRICACION DE HERRAMIENTAS DE MANO MOTORIZADAS
2819|FABRICACION DE OTROS TIPOS DE MAQUINARIA DE USO GENERAL
2821|FABRICACION DE MAQUINARIA AGROPECUARIA Y FORESTAL
2822|FABRICACION DE MAQUINARIA PARA LA CONFORMACION DE METALES Y DE MAQUINAS HERRAMIENTA
2823|FABRICACION DE MAQUINARIA METALURGICA
2824|FABRICACION DE MAQUINARIA PARA LA EXPLOTACION DE MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCION
2825|FABRICACION DE MAQUINARIA PARA LA ELABORACION DE ALIMENTOS BEBIDAS Y TABACO
2826|FABRICACION DE MAQUINARIA PARA LA ELABORACION DE PRODUCTOS TEXTILES PRENDAS DE VESTIR Y CUEROS
2829|FABRICACION DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL
2910|FABRICACION DE VEHICULOS AUTOMOTORES
2920|FABRICACION DE CARROCERIAS PARA VEHICULOS AUTOMOTORES; FABRICACION DE REMOLQUES Y SEMIRREMOLQUES
2930|FABRICACION DE PARTES PIEZAS Y ACCESORIOS PARA VEHICULOS AUTOMOTORES
3011|CONSTRUCCION DE BUQUES Y ENTIDADES FLOTANTES
3012|CONSTRUCCION DE EMBARCACIONES DE RECREO Y DE DEPORTE
3020|FABRICACION DE LOCOMOTORAS Y MATERIAL RODANTE
3030|FABRICACION DE AERONAVES NAVES ESPACIALES Y MAQUINARIA CONEXA
3040|FABRICACION DE VEHICULOS MILITARES DE COMBATE
3091|FABRICACION DE MOTOCICLETAS
3092|FABRICACION DE BICICLETAS Y DE SILLONES DE RUEDAS PARA INVALIDOS
3099|FABRICACION DE OTROS TIPOS DE EQUIPO DE TRANSPORTE NO CLASIFICADOS PREVIAMENTE
3100|FABRICACION DE MUEBLES
3211|FABRICACION DE JOYAS Y ARTICULOS CONEXOS
3212|FABRICACION DE BISUTERIA Y ARTICULOS CONEXOS
3220|FABRICACION DE INSTRUMENTOS DE MUSICA
3230|FABRICACION DE ARTICULOS DE DEPORTE
3240|FABRICACION DE JUEGOS Y JUGUETES
3250|FABRICACION DE INSTRUMENTOS Y MATERIALES MEDICOS Y ODONTOLOGICOS
3290|OTRAS INDUSTRIAS MANUFACTURERAS NO CLASIFICADOS PREVIAMENTE
3311|REPARACION DE PRODUCTOS ELABORADOS DE METAL
3312|REPARACION DE MAQUINARIA
3313|REPARACION DE EQUIPO ELECTRONICO Y OPTICO
3314|REPARACION DE EQUIPO ELECTRICO
3315|REPARACION DE EQUIPO DE TRANSPORTE EXCEPTO VEHICULOS AUTOMOTORES
3319|REPARACION DE OTROS TIPOS DE EQUIPO
3320|INSTALACION DE MAQUINARIA Y EQUIPO INDUSTRIALES
3510|GENERACION TRANSMISION Y DISTRIBUCION DE ENERGIA ELECTRICA
3520|FABRICACION DE GAS; DISTRIBUCION DE COMBUSTIBLES GASEOSOS POR TUBERIAS
3530|SUMINISTRO DE VAPOR Y DE AIRE ACONDICIONADO
3600|CAPTACION TRATAMIENTO Y DISTRIBUCION DE AGUA
3700|EVACUACION DE AGUAS RESIDUALES
3811|RECOGIDA DE DESECHOS NO PELIGROSOS
3812|RECOGIDA DE DESECHOS PELIGROSOS
3821|TRATAMIENTO Y ELIMINACION DE DESECHOS NO PELIGROSOS
3822|TRATAMIENTO Y ELIMINACION DE DESECHOS PELIGROSOS
3830|RECUPERACION DE MATERIALES
3900|ACTIVIDADES DE DESCONTAMINACION Y OTROS SERVICIOS DE GESTION DE DESECHOS
4100|CONSTRUCCION DE EDIFICIOS
4210|CONSTRUCCION DE CARRETERAS Y VIAS DE FERROCARRIL
4220|CONSTRUCCION DE PROYECTOS DE SERVICIO PUBLICO
4290|CONSTRUCCION DE OTRAS OBRAS DE INGENIERIA CIVIL
4311|DEMOLICION
4312|PREPARACION DEL TERRENO
4321|INSTALACIONES ELECTRICAS
4322|INSTALACIONES DE FONTANERIA CALEFACCION Y AIRE ACONDICIONADO
4329|OTRAS INSTALACIONES PARA OBRAS DE CONSTRUCCION
4330|TERMINACION Y ACABADO DE EDIFICIOS
4390|OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCION
4510|VENTA DE VEHICULOS AUTOMOTORES
4520|MANTENIMIENTO Y REPARACION DE VEHICULOS AUTOMOTORES
4530|VENTA DE PARTES PIEZAS Y ACCESORIOS PARA VEHICULOS AUTOMOTORES
4540|VENTA MANTENIMIENTO Y REPARACION DE MOTOCICLETAS Y SUS PARTES PIEZAS Y ACCESORIOS
4610|VENTA AL POR MAYOR A CAMBIO DE UNA RETRIBUCION O POR CONTRATA
4620|VENTA AL POR MAYOR DE MATERIAS PRIMAS AGROPECUARIAS Y ANIMALES VIVOS
4630|VENTA AL POR MAYOR DE ALIMENTOS BEBIDAS Y TABACO
4641|VENTA AL POR MAYOR DE PRODUCTOS TEXTILES PRENDAS DE VESTIR Y CALZADO
4649|VENTA AL POR MAYOR DE OTROS ENSERES DOMESTICOS
4651|VENTA AL POR MAYOR DE ORDENADORES EQUIPO PERIFERICO Y PROGRAMAS DE INFORMATICA
4652|VENTA AL POR MAYOR DE EQUIPO PARTES Y PIEZAS ELECTRONICOS Y DE TELECOMUNICACIONES
4653|VENTA AL POR MAYOR DE MAQUINARIA EQUIPO Y MATERIALES AGROPECUARIOS
4659|VENTA AL POR MAYOR DE OTROS TIPOS DE MAQUINARIA Y EQUIPO
4661|VENTA AL POR MAYOR DE COMBUSTIBLES SOLIDOS LIQUIDOS Y GASEOSOS Y PRODUCTOS CONEXOS
4662|VENTA AL POR MAYOR DE METALES Y MINERALES METALIFEROS
4663|VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCION ARTICULOS DE FERRETERIA Y EQUIPO Y MATERIALES DE FONTANERIA Y CALEFACCION
4669|VENTA AL POR MAYOR DE DESPERDICIOS DESECHOS Y CHATARRA Y OTROS PRODUCTOS NO CLASIFICADOS PREVIAMENTE
4690|VENTA AL POR MAYOR NO ESPECIALIZADA
4711|VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS CON PREDOMINIO DE LA VENTA DE ALIMENTOS BEBIDAS O TABACO
4719|OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS
4721|VENTA AL POR MENOR DE ALIMENTOS EN COMERCIOS ESPECIALIZADOS
4722|VENTA AL POR MENOR DE BEBIDAS EN COMERCIOS ESPECIALIZADOS
4723|VENTA AL POR MENOR DE PRODUCTOS DE TABACO EN COMERCIOS ESPECIALIZADOS
4730|VENTA AL POR MENOR DE COMBUSTIBLES PARA VEHICULOS AUTOMOTORES EN COMERCIOS ESPECIALIZADOS
4741|VENTA AL POR MENOR DE ORDENADORES EQUIPO PERIFERICO PROGRAMA DE INFORMATICA Y EQUIPO DE TELECOMUNICION EN COMERCIOS ESPECIALIZADOS
4742|VENTA AL POR MENOR DE EQUIPO DE SONIDO Y DE VIDEO EN COMERCIOS ESPECIALIZADOS
4751|VENTA AL POR MENOR DE PRODUCTOS TEXTILES EN COMERCIOS ESPECIALIZADOS
4752|VENTA AL POR MENOR DE ARTICULOS DE FERRETERIA PINTURAS Y PRODUCTOS DE VIDRIO EN COMERCIOS ESPECIALIZADOS
4753|VENTA AL POR MENOR DE TAPICES ALFOMBRAS Y CUBRIMIENTOS PARA PAREDES Y PISOS EN COMERCIOS ESPECIALIZADOS
4759|VENTA AL POR MENOR DE APARATOS ELECTRICOS DE USO DOMESTICO MUEBLES EQUIPO DE ILUMINACION Y OTROS ENSERES EN COMERCIOS ESPECIALIZADOS
4761|VENTA AL POR MENOR DE LIBROS PERIODICOS Y ARTICULOS DE PAPELERIA EN COMERCIOS ESPECIALIZADOS
4762|VENTA AL POR MENOR DE GRABACIONES DE MUSICA Y DE VIDEO EN COMERCIOS ESPECIALIZADOS
4763|VENTA AL POR MENOR DE EQUIPO DE DEPORTE EN COMERCIOS ESPECIALIZADOS
4764|VENTA AL POR MENOR DE JUEGOS Y JUGUETES EN COMERCIOS ESPECIALIZADOS
4771|VENTA AL POR MENOR DE PRENDAS DE VESTIR CALZADO Y ARTICULOS DE CUERO EN COMERCIOS ESPECIALIZADOS
4772|VENTA AL POR MENOR DE PRODUCTOS FARMACEUTICOS Y MEDICOS COSMETICOS Y ARTICULOS DE TOCADOR EN COMERCIOS ESPECIALIZADOS
4773|VENTA AL POR MENOR DE OTROS PRODUCTOS NUEVOS EN COMERCIOS ESPECIALIZADOS
4774|VENTA AL POR MENOR DE ARTICULOS DE SEGUNDA MANO
4781|VENTA AL POR MENOR DE ALIMENTOS BEBIDAS Y TABACO EN PUESTOS DE VENTA Y MERCADOS
4782|VENTA AL POR MENOR DE PRODUCTOS TEXTILES PRENDAS DE VESTIR Y CALZADO EN PUESTOS DE VENTA Y MERCADOS
4789|VENTA AL POR MENOR DE OTROS PRODUCTOS EN PUESTOS DE VENTA Y MERCADOS
4791|VENTA AL POR MENOR POR CORREO Y POR INTERNET
4799|OTRAS ACTIVIDADES DE VENTA AL POR MENOR NO REALIZADAS EN COMERCIOS PUESTOS DE VENTA O MERCADOS
4911|TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRIL
4912|TRANSPORTE DE CARGA POR FERROCARRIL
4921|TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS POR VIA TERRESTRE
4922|OTRAS ACTIVIDADES DE TRANSPORTE POR VIA TERRESTRE
4923|TRANSPORTE DE CARGA POR CARRETERA
4930|TRANSPORTE POR TUBERIAS
5011|TRANSPORTE DE PASAJEROS MARITIMO Y DE CABOTAJE
5012|TRANSPORTE DE CARGA MARITIMO Y DE CABOTAJE
5021|TRANSPORTE DE PASAJEROS POR VIAS DE NAVEGACION INTERIORES
5022|TRANSPORTE DE CARGA POR VIAS DE NAVEGACION INTERIORES
5110|TRANSPORTE DE PASAJEROS POR VIA AEREA
5120|TRANSPORTE DE CARGA POR VIA AEREA
5210|ALMACENAMIENTO Y DEPOSITO
5221|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE TERRESTRE
5222|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE ACUATICO
5223|ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE AEREO
5224|MANIPULACION DE LA CARGA
5229|OTRAS ACTIVIDADES DE APOYO AL TRANSPORTE
5310|ACTIVIDADES POSTALES
5320|ACTIVIDADES DE MENSAJERIA
5510|ACTIVIDADES DE ALOJAMIENTO PARA ESTANCIAS CORTAS
5520|ACTIVIDADES DE CAMPAMENTOS PARQUES DE VEHICULOS RECREATIVOS Y PARQUES DE CARAVANAS
5590|OTRAS ACTIVIDADES DE ALOJAMIENTO
5610|ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MOVIL DE COMIDAS
5621|SUMINISTRO DE COMIDAS POR ENCARGO
5629|OTRAS ACTIVIDADES DE SERVICIO DE COMIDAS
5630|ACTIVIDADES DE SERVICIO DE BEBIDAS
5811|EDICION DE LIBROS
5812|EDICION DE DIRECTORIOS Y LISTAS DE CORREO
5813|EDICION DE PERIODICOS REVISTAS Y OTRAS PUBLICACIONES PERIODICAS
5819|OTRAS ACTIVIDADES DE EDICION
5820|EDICION DE PROGRAMAS INFORMATICOS
5911|ACTIVIDADES DE PRODUCCION DE PELICULAS CINEMATOGRAFICAS VIDEOS Y PROGRAMAS DE TELEVISION
5912|ACTIVIDADES DE POSTPRODUCCION DE PELICULAS CINEMATOGRAFICAS VIDEOS Y PROGRAMAS DE TELEVISION
5913|ACTIVIDADES DE DISTRIBUCION DE PELICULAS CINEMATOGRAFICAS VIDEOS Y PROGRAMAS DE TELEVISION
5914|ACTIVIDADES DE EXHIBICION DE PELICULAS CINEMATOGRAFICAS Y CINTAS DE VIDEO
5920|ACTIVIDADES DE GRABACION DE SONIDO Y EDICION DE MUSICA
6010|TRANSMISIONES DE RADIO
6020|PROGRAMACION Y TRANSMISIONES DE TELEVISION
6110|ACTIVIDADES DE TELECOMUNICACIONES ALAMBICAS
6120|ACTIVIDADES DE TELECOMUNICACIONES INALAMBRICAS
6130|ACTIVIDADES DE TELECOMUNICACIONES POR SATELITE
6190|OTRAS ACTIVIDADES DE TELECOMUNICACIONES
6201|PROGRAMACION INFORMATICA
6202|CONSULTORIA DE INFORMATICA Y GESTION DE INSTALACIONES INFORMATICAS
6209|OTRAS ACTIVIDADES DE TECNOLOGIA DE LA INFORMACION Y DE SERVICIOS INFORMATICOS
6311|PROCESAMIENTO DE DATOS HOSPEDAJE Y ACTIVIDADES CONEXAS
6312|PORTALES WEB
6391|ACTIVIDADES DE AGENCIAS DE NOTICIAS
6399|OTRAS ACTIVIDADES DE SERVICIOS DE INFORMACION NO CLASIFICADOS PREVIAMENTE
6411|BANCA CENTRAL
6419|OTROS TIPOS DE INTERMEDIACION MONETARIA
6420|ACTIVIDADES DE SOCIEDADES DE CARTERA
6430|FONDOS Y SOCIEDADES DE INVERSION Y ENTIDADES FINANCIERAS SIMILARES
6491|ARRENDAMIENTO FINANCIERO
6492|OTRAS ACTIVIDADES DE CONCESION DE CREDITO
6499|OTRAS ACTIVIDADES DE SERVICIOS FINANCIEROS EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES NO CLASIFICADOS PREVIAMENTE
6511|SEGUROS DE VIDA
6512|SEGUROS GENERALES
6520|REASEGUROS
6530|FONDOS DE PENSIONES
6611|ADMINISTRACION DE MERCADOS FINANCIEROS
6612|CORRETAJE DE VALORES Y DE CONTRATOS DE PRODUCTOS BASICOS
6619|OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS
6621|EVALUACION DE RIESGOS Y DAÑOS
6622|ACTIVIDADES DE AGENTES Y CORREDORES DE SEGUROS
6629|OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SEGUROS Y FONDOS DE PENSIONES
6630|ACTIVIDADES DE GESTION DE FONDOS
6810|ACTIVIDADES INMOBILIARIAS REALIZADAS CON BIENES PROPIOS O ARRENDADOS
6820|ACTIVIDADES INMOBILIARIAS REALIZADAS A CAMBIO DE UNA RETRIBUCION O POR CONTRATA
6910|ACTIVIDADES JURIDICAS
6920|ACTIVIDADES DE CONTABILIDAD TENEDURIA DE LIBROS Y AUDITORIA; CONSULTORIA FISCAL
7010|ACTIVIDADES DE OFICINAS PRINCIPALES
7020|ACTIVIDADES DE CONSULTORIA DE GESTION
7110|ACTIVIDADES DE ARQUITECTURA E INGENIERIA Y ACTIVIDADES CONEXAS DE CONSULTORIA TECNICA
7120|ENSAYOS Y ANALISIS TECNICOS
7210|INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES Y LA INGENIERIA
7220|INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES
7310|PUBLICIDAD
7320|ESTUDIOS DE MERCADO Y ENCUESTAS DE OPINION PUBLICA
7410|ACTIVIDADES ESPECIALIZADAS DE DISEÑO
7420|ACTIVIDADES DE FOTOGRAFIA
7490|OTRAS ACTIVIDADES PROFESIONALES CIENTIFICAS Y TECNICAS NO CLASIFICADOS PREVIAMENTE
7500|ACTIVIDADES VETERINARIAS
7710|ALQUILER Y ARRENDAMIENTO DE VEHICULOS AUTOMOTORES
7721|ALQUILER Y ARRENDAMIENTO DE EQUIPO RECREATIVO Y DEPORTIVO
7722|ALQUILER DE CINTAS DE VIDEO Y DISCOS
7729|ALQUILER Y ARRENDAMIENTO DE OTROS EFECTOS PERSONALES Y ENSERES DOMESTICOS
7730|ALQUILER Y ARRENDAMIENTO DE OTROS TIPOS DE MAQUINARIA EQUIPO Y BIENES TANGIBLES
7740|ARRENDAMIENTO DE PROPIEDAD INTELECTUAL Y PRODUCTOS SIMILARES EXCEPTO OBRAS PROTEGIDAS POR DERECHOS DE AUTOR
7810|ACTIVIDADES DE AGENCIAS DE EMPLEO
7820|ACTIVIDADES DE AGENCIAS DE EMPLEO TEMPORAL
7830|OTRAS ACTIVIDADES DE DOTACION DE RECURSOS HUMANOS
7911|ACTIVIDADES DE AGENCIAS DE VIAJES
7912|ACTIVIDADES DE OPERADORES TURISTICOS
7990|OTROS SERVICIOS DE RESERVAS Y ACTIVIDADES CONEXAS
8010|ACTIVIDADES DE SEGURIDAD PRIVADA
8020|ACTIVIDADES DE SERVICIOS DE SISTEMAS DE SEGURIDAD
8030|ACTIVIDADES DE INVESTIGACION
8110|ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES
8121|LIMPIEZA GENERAL DE EDIFICIOS
8129|OTRAS ACTIVIDADES DE LIMPIEZA DE EDIFICIOS Y DE INSTALACIONES INDUSTRIALES
8130|ACTIVIDADES DE PAISAJISMO Y SERVICIOS DE MANTENIMIENTO CONEXOS
8211|ACTIVIDADES COMBINADAS DE SERVICIOS ADMINISTRATIVOS DE OFICINA
8219|FOTOCOPIADO PREPARACION DE DOCUMENTOS Y OTRAS ACTIVIDADES ESPECIALIZADAS DE APOYO DE OFICINA
8220|ACTIVIDADES DE CENTROS DE LLAMADAS
8230|ORGANIZACION DE CONVENCIONES Y EXPOSICIONES COMERCIALES
8291|ACTIVIDADES DE AGENCIAS DE COBRO Y AGENCIAS DE CALIFICACION CREDITICIA
8292|ACTIVIDADES DE ENVASADO Y EMPAQUETADO
8299|OTRAS ACTIVIDADES DE SERVICIOS DE APOYO A LAS EMPRESAS NO CLASIFICADOS PREVIAMENTE
8411|ACTIVIDADES DE LA ADMINISTRACION PUBLICA EN GENERAL
8412|REGULACION DE ACTIDADES DE ORGANISMOS QUE PRESTAN SERVICIO SANITARIO EDUCATIVO CULTURAL Y SERVICIO SOCIAL MENOS SERVICIOS DE SEGURIDAD SOCIAL
8413|REGULACION Y FACILITACION DE LA ACTIVIDAD ECONOMICA
8421|RELACIONES EXTERIORES
8422|ACTIVIDADES DE DEFENSA
8423|ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PUBLICO Y DE SEGURIDAD
8430|ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACION OBLIGATORIA
8510|ENSEÑANZA PREESCOLAR Y PRIMARIA
8521|ENSEÑANZA SECUNDARIA DE FORMACION GENERAL
8522|ENSEÑANZA SECUNDARIA DE FORMACION TECNICA Y PROFESIONAL
8530|ENSEÑANZA SUPERIOR
8541|ENSEÑANZA DEPORTIVA Y RECREATIVA
8542|ENSEÑANZA CULTURAL
8549|OTROS TIPOS DE ENSEÑANZA NO CLASIFICADOS PREVIAMENTE
8550|ACTIVIDADES DE APOYO A LA ENSEÑANZA
8610|ACTIVIDADES DE HOSPITALES
8620|ACTIVIDADES DE MEDICOS Y ODONTOLOGOS
8690|OTRAS ACTIVIDADES DE ATENCION DE LA SALUD HUMANA
8710|ACTIVIDADES DE ATENCION DE ENFERMERIA EN INSTITUCIONES
8720|ACTIVIDADES DE ATENCION EN INSTITUCIONES PARA PERSONAS CON RETRASO MENTAL ENFERMOS MENTALES Y TOXICOMANOS
8730|ACTIVIDADES DE ATENCION EN INSTITUCIONES PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD
8790|OTRAS ACTIVIDADES DE ATENCION EN INSTITUCIONES
8810|ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD
8890|OTRAS ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO
9000|ACTIVIDADES CREATIVAS ARTISTICAS Y DE ENTRETENIMIENTO
9101|ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS
9102|ACTIVIDADES DE MUSEOS Y CONSERVACION DE LUGARES Y EDIFICIOS HISTORICOS
9103|ACTIVIDADES DE JARDINES BOTANICOS Y ZOOLOGICOS Y DE RESERVAS NATURALES
9200|ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS
9311|GESTION DE INSTALACIONES DEPORTIVAS
9312|ACTIVIDADES DE CLUBES DEPORTIVOS
9319|OTRAS ACTIVIDADES DEPORTIVAS
9321|ACTIVIDADES DE PARQUES DE ATRACCIONES Y PARQUES TEMATICOS
9329|OTRAS ACTIVIDADES DE ESPARCIMIENTO Y RECREATIVAS NO CLASIFICADOS PREVIAMENTE
9411|ACTIVIDADES DE ASOCIACIONES EMPRESARIALES Y DE EMPLEADORES
9412|ACTIVIDADES DE ASOCIACIONES PROFESIONALES
9420|ACTIVIDADES DE SINDICATOS
9491|ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS
9492|ACTIVIDADES DE ORGANIZACIONES POLITICAS
9499|ACTIVIDADES DE OTRAS ASOCIACIONES NO CLASIFICADOS PREVIAMENTE
9511|REPARACION DE ORDENADORES Y EQUIPO PERIFERICO
9512|REPARACION DE EQUIPO DE COMUNICACIONES
9521|REPARACION DE APARATOS ELECTRONICOS DE CONSUMO
9522|REPARACION DE APARATOS DE USO DOMESTICO Y EQUIPO DOMESTICO Y DE JARDINERIA
9523|REPARACION DE CALZADO Y DE ARTICULOS DE CUERO
9524|REPARACION DE MUEBLES Y ACCESORIOS DOMESTICOS
9529|REPARACION DE OTROS EFECTOS PERSONALES Y ENSERES DOMESTICOS
9601|LAVADO Y LIMPIEZA INCLUIDA LA LIMPIEZA EN SECO DE PRODUCTOS TEXTILES Y DE PIEL
9602|PELUQUERIA Y OTROS TRATAMIENTOS DE BELLEZA
9603|POMPAS FUNEBRES Y ACTIVIDADES CONEXAS
9609|OTRAS ACTIVIDADES DE SERVICIOS PERSONALES NO CLASIFICADOS PREVIAMENTE
9700|ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMESTICO
9900|ACTIVIDADES DE ORGANIZACIONES Y ORGANOS EXTRATERRITORIALES
`;

/** Texto en mayúsculas, sin tildes (también la de la Ñ) y con espacios simples. */
export function normalizePeSunatActivityText(text: string | null | undefined): string {
  if (typeof text !== 'string') return '';
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/\s+/g, ' ')
    .trim();
}

/** Texto de actividad (normalizado igual que la búsqueda) → clase CIIU Rev. 4. */
export const PE_SUNAT_CIIU4_CODE_BY_ACTIVITY: ReadonlyMap<string, string> = new Map(
  RAW.split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => {
      const separator = line.indexOf('|');
      return [normalizePeSunatActivityText(line.slice(separator + 1)), line.slice(0, separator)] as const;
    }),
);

/** Clase CIIU Rev. 4 de una actividad del Padrón RUC, o `null` si no se conoce. */
export function resolvePeSunatCiiu4Code(activityText: string | null | undefined): string | null {
  const key = normalizePeSunatActivityText(activityText);
  if (key.length === 0) return null;
  return PE_SUNAT_CIIU4_CODE_BY_ACTIVITY.get(key) ?? null;
}
