/**
 * Prospecting Toolkit — Catálogo estructurado de fuentes MVP.
 *
 * Contiene únicamente los países prioritarios del MVP: CO, MX, CL, PE, EC, BR.
 * Fuentes globales incluidas como fallback (OpenCorporates, Apollo).
 * Lusha: presente pero marcada como "no discovery" — filtrada en getCatalogContext.
 *
 * Principios:
 * - P0: fuente primaria oficial, alta confianza para el país
 * - P1: complementaria o de nicho, útil pero no suficiente sola
 * - P2: global o pagada, fallback de último recurso
 */

import type { CatalogSource } from './types';

// ─── Identificadores fiscales por país ────────────────────────────────────────

export const FISCAL_IDENTIFIERS: Record<string, string> = {
  AR: 'CUIT',
  BO: 'NIT',
  BR: 'CNPJ',
  CL: 'RUT',
  CO: 'NIT',
  CR: 'Cédula Jurídica',
  DO: 'RNC',
  EC: 'RUC',
  GT: 'NIT',
  HN: 'RTN',
  MX: 'RFC',
  NI: 'RUC',
  PA: 'RUC',
  PE: 'RUC',
  PY: 'RUC',
  SV: 'NRC/NIT',
  UY: 'RUT',
};

// ─── Riesgos conocidos por país ───────────────────────────────────────────────

export const COUNTRY_RISKS: Record<string, string[]> = {
  CO: [
    'SIIS/Supersociedades cubre principalmente empresas medianas/grandes; microempresas pueden no aparecer.',
    'RUES puede tener datos desactualizados en sectores informales.',
    'SECOP II solo cubre proveedores del Estado; no representa todo el mercado.',
    'No asumir que toda empresa registrada en RUES está activa.',
    'Validar NIT antes de presentar la empresa — errores de transcripción son frecuentes.',
  ],
  MX: [
    'DENUE API tiene límite de registros por consulta; paginar correctamente.',
    'SIEM puede tener datos con 1-2 años de antigüedad para PYMES.',
    'No todas las empresas tienen RFC público disponible via DENUE.',
    'Empresas del sector informal no aparecen en registros oficiales.',
    'CANAIVE/AMIA solo cubren sus sectores específicos.',
  ],
  CL: [
    'RES solo cubre empresas registradas activamente; algunas PYMES operan sin registro formal.',
    'ChileCompra solo cubre proveedores del Estado chileno.',
    'Datos de contacto en fuentes públicas chilenas son escasos.',
    'No confundir RUT de persona natural con RUT de empresa.',
    'SII proporciona validación fiscal pero no perfil de empresa completo.',
  ],
  PE: [
    'SUNAT Padrón RUC es la fuente más confiable pero solo contiene datos tributarios.',
    'SEACE/OSCE solo cubre proveedores de contrataciones del Estado.',
    'PRODUCE Manufactura solo cubre sector manufacturero.',
    'Alta informalidad en algunos sectores — registros incompletos.',
    'Verificar estado activo en SUNAT antes de prospectar.',
  ],
  EC: [
    'SCVS/Supercias cubre principalmente grandes empresas obligadas a reportar.',
    'SERCOP cubre solo proveedores del Estado ecuatoriano.',
    'Datos de contacto en fuentes oficiales ecuatorianas son muy limitados.',
    'Distinguir RUC de persona natural vs empresa antes de prospectar.',
  ],
  BR: [
    'CNPJ es la fuente más completa de LatAm pero puede incluir empresas inactivas.',
    'cnpj.ws es un tercero no oficial; validar disponibilidad y TOS antes de usar.',
    'Volumen masivo requiere filtrado cuidadoso por situação: Ativa.',
    'Datos de contacto en Receita Federal son mínimos.',
  ],
};

// ─── Reglas globales del agente ───────────────────────────────────────────────

export const GLOBAL_RULES: string[] = [
  'No usar Lusha para discovery; solo para enriquecimiento de contactos bajo demanda.',
  'Apollo solo como fallback explícito cuando fuentes públicas no alcanzan el objetivo.',
  'HubSpot duplicate check obligatorio antes de presentar empresa como nueva.',
  'No inventar website, LinkedIn, ni datos de contacto.',
  'Máximo 25 empresas candidatas por ejecución.',
  'Usar identificador fiscal del país como ancla de deduplicación cuando esté disponible.',
];

// ─── Catálogo de fuentes ──────────────────────────────────────────────────────

export const CATALOG_SOURCES: CatalogSource[] = [

  // ── Colombia ────────────────────────────────────────────────────────────────
  {
    key: 'co_siis',
    name: 'Supersociedades SIIS',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://siis.ia.supersociedades.gov.co/',
    automationLevel: 'high',
    recommendedUse:
      'Enriquecimiento post-discovery y priorización de candidatos colombianos medianos/grandes. Señales financieras (ingresos, utilidades, activos) y validación de NIT. Usar desde snapshot/cache después del discovery. NO usar como fuente de discovery principal ni como fuente universal — no cubre microempresas ni empresas no vigiladas por Supersociedades.',
    limitations: [
      'No es fuente de discovery universal — solo empresas bajo supervisión de Supersociedades',
      'No cubre microempresas ni empresas no vigiladas',
      'Datos con rezago de 1-2 años respecto al ejercicio fiscal',
      'No incluye datos de contacto (emails, teléfonos)',
      'No reemplaza RUES para discovery amplio',
      'Requiere snapshot/cache — no consultar Excel en cada búsqueda del wizard',
    ],
    riskNotes: [
      'Usar como complemento post-discovery, no como única fuente de validación',
      'Evitar usar como única fuente — combinar con RUES para cobertura amplia',
      'No consultar Excel de SIIS en cada búsqueda — ejecutar por ETL batch controlado',
      'Ejecutar ETL programado con control de versiones de snapshot',
    ],
  },
  {
    key: 'co_datos_gov',
    name: 'datos.gov.co',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'public_dataset',
    url: 'https://www.datos.gov.co/',
    automationLevel: 'high',
    recommendedUse: 'Datasets públicos con señales empresariales. Varios sectores disponibles para descarga.',
    limitations: ['Calidad variable según dataset', 'Frecuencia de actualización irregular'],
  },
  {
    key: 'co_rues',
    name: 'RUES (Registro Único Empresarial)',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'connection_required',
    type: 'official_registry',
    url: 'https://www.rues.org.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery amplio por NIT. Cubre microempresas hasta grandes empresas registradas en Cámaras.',
    limitations: ['Sin API pública oficial', 'Consultas requieren nombre o NIT'],
    riskNotes: ['Datos pueden estar desactualizados para empresas pequeñas', 'Requiere acuerdo o API privada para consulta masiva — pendiente negociación'],
  },
  {
    key: 'co_secop2',
    name: 'SECOP II (Compras Públicas)',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.secop.gov.co/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado. Señal de empresa activa con historial contractual B2G.',
    limitations: ['Solo empresas que venden al Estado colombiano'],
  },
  {
    key: 'co_minsalud_reps',
    name: 'MinSalud REPS',
    countryCodes: ['CO'],
    sectors: ['salud', 'health', 'farmaceutico', 'pharmaceutical', 'clinica', 'hospital', 'ips', 'eps', 'laboratorio'],
    priority: 'P0',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.reps.gov.co/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de prestadores de salud habilitados. Fuente primaria para discovery en sector salud colombiano.',
    riskNotes: ['Acceso masivo no confirmado — validar endpoint de descarga antes de integrar'],
  },
  {
    key: 'co_superfinanciera',
    name: 'Superfinanciera Colombia',
    countryCodes: ['CO'],
    sectors: ['financiero', 'fintech', 'banca', 'banco', 'seguros', 'financial', 'banking', 'insurance', 'aseguradora'],
    priority: 'P0',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.superfinanciera.gov.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en sector financiero supervisado: bancos, aseguradoras, fiduciarias, fondos.',
    riskNotes: ['Extracción masiva no probada — validar disponibilidad de datos estructurados antes de integrar'],
  },

  // ── Colombia — Innovación / Emprendimiento ──────────────────────────────────
  {
    key: 'co_innpulsa',
    name: 'iNNpulsa Colombia (MinComercio)',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'innovacion', 'startups', 'emprendimiento', 'technology', 'innovation', 'startup_ecosystem'],
    priority: 'P2',
    operationalStatus: 'pending_validation',
    type: 'other',
    url: 'https://www.innpulsacolombia.com/',
    automationLevel: 'low',
    recommendedUse: 'Empresas beneficiarias de programas iNNpulsa (MinComercio). Señal de startup/empresa innovadora apoyada por el Estado colombiano. Pendiente validación de acceso a lista estructurada de beneficiarios.',
    limitations: [
      'Solo empresas con programas iNNpulsa — cobertura acotada',
      'Lista de beneficiarios pública pero sin API — extracción manual o web',
      'Pendiente validación de disponibilidad de directorio estructurado',
    ],
    riskNotes: [
      'Fuente pública del Estado colombiano — sin costo ni ToS restrictivo',
      'Validar acceso a directorio estructurado antes de integrar en producción',
    ],
  },

  // ── Colombia — Tecnología (Hito 16Y.1) ─────────────────────────────────────
  {
    key: 'co_fedesoft',
    name: 'Fedesoft (Federación Colombiana de Software y TI)',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'software', 'tic', 'servicios_ti', 'technology', 'software_development', 'it_services'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'industry_association',
    url: 'https://www.fedesoft.org/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en ecosistema software y TI colombiano. Directorio de empresas afiliadas al gremio nacional del software.',
    limitations: ['Solo empresas afiliadas a Fedesoft', 'Sin API pública — consulta directa o web scraping'],
  },
  {
    key: 'co_colombia_fintech',
    name: 'Colombia Fintech (Asociación Fintech de Colombia)',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'fintech', 'financiero', 'pagos', 'technology', 'payments', 'financial_technology'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'industry_association',
    url: 'https://www.colombiafintech.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery sectorial fintech: pagos, lending, insurtech, wealthtech, neobancos colombianos. Señal de empresa activa en intersección tech-financiero.',
    limitations: ['Solo miembros asociados', 'Solapamiento parcial con co_superfinanciera'],
  },
  {
    key: 'co_colombia_digital',
    name: 'Colombia Digital',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'transformacion_digital', 'tic', 'technology', 'digital_transformation', 'ict'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.colombiadigital.net/',
    automationLevel: 'low',
    recommendedUse: 'Señal sectorial de transformación digital. Empresas y casos del ecosistema TIC colombiano. Útil para contexto y discovery de actores tech.',
    limitations: ['No es un directorio estructurado de empresas', 'Cobertura variada — más útil para señal sectorial que discovery masivo'],
  },
  {
    key: 'co_andicom',
    name: 'ANDICOM (Congreso TIC Colombia / CINTEL)',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'telecomunicaciones', 'software', 'servicios_ti', 'technology', 'telecommunications', 'ict'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.andicom.co/',
    automationLevel: 'low',
    recommendedUse: 'Expositores, sponsors y empresas activas del ecosistema TIC empresarial colombiano. Señal de empresa tech con presencia institucional.',
    limitations: ['Solo empresas que participan o patrocinan el evento', 'Datos disponibles principalmente en período de congreso'],
  },
  {
    key: 'co_ruta_n',
    name: 'Ruta N (Ecosistema Innovación Medellín)',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'innovacion', 'startups', 'software', 'technology', 'innovation', 'startup_ecosystem'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'other',
    url: 'https://www.rutanmedellin.org/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de startups y empresas tech en ecosistema Medellín. Empresas relacionadas con programas de innovación y aceleración.',
    limitations: ['Foco geográfico en Medellín y Antioquia', 'Sin API de directorio — consulta manual o web'],
  },
  {
    key: 'co_microsoft_partners',
    name: 'Microsoft Partner Directory Colombia',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'cloud', 'software', 'integradores', 'technology', 'cloud_computing', 'it_services', 'enterprise_software'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'commercial_provider',
    url: 'https://www.microsoft.com/en-us/solution-providers/home',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de integradores, ISVs y partners cloud certificados por Microsoft en Colombia. Señal de empresa tech activa con certificación formal.',
    limitations: ['Solo partners certificados Microsoft', 'Filtrar por país Colombia en la búsqueda', 'Sin API pública de directorio'],
  },
  {
    key: 'co_aws_partners',
    name: 'AWS Partner Network Colombia',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'cloud', 'infraestructura_ti', 'technology', 'cloud_computing', 'infrastructure', 'devops'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'commercial_provider',
    url: 'https://partners.amazonaws.com/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de partners cloud AWS en Colombia: consultoría cloud, infraestructura, MSPs, ISVs. Señal de empresa tech con práctica cloud activa.',
    limitations: ['Solo partners certificados AWS', 'Filtrar por país Colombia', 'Sin API pública'],
  },
  {
    key: 'co_getonboard',
    name: 'GetOnBoard Colombia',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'software', 'startups', 'talento_tech', 'technology', 'software_development', 'tech_talent'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'other',
    url: 'https://www.getonbrd.com/',
    automationLevel: 'low',
    recommendedUse: 'Identificar empleadores tech activos en Colombia a través de vacantes publicadas. Señal indirecta de empresa tech con capacidad de contratación.',
    limitations: ['Señal de actividad laboral, no directorio formal de empresas', 'Cobertura limitada a empresas que publican en la plataforma'],
  },

  // ── México ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_denue',
    name: 'DENUE / INEGI API',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.inegi.org.mx/servicios/api_denue.html',
    automationLevel: 'high',
    recommendedUse: 'Discovery principal en México. API oficial con 5M+ establecimientos por municipio, clasificador SCIAN y tamaño.',
    limitations: ['Rate limits por token de acceso', 'RFC no incluido en respuesta de API'],
    riskNotes: ['Paginar correctamente', 'Actualización cada 1-2 años'],
  },
  {
    key: 'mx_datos_gob',
    name: 'datos.gob.mx (Portal Datos Abiertos México)',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'public_dataset',
    url: 'https://datos.gob.mx/',
    automationLevel: 'high',
    recommendedUse: 'Agregador de datasets públicos mexicanos. Acceso a DENUE histórico por entidad/actividad (CSV por estado, versiones 2016–2019+), SIEM (establecimientos visitados por cámaras empresariales), y otros datasets sectoriales. CKAN API disponible.',
    limitations: [
      'No es fuente primaria — agrega datasets con fechas variables de actualización',
      'DENUE más reciente disponible vía app INEGI directa (mx_denue); datos.gob.mx tiene versiones históricas',
      'Calidad y cobertura variable por dataset — verificar fecha y fuente antes de integrar',
    ],
  },
  {
    key: 'mx_siem',
    name: 'SIEM (Sistema de Información Empresarial Mexicano)',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'http://www.siem.gob.mx/',
    automationLevel: 'medium',
    recommendedUse: 'Complemento a DENUE para PYMES con datos de contacto básicos. Registro con Cámara de Comercio.',
    limitations: ['Cobertura menor que DENUE', 'Sin API pública oficial'],
  },
  {
    key: 'mx_canaive',
    name: 'CANAIVE (Cámara Nacional de la Industria del Vestido)',
    countryCodes: ['MX'],
    sectors: ['textil', 'manufactura textil', 'moda', 'clothing', 'garment', 'apparel', 'textile', 'vestido', 'confeccion'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.canaive.org.mx/',
    automationLevel: 'manual',
    recommendedUse: 'Discovery en industria textil mexicana. Directorio de empresas afiliadas.',
    limitations: ['Solo afiliados a la cámara', 'Sin API — consulta manual'],
  },
  {
    key: 'mx_amia',
    name: 'AMIA (Asociación Mexicana de la Industria Automotriz)',
    countryCodes: ['MX'],
    sectors: ['automotriz', 'automotive', 'autopartes', 'auto parts', 'vehiculo', 'vehicle', 'manufactura automotriz'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.amia.com.mx/',
    automationLevel: 'manual',
    recommendedUse: 'Discovery en industria automotriz mexicana. OEMs y Tier-1.',
    limitations: ['Solo miembros asociados', 'Sin API — consulta directa'],
  },

  // ── México — Compras Públicas y Asociaciones Sectoriales ───────────────────
  {
    key: 'mx_compranet',
    name: 'CompraNet (Compras Gubernamentales México)',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'connection_required',
    type: 'procurement',
    url: 'https://compranet.hacienda.gob.mx/',
    automationLevel: 'low',
    recommendedUse: 'Discovery de proveedores del Estado mexicano. Señal B2G de empresa activa con historial contractual. Portal migrado a CompraNet 5.0; validar endpoint de descarga antes de integrar.',
    limitations: [
      'Portal migrado — endpoint CSV original caído; verificar acceso a datos abiertos en datos.gob.mx/compranet',
      'Solo empresas con contratos con el gobierno federal mexicano',
    ],
    riskNotes: [
      'Endpoint de datos estructurados pendiente de reconfirmación post-migración',
      'Fuente pública — sin costo ni ToS restrictivo conocido',
    ],
  },
  {
    key: 'mx_amiti',
    name: 'AMITI (Asociación Mexicana de la Industria de Tecnologías de la Información)',
    countryCodes: ['MX'],
    sectors: ['tecnologia', 'software', 'tic', 'servicios_ti', 'technology', 'it_services', 'software_development'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.amiti.org.mx/',
    automationLevel: 'manual',
    recommendedUse: 'Señal sectorial TI mexicana. ~200 empresas afiliadas. Útil para identificar actores del ecosistema TI; no para discovery masivo.',
    limitations: [
      'Solo ~200 afiliados — no fuente masiva',
      'Sin API — consulta manual del directorio web',
      'RFC no disponible en directorio público',
    ],
    riskNotes: [
      'ToS medio: confirmar antes de automatizar scraping del directorio',
    ],
  },
  {
    key: 'mx_fintech_mx',
    name: 'Fintech México (Asociación FinTech de México)',
    countryCodes: ['MX'],
    sectors: ['tecnologia', 'fintech', 'financiero', 'pagos', 'technology', 'payments', 'financial_technology'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.fintechmx.com/',
    automationLevel: 'manual',
    recommendedUse: 'Señal sectorial fintech mexicana. Directorio de empresas miembro. Volumen pequeño; útil para señal de actor activo en ecosistema fintech MX.',
    limitations: [
      'Volumen reducido — directorio de miembros, no fuente masiva',
      'Sin API pública — consulta manual del directorio',
      'Pendiente validación de URL activa y cobertura del directorio',
    ],
    riskNotes: [
      'Verificar URL y disponibilidad del directorio antes de integrar',
    ],
  },

  // ── Chile ───────────────────────────────────────────────────────────────────
  {
    key: 'cl_res',
    name: 'RES / datos.gob.cl',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://datos.gob.cl/',
    automationLevel: 'high',
    recommendedUse: 'Discovery principal en Chile. Portal de datos abiertos con datasets de empresas activas por sector.',
  },
  {
    key: 'cl_chilecompra',
    name: 'ChileCompra (Mercado Público)',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.mercadopublico.cl/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado chileno. API disponible. Señal de empresa activa con contratación B2G.',
    limitations: ['Solo empresas proveedoras del Estado'],
  },
  {
    key: 'cl_sence_otec',
    name: 'SENCE OTEC',
    countryCodes: ['CL'],
    sectors: ['capacitacion', 'educacion', 'training', 'hr', 'recursos humanos', 'capital humano', 'formacion'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.sence.cl/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de organismos técnicos de capacitación laboral en Chile.',
    limitations: ['Solo sector capacitación formal', 'Sin API pública'],
  },
  {
    key: 'cl_sii',
    name: 'SII Chile (Validación tributaria)',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'validation_only',
    type: 'official_registry',
    url: 'https://www.sii.cl/',
    automationLevel: 'low',
    recommendedUse: 'Validación de RUT y estado tributario. No usar para discovery masivo.',
    limitations: ['Solo validación individual de RUT', 'No permite automatización masiva'],
    riskNotes: ['No confundir RUT de persona natural con empresa'],
  },
  {
    key: 'cl_corfo',
    name: 'CORFO Chile (Corporación de Fomento)',
    countryCodes: ['CL'],
    sectors: ['manufactura', 'tecnologia', 'agronegocio', 'pesca', 'turismo', 'manufacturing', 'technology', 'agribusiness', 'fishing', 'tourism'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.corfo.cl/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de empresas financiadas o asociadas a CORFO. Directorio de empresas beneficiarias de programas de desarrollo productivo.',
    limitations: ['Solo empresas con algún vínculo CORFO', 'Sin API pública masiva'],
  },
  {
    key: 'cl_cmf',
    name: 'CMF Chile (Comisión para el Mercado Financiero)',
    countryCodes: ['CL'],
    sectors: ['financiero', 'seguros', 'inversión', 'fondos mutuos', 'financial', 'insurance', 'investment', 'mutual funds', 'fiduciaria'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.cmfchile.cl/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de intermediarios financieros, administradoras de fondos, corredoras. Fuente para discovery en sector financiero chileno.',
    limitations: ['Solo sector financiero regulado', 'Consultas manuales o mediante solicitud'],
  },
  {
    key: 'cl_sofofa',
    name: 'SOFOFA Chile (Sociedad de Fomento Fabril)',
    countryCodes: ['CL'],
    sectors: ['manufactura', 'industrial', 'fabricacion', 'manufacturing', 'industrial production', 'factory'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.sofofa.cl/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas asociadas a SOFOFA. Señal de empresa manufacturera activa y alineada con industria formal chilena.',
    limitations: ['Solo miembros afiliados a SOFOFA', 'Sin API — consulta manual o directorio'],
  },
  {
    key: 'cl_ccs',
    name: 'CCS Chile (Cámara de Comercio de Santiago)',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccs.cl/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de comercios y empresas asociadas en Santiago. Amplia cobertura en Región Metropolitana.',
    limitations: ['Solo afiliados CCS', 'Sin API pública'],
  },

  // ── Chile — Innovación / Startups ───────────────────────────────────────────
  {
    key: 'cl_startup_chile',
    name: 'Startup Chile (CORFO)',
    countryCodes: ['CL'],
    sectors: ['tecnologia', 'startups', 'innovacion', 'technology', 'startup_ecosystem', 'innovation'],
    priority: 'P2',
    operationalStatus: 'pending_validation',
    type: 'other',
    url: 'https://www.startupchile.org/',
    automationLevel: 'low',
    recommendedUse: 'Lista de startups beneficiarias del programa Startup Chile de CORFO. Señal de empresa tech/innovadora activa en Chile. Pendiente validación de URL de directorio público estructurado.',
    limitations: [
      'Solo startups beneficiarias del programa — universo acotado',
      'Directorio web público; estructura y formato de acceso pendiente de validación',
    ],
    riskNotes: [
      'Fuente pública de CORFO (Estado chileno) — sin costo ni ToS restrictivo',
      'Validar URL de directorio o endpoint de descarga antes de integrar en producción',
    ],
  },

  // ── República Dominicana ────────────────────────────────────────────────────
  {
    key: 'do_camaratic',
    name: 'Cámara de Comercio y Producción (CAMARATIC)',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://camaratic.do/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas afiliadas a la principal cámara de comercio dominicana. Fuente de empresas activas en RD.',
    limitations: ['Solo miembros afiliados a CAMARATIC', 'Sin API pública'],
  },
  {
    key: 'do_camara_sto_domingo',
    name: 'Cámara de Comercio de Santo Domingo',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccsd.com.do/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional para zona metropolitana. Directorio de empresas afiliadas en Santo Domingo.',
    limitations: ['Solo afiliados CCSD', 'Sin API — consulta manual'],
  },

  {
    key: 'do_dgcp',
    name: 'DGCP (Dirección General de Contrataciones Públicas RD)',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://datosabiertos.dgcp.gob.do/datos-abiertos/tablas',
    automationLevel: 'medium',
    recommendedUse: 'Proveedores del Estado dominicano con RNC. Datos desde 2005. Señal de empresa activa con historial contractual B2G en República Dominicana. Portal de datos abiertos OCDS.',
    limitations: [
      'Solo empresas proveedoras del Estado dominicano — no representa el universo empresarial completo de RD',
      'Portal SPA (React) — extracción requiere inspeccionar API subyacente o usar datos.gob.do',
      'Volumen moderado — decenas de miles de proveedores registrados, no millones',
    ],
    riskNotes: [
      'Miembro Open Contracting Partnership (OCDS) — datos bajo estándares abiertos, riesgo legal bajo',
    ],
  },

  // ── Perú ────────────────────────────────────────────────────────────────────
  {
    key: 'pe_sunat_bulk',
    name: 'SUNAT Padrón RUC Bulk (Descarga masiva)',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'http://www2.sunat.gob.pe/padron_reducido_ruc.zip',
    automationLevel: 'high',
    recommendedUse: 'Descarga masiva del Padrón Reducido RUC. 11–14M registros: RUC, razón social, estado contribuyente, condición domicilio, UBIGEO. Sin auth. Complementar con pe_sunat para enriquecimiento CIIU individual.',
    limitations: [
      'Padrón reducido no incluye actividad CIIU — usar consulta SOL individual para obtener sector',
      'Incluye personas naturales con RUC; filtrar por tipo de contribuyente para empresas jurídicas',
      'ZIP ~387 MB; actualización variable — verificar fecha del archivo antes de procesar',
    ],
    riskNotes: [
      'Filtrar estado: ACTIVO antes de prospectar',
      'Amparado por Resolución de Superintendencia N° 304-2024/SUNAT — uso público permitido',
    ],
  },
  {
    key: 'pe_sunat',
    name: 'SUNAT Padrón RUC',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'validation_only',
    type: 'official_registry',
    url: 'https://e-consultaruc.sunat.gob.pe/',
    automationLevel: 'medium',
    recommendedUse: 'Fuente principal en Perú. Padrón RUC con razón social, estado activo, actividad CIIU.',
    limitations: ['Sin API oficial para consulta masiva', 'Solo datos tributarios básicos'],
    riskNotes: ['Verificar estado: Activo antes de prospectar'],
  },
  {
    key: 'pe_seace',
    name: 'OSCE / SEACE (Contrataciones del Estado)',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.seace.gob.pe/',
    automationLevel: 'high',
    recommendedUse: 'Discovery de proveedores del Estado peruano. Señal de empresa activa con historial B2G.',
    limitations: ['Solo empresas que contratan con el Estado'],
  },
  {
    key: 'pe_produce',
    name: 'PRODUCE Manufactura',
    countryCodes: ['PE'],
    sectors: ['manufactura', 'manufacturing', 'industria', 'industrial', 'produccion', 'production', 'planta'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'public_dataset',
    url: 'https://www.gob.pe/produce',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en sector manufactura peruano. Padrones y estadísticas de empresas manufactureras.',
    limitations: ['Solo sector manufactura'],
  },

  // ── Perú — Cámara de Comercio ───────────────────────────────────────────────
  {
    key: 'pe_camara_lima',
    name: 'Cámara de Comercio de Lima',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'pending_validation',
    type: 'industry_association',
    url: 'https://www.camaralima.org.pe/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas asociadas a la Cámara de Comercio de Lima. Señal de empresa peruana activa y formalmente registrada. Pendiente validación de acceso al directorio público.',
    limitations: [
      'Solo empresas afiliadas a la CCL — no representa el universo empresarial peruano',
      'Directorio web; sin API — consulta manual',
      'Pendiente validación de estructura y acceso al directorio',
    ],
    riskNotes: [
      'Verificar disponibilidad y estructura del directorio antes de integrar en producción',
    ],
  },

  // ── Ecuador ─────────────────────────────────────────────────────────────────
  {
    key: 'ec_scvs',
    name: 'SCVS / Supercias Ecuador',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.supercias.gob.ec/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de compañías ecuatorianas. Razón social, objeto social, representante legal.',
    limitations: ['Solo empresas obligadas a reportar a Supercias', 'Excluye microempresas'],
  },
  {
    key: 'ec_sercop',
    name: 'SERCOP (Compras Públicas Ecuador)',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.sercop.gob.ec/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado ecuatoriano. Señal de empresa activa.',
    limitations: ['Solo empresas contratistas del Estado'],
  },
  {
    key: 'ec_ekos',
    name: 'EKOS Ecuador',
    countryCodes: ['EC'],
    sectors: ['manufactura', 'tecnologia', 'agronegocio', 'servicios'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'commercial_provider',
    url: 'https://www.ekosnegocios.com/',
    automationLevel: 'medium',
    recommendedUse: 'Base de datos de empresas ecuatorianas. Directorio con información de contacto y rubro empresarial.',
    limitations: ['Datos de fuente comercial tercero', 'Cobertura parcial de mercado ecuatoriano'],
  },

  // ── Guatemala ───────────────────────────────────────────────────────────────
  {
    key: 'gt_camara_comercio',
    name: 'Cámara de Comercio de Guatemala',
    countryCodes: ['GT'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.camaracomercio.com.gt/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas afiliadas a la Cámara. Identificar empresas activas en Guatemala.',
    limitations: ['Solo empresas afiliadas', 'Sin API — consulta manual o directorio web'],
  },

  // ── Honduras ────────────────────────────────────────────────────────────────
  {
    key: 'hn_ccic',
    name: 'Cámara de Comercio e Industrias de Cortés',
    countryCodes: ['HN'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccic.hn/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional. Directorio de empresas en zona industrial de Cortés.',
    limitations: ['Solo empresas afiliadas CCIC', 'Zona geográfica limitada (Cortés)'],
  },
  {
    key: 'hn_ccit',
    name: 'Cámara de Comercio e Industrias de Tegucigalpa',
    countryCodes: ['HN'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccit.hn/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional. Directorio de empresas en capital hondureña.',
    limitations: ['Solo empresas afiliadas CCIT', 'Zona geográfica limitada (Tegucigalpa)'],
  },

  // ── Brasil ──────────────────────────────────────────────────────────────────
  {
    key: 'br_receita_dados_abertos',
    name: 'Receita Federal CNPJ Dados Abertos (Bulk)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://dadosabertos.rfb.gov.br/CNPJ/',
    automationLevel: 'high',
    recommendedUse: 'Fuente principal para ingesta masiva/offline de CNPJ. Dataset más completo de LATAM — ~60M CNPJs (~22M activos). Archivos ZIP: CNPJ, razão social, CNAE, município, situação cadastral, capital social, porte, quadro societário. Filtrar CNAE 62xx para tecnología. Usar esta fuente como punto de entrada para cualquier pipeline bulk de Brasil.',
    limitations: [
      'Descarga ~4.7 GB comprimido / ~17 GB descomprimido — procesamiento batch offline obligatorio',
      'Acceso desde fuera de Brasil puede dar timeout; usar mirror: dados.gov.br o arquivos.receitafederal.gov.br',
      'No incluye datos de contacto (teléfono/email) en la mayoría de registros',
      'Licencia CC BY-ND 3.0 — no permite derivados; verificar uso comercial con legal antes de producción',
    ],
    riskNotes: [
      'Filtrar por situação cadastral: Ativa',
      'Verificar disponibilidad de mirror antes de procesar en producción',
    ],
  },
  {
    key: 'br_receita_cnpj',
    name: 'Receita Federal CNPJ (Referencia institucional)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'validation_only',
    type: 'official_registry',
    url: 'https://www.gov.br/receitafederal/',
    automationLevel: 'low',
    recommendedUse: 'Referencia institucional y validación puntual de CNPJ. No duplicar ingesta bulk si br_receita_dados_abertos está activa — esta fuente es complementaria para consultas individuales o verificación de registros específicos.',
    limitations: ['Sin descarga masiva directa desde el portal web', 'Datos de contacto mínimos en la fuente oficial'],
    riskNotes: ['No usar como pipeline de discovery masivo; usar br_receita_dados_abertos para ingesta bulk'],
  },
  {
    key: 'br_cnpj_ws',
    name: 'cnpj.ws (API tercero)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'connection_required',
    type: 'commercial_provider',
    url: 'https://www.cnpj.ws/',
    automationLevel: 'high',
    recommendedUse: 'API REST sobre datos CNPJ. Más conveniente que Receita Federal directa para integraciones.',
    limitations: ['Tercero no oficial sobre datos de Receita Federal'],
    riskNotes: ['Validar TOS y SLA antes de usar en producción'],
  },

  // ── Globales / Fallback ─────────────────────────────────────────────────────
  {
    key: 'global_opencorporates',
    name: 'OpenCorporates',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'connection_required',
    type: 'public_dataset',
    url: 'https://opencorporates.com/',
    automationLevel: 'medium',
    recommendedUse: 'Fallback global para países sin fuente P0. Cubre 130+ jurisdicciones con datos básicos de registro.',
    limitations: ['Cobertura desigual en LatAm', 'API requiere plan de pago para volumen', 'Datos pueden estar desactualizados'],
    riskNotes: [
      'Requiere plan/API de pago para volumen; no usar como fuente automática de discovery sin validación comercial y legal previa.',
    ],
  },
  {
    key: 'global_apollo',
    name: 'Apollo.io',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'connection_required',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Fallback pagado cuando fuentes públicas no alcanzan el objetivo de cantidad. Cobertura débil en LatAm vs USA.',
    limitations: ['Cobertura débil en LatAm', 'Datos de contacto con 25-40% de rebote esperado', 'Costo por crédito'],
    riskNotes: ['Solo usar como último recurso explícito autorizado', 'No usar como primera fuente de discovery'],
  },
  {
    key: 'global_lusha',
    name: 'Lusha',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'validation_only',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Enriquecimiento de datos de contacto (teléfono, email directo) bajo demanda ÚNICAMENTE.',
    limitations: ['Nunca usar para discovery de empresas', 'Solo enriquecimiento de contactos ya identificados'],
    riskNotes: ['Excluida de discovery — no aparece en recommendedSources'],
  },
];
