/**
 * Prospecting Toolkit — Catálogo estructurado de fuentes MVP.
 *
 * Contiene únicamente los países prioritarios del MVP: CO, MX, CL, PE, EC, BR.
 * Fuentes globales incluidas como fallback (OpenCorporates, Apollo).
 * Lusha: presente pero marcada como "no discovery" — filtrada en getCatalogContext.
 *
 * Principios:
 * - P0: fuente primaria oficial, alta confianza para el país
 * - P1: complementaria o de nicho, útil pero no suficiente sola
 * - P2: global o pagada, fallback de último recurso
 */

import type { CatalogSource } from './types';

// ─── Identificadores fiscales por país ────────────────────────────────────────

export const FISCAL_IDENTIFIERS: Record<string, string> = {
  AR: 'CUIT',
  BO: 'NIT',
  BR: 'CNPJ',
  CL: 'RUT',
  CO: 'NIT',
  CR: 'Cédula Jurídica',
  DO: 'RNC',
  EC: 'RUC',
  GT: 'NIT',
  HN: 'RTN',
  MX: 'RFC',
  NI: 'RUC',
  PA: 'RUC',
  PE: 'RUC',
  PY: 'RUC',
  SV: 'NRC/NIT',
  UY: 'RUT',
};

// ─── Riesgos conocidos por país ───────────────────────────────────────────────

export const COUNTRY_RISKS: Record<string, string[]> = {
  CO: [
    'SIIS/Supersociedades cubre principalmente empresas medianas/grandes; microempresas pueden no aparecer.',
    'RUES puede tener datos desactualizados en sectores informales.',
    'SECOP II solo cubre proveedores del Estado; no representa todo el mercado.',
    'No asumir que toda empresa registrada en RUES está activa.',
    'Validar NIT antes de presentar la empresa — errores de transcripción son frecuentes.',
  ],
  MX: [
    'DENUE API tiene límite de registros por consulta; paginar correctamente.',
    'SIEM puede tener datos con 1-2 años de antigüedad para PYMES.',
    'No todas las empresas tienen RFC público disponible via DENUE.',
    'Empresas del sector informal no aparecen en registros oficiales.',
    'CANAIVE/AMIA solo cubren sus sectores específicos.',
  ],
  CL: [
    'RES solo cubre empresas registradas activamente; algunas PYMES operan sin registro formal.',
    'ChileCompra solo cubre proveedores del Estado chileno.',
    'Datos de contacto en fuentes públicas chilenas son escasos.',
    'No confundir RUT de persona natural con RUT de empresa.',
    'SII proporciona validación fiscal pero no perfil de empresa completo.',
  ],
  PE: [
    'SUNAT Padrón RUC es la fuente más confiable pero solo contiene datos tributarios.',
    'SEACE/OSCE solo cubre proveedores de contrataciones del Estado.',
    'PRODUCE Manufactura solo cubre sector manufacturero.',
    'Alta informalidad en algunos sectores — registros incompletos.',
    'Verificar estado activo en SUNAT antes de prospectar.',
  ],
  EC: [
    'SCVS/Supercias cubre principalmente grandes empresas obligadas a reportar.',
    'SERCOP cubre solo proveedores del Estado ecuatoriano.',
    'Datos de contacto en fuentes oficiales ecuatorianas son muy limitados.',
    'Distinguir RUC de persona natural vs empresa antes de prospectar.',
  ],
  BR: [
    'CNPJ es la fuente más completa de LatAm pero puede incluir empresas inactivas.',
    'cnpj.ws es un tercero no oficial; validar disponibilidad y TOS antes de usar.',
    'Volumen masivo requiere filtrado cuidadoso por situação: Ativa.',
    'Datos de contacto en Receita Federal son mínimos.',
  ],
};

// ─── Reglas globales del agente ───────────────────────────────────────────────

export const GLOBAL_RULES: string[] = [
  'No usar Lusha para discovery; solo para enriquecimiento de contactos bajo demanda.',
  'Apollo solo como fallback explícito cuando fuentes públicas no alcanzan el objetivo.',
  'HubSpot duplicate check obligatorio antes de presentar empresa como nueva.',
  'No inventar website, LinkedIn, ni datos de contacto.',
  'Máximo 25 empresas candidatas por ejecución.',
  'Usar identificador fiscal del país como ancla de deduplicación cuando esté disponible.',
];

// ─── Catálogo de fuentes ──────────────────────────────────────────────────────

export const CATALOG_SOURCES: CatalogSource[] = [

  // ── Colombia ────────────────────────────────────────────────────────────────
  {
    key: 'co_siis',
    name: 'Supersociedades SIIS',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://siis.ia.supersociedades.gov.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de empresas medianas/grandes supervisadas. Datos societarios y financieros.',
    limitations: ['Solo empresas bajo supervisión de Supersociedades', 'No cubre microempresas'],
    riskNotes: ['Verificar estado activo/inactivo antes de prospectar'],
  },
  {
    key: 'co_datos_gov',
    name: 'datos.gov.co',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    type: 'public_dataset',
    url: 'https://www.datos.gov.co/',
    automationLevel: 'high',
    recommendedUse: 'Datasets públicos con señales empresariales. Varios sectores disponibles para descarga.',
    limitations: ['Calidad variable según dataset', 'Frecuencia de actualización irregular'],
  },
  {
    key: 'co_rues',
    name: 'RUES (Registro Único Empresarial)',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.rues.org.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery amplio por NIT. Cubre microempresas hasta grandes empresas registradas en Cámaras.',
    limitations: ['Sin API pública oficial', 'Consultas requieren nombre o NIT'],
    riskNotes: ['Datos pueden estar desactualizados para empresas pequeñas'],
  },
  {
    key: 'co_secop2',
    name: 'SECOP II (Compras Públicas)',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P1',
    type: 'procurement',
    url: 'https://www.secop.gov.co/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado. Señal de empresa activa con historial contractual B2G.',
    limitations: ['Solo empresas que venden al Estado colombiano'],
  },
  {
    key: 'co_minsalud_reps',
    name: 'MinSalud REPS',
    countryCodes: ['CO'],
    sectors: ['salud', 'health', 'farmaceutico', 'pharmaceutical', 'clinica', 'hospital', 'ips', 'eps', 'laboratorio'],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.reps.gov.co/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de prestadores de salud habilitados. Fuente primaria para discovery en sector salud colombiano.',
  },
  {
    key: 'co_superfinanciera',
    name: 'Superfinanciera Colombia',
    countryCodes: ['CO'],
    sectors: ['financiero', 'fintech', 'banca', 'banco', 'seguros', 'financial', 'banking', 'insurance', 'aseguradora'],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.superfinanciera.gov.co/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en sector financiero supervisado: bancos, aseguradoras, fiduciarias, fondos.',
  },

  // ── México ──────────────────────────────────────────────────────────────────
  {
    key: 'mx_denue',
    name: 'DENUE / INEGI API',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.inegi.org.mx/servicios/api_denue.html',
    automationLevel: 'high',
    recommendedUse: 'Discovery principal en México. API oficial con 5M+ establecimientos por municipio, clasificador SCIAN y tamaño.',
    limitations: ['Rate limits por token de acceso', 'RFC no incluido en respuesta de API'],
    riskNotes: ['Paginar correctamente', 'Actualización cada 1-2 años'],
  },
  {
    key: 'mx_siem',
    name: 'SIEM (Sistema de Información Empresarial Mexicano)',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    type: 'official_registry',
    url: 'http://www.siem.gob.mx/',
    automationLevel: 'medium',
    recommendedUse: 'Complemento a DENUE para PYMES con datos de contacto básicos. Registro con Cámara de Comercio.',
    limitations: ['Cobertura menor que DENUE', 'Sin API pública oficial'],
  },
  {
    key: 'mx_canaive',
    name: 'CANAIVE (Cámara Nacional de la Industria del Vestido)',
    countryCodes: ['MX'],
    sectors: ['textil', 'manufactura textil', 'moda', 'clothing', 'garment', 'apparel', 'textile', 'vestido', 'confeccion'],
    priority: 'P1',
    type: 'industry_association',
    url: 'https://www.canaive.org.mx/',
    automationLevel: 'manual',
    recommendedUse: 'Discovery en industria textil mexicana. Directorio de empresas afiliadas.',
    limitations: ['Solo afiliados a la cámara', 'Sin API — consulta manual'],
  },
  {
    key: 'mx_amia',
    name: 'AMIA (Asociación Mexicana de la Industria Automotriz)',
    countryCodes: ['MX'],
    sectors: ['automotriz', 'automotive', 'autopartes', 'auto parts', 'vehiculo', 'vehicle', 'manufactura automotriz'],
    priority: 'P1',
    type: 'industry_association',
    url: 'https://www.amia.com.mx/',
    automationLevel: 'manual',
    recommendedUse: 'Discovery en industria automotriz mexicana. OEMs y Tier-1.',
    limitations: ['Solo miembros asociados', 'Sin API — consulta directa'],
  },

  // ── Chile ───────────────────────────────────────────────────────────────────
  {
    key: 'cl_res',
    name: 'RES / datos.gob.cl',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://datos.gob.cl/',
    automationLevel: 'high',
    recommendedUse: 'Discovery principal en Chile. Portal de datos abiertos con datasets de empresas activas por sector.',
  },
  {
    key: 'cl_chilecompra',
    name: 'ChileCompra (Mercado Público)',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    type: 'procurement',
    url: 'https://www.mercadopublico.cl/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado chileno. API disponible. Señal de empresa activa con contratación B2G.',
    limitations: ['Solo empresas proveedoras del Estado'],
  },
  {
    key: 'cl_sence_otec',
    name: 'SENCE OTEC',
    countryCodes: ['CL'],
    sectors: ['capacitacion', 'educacion', 'training', 'hr', 'recursos humanos', 'capital humano', 'formacion'],
    priority: 'P1',
    type: 'official_registry',
    url: 'https://www.sence.cl/',
    automationLevel: 'medium',
    recommendedUse: 'Discovery de organismos técnicos de capacitación laboral en Chile.',
    limitations: ['Solo sector capacitación formal', 'Sin API pública'],
  },
  {
    key: 'cl_sii',
    name: 'SII Chile (Validación tributaria)',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    type: 'official_registry',
    url: 'https://www.sii.cl/',
    automationLevel: 'low',
    recommendedUse: 'Validación de RUT y estado tributario. No usar para discovery masivo.',
    limitations: ['Solo validación individual de RUT', 'No permite automatización masiva'],
    riskNotes: ['No confundir RUT de persona natural con empresa'],
  },

  // ── Perú ────────────────────────────────────────────────────────────────────
  {
    key: 'pe_sunat',
    name: 'SUNAT Padrón RUC',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://e-consultaruc.sunat.gob.pe/',
    automationLevel: 'medium',
    recommendedUse: 'Fuente principal en Perú. Padrón RUC con razón social, estado activo, actividad CIIU.',
    limitations: ['Sin API oficial para consulta masiva', 'Solo datos tributarios básicos'],
    riskNotes: ['Verificar estado: Activo antes de prospectar'],
  },
  {
    key: 'pe_seace',
    name: 'OSCE / SEACE (Contrataciones del Estado)',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P1',
    type: 'procurement',
    url: 'https://www.seace.gob.pe/',
    automationLevel: 'high',
    recommendedUse: 'Discovery de proveedores del Estado peruano. Señal de empresa activa con historial B2G.',
    limitations: ['Solo empresas que contratan con el Estado'],
  },
  {
    key: 'pe_produce',
    name: 'PRODUCE Manufactura',
    countryCodes: ['PE'],
    sectors: ['manufactura', 'manufacturing', 'industria', 'industrial', 'produccion', 'production', 'planta'],
    priority: 'P1',
    type: 'public_dataset',
    url: 'https://www.gob.pe/produce',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en sector manufactura peruano. Padrones y estadísticas de empresas manufactureras.',
    limitations: ['Solo sector manufactura'],
  },

  // ── Ecuador ─────────────────────────────────────────────────────────────────
  {
    key: 'ec_scvs',
    name: 'SCVS / Supercias Ecuador',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.supercias.gob.ec/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de compañías ecuatorianas. Razón social, objeto social, representante legal.',
    limitations: ['Solo empresas obligadas a reportar a Supercias', 'Excluye microempresas'],
  },
  {
    key: 'ec_sercop',
    name: 'SERCOP (Compras Públicas Ecuador)',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P1',
    type: 'procurement',
    url: 'https://www.sercop.gob.ec/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado ecuatoriano. Señal de empresa activa.',
    limitations: ['Solo empresas contratistas del Estado'],
  },

  // ── Brasil ──────────────────────────────────────────────────────────────────
  {
    key: 'br_receita_cnpj',
    name: 'Receita Federal CNPJ',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P0',
    type: 'official_registry',
    url: 'https://www.gov.br/receitafederal/',
    automationLevel: 'high',
    recommendedUse: 'Fuente más completa de LatAm. CNPJ, razón social, CNAE, municipio. Datos de empresas de todo tamaño.',
    limitations: ['Datos de contacto mínimos en la fuente oficial'],
    riskNotes: ['Filtrar por situação cadastral: Ativa'],
  },
  {
    key: 'br_cnpj_ws',
    name: 'cnpj.ws (API tercero)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P1',
    type: 'commercial_provider',
    url: 'https://www.cnpj.ws/',
    automationLevel: 'high',
    recommendedUse: 'API REST sobre datos CNPJ. Más conveniente que Receita Federal directa para integraciones.',
    limitations: ['Tercero no oficial sobre datos de Receita Federal'],
    riskNotes: ['Validar TOS y SLA antes de usar en producción'],
  },

  // ── Globales / Fallback ─────────────────────────────────────────────────────
  {
    key: 'global_opencorporates',
    name: 'OpenCorporates',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    type: 'public_dataset',
    url: 'https://opencorporates.com/',
    automationLevel: 'medium',
    recommendedUse: 'Fallback global para países sin fuente P0. Cubre 130+ jurisdicciones con datos básicos de registro.',
    limitations: ['Cobertura desigual en LatAm', 'API requiere plan de pago para volumen', 'Datos pueden estar desactualizados'],
  },
  {
    key: 'global_apollo',
    name: 'Apollo.io',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Fallback pagado cuando fuentes públicas no alcanzan el objetivo de cantidad. Cobertura débil en LatAm vs USA.',
    limitations: ['Cobertura débil en LatAm', 'Datos de contacto con 25-40% de rebote esperado', 'Costo por crédito'],
    riskNotes: ['Solo usar como último recurso explícito autorizado', 'No usar como primera fuente de discovery'],
  },
  {
    key: 'global_lusha',
    name: 'Lusha',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Enriquecimiento de datos de contacto (teléfono, email directo) bajo demanda ÚNICAMENTE.',
    limitations: ['Nunca usar para discovery de empresas', 'Solo enriquecimiento de contactos ya identificados'],
    riskNotes: ['Excluida de discovery — no aparece en recommendedSources'],
  },
];
