/**
 * Prospecting Toolkit — Catálogo estructurado de fuentes MVP.
 *
 * Contiene únicamente los países prioritarios del MVP: CO, MX, CL, PE, EC, BR.
 * Fuentes globales incluidas como fallback (OpenCorporates, Apollo).
 * Lusha: presente pero marcada como "no discovery" — filtrada en getCatalogContext.
 *
 * Principios:
 * - P0: fuente primaria oficial, alta confianza para el país
 * - P1: complementaria o de nicho, útil pero no suficiente sola
 * - P2: global o pagada, fallback de último recurso
 */

import type { CatalogSource } from './types';

// ─── Identificadores fiscales por país ────────────────────────────────────────

export const FISCAL_IDENTIFIERS: Record<string, string> = {
  AR: 'CUIT',
  BO: 'NIT',
  BR: 'CNPJ',
  CL: 'RUT',
  CO: 'NIT',
  CR: 'Cédula Jurídica',
  DO: 'RNC',
  EC: 'RUC',
  GT: 'NIT',
  HN: 'RTN',
  MX: 'RFC',
  NI: 'RUC',
  PA: 'RUC',
  PE: 'RUC',
  PY: 'RUC',
  SV: 'NRC/NIT',
  UY: 'RUT',
};

// ─── Riesgos conocidos por país ───────────────────────────────────────────────

export const COUNTRY_RISKS: Record<string, string[]> = {
  CO: [
    'SIIS/Supersociedades cubre principalmente empresas medianas/grandes; microempresas pueden no aparecer.',
    'RUES puede tener datos desactualizados en sectores informales.',
    'SECOP II solo cubre proveedores del Estado; no representa todo el mercado.',
    'No asumir que toda empresa registrada en RUES está activa.',
    'Validar NIT antes de presentar la empresa — errores de transcripción son frecuentes.',
  ],
  MX: [
    'DENUE API tiene límite de registros por consulta; paginar correctamente.',
    'SIEM puede tener datos con 1-2 años de antigüedad para PYMES.',
    'No todas las empresas tienen RFC público disponible via DENUE.',
    'Empresas del sector informal no aparecen en registros oficiales.',
    'CANAIVE/AMIA solo cubren sus sectores específicos.',
  ],
  CL: [
    'RES solo cubre empresas registradas activamente; algunas PYMES operan sin registro formal.',
    'ChileCompra (descartado MVP) solo cubre proveedores del Estado chileno.',
    'Datos de contacto en fuentes públicas chilenas son escasos.',
    'No confundir RUT de persona natural con RUT de empresa.',
    'SII proporciona validación fiscal pero no perfil de empresa completo.',
  ],
  PE: [
    'SUNAT Padrón RUC es la fuente más confiable pero solo contiene datos tributarios.',
    'SEACE/OSCE solo cubre proveedores de contrataciones del Estado.',
    'PRODUCE Manufactura solo cubre sector manufacturero.',
    'Alta informalidad en algunos sectores — registros incompletos.',
    'Verificar estado activo en SUNAT antes de prospectar.',
  ],
  EC: [
    'SCVS/Supercias cubre principalmente grandes empresas obligadas a reportar.',
    'SERCOP cubre solo proveedores del Estado ecuatoriano.',
    'Datos de contacto en fuentes oficiales ecuatorianas son muy limitados.',
    'Distinguir RUC de persona natural vs empresa antes de prospectar.',
  ],
  BR: [
    'CNPJ es la fuente más completa de LatAm pero puede incluir empresas inactivas.',
    'cnpj.ws es un tercero no oficial; validar disponibilidad y TOS antes de usar.',
    'Volumen masivo requiere filtrado cuidadoso por situação: Ativa.',
    'Datos de contacto en Receita Federal son mínimos.',
  ],
};

// ─── Reglas globales del agente ───────────────────────────────────────────────

export const GLOBAL_RULES: string[] = [
  'No usar Lusha para discovery; solo para enriquecimiento de contactos bajo demanda.',
  'Apollo solo como fallback explícito cuando fuentes públicas no alcanzan el objetivo.',
  'HubSpot duplicate check obligatorio antes de presentar empresa como nueva.',
  'No inventar website, LinkedIn, ni datos de contacto.',
  'Máximo 25 empresas candidatas por ejecución.',
  'Usar identificador fiscal del país como ancla de deduplicación cuando esté disponible.',
];

// ─── Catálogo de fuentes ──────────────────────────────────────────────────────

export const CATALOG_SOURCES: CatalogSource[] = [

  // ── Colombia ────────────────────────────────────────────────────────────────
  {
    key: 'co_siis',
    name: 'Supersociedades SIIS',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected',
    connectionMode: 'automatic_enrichment',
    nextAction: 'Snapshot SIIS 2024 cargado con 10.000 registros. Monitorear actualización anual y recargar snapshot cuando SIIS publique nuevo año.',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://siis.ia.supersociedades.gov.co/',
    automationLevel: 'high',
    recommendedUse:
      'Enriquecimiento financiero post-discovery y priorización de candidatos colombianos medianos/grandes. Señales financieras (ingresos, utilidades, activos, patrimonio) y validación parcial por NIT para empresas reportadas en SIIS. Fuente ya disponible vía snapshot SIIS 2024 cargado en Supabase con 10.000 registros. NO usar como fuente de discovery principal ni como fuente universal — no cubre microempresas ni empresas no vigiladas por Supersociedades.',
    limitations: [
      'Cobertura limitada a empresas reportadas o supervisadas por Supersociedades — no representa todo el universo empresarial colombiano',
      'No cubre microempresas ni empresas no vigiladas',
      'Datos con rezago de 1-2 años respecto al ejercicio fiscal',
      'No incluye datos de contacto (emails, teléfonos)',
      'No reemplaza RUES para discovery amplio',
      'No debe consultarse live en el wizard — usa snapshot controlado en Supabase',
      'Requiere recarga anual o manual cuando SIIS publique nuevo Excel',
    ],
    riskNotes: [
      'Usar como complemento post-discovery, no como única fuente de validación',
      'Evitar usar como única fuente — combinar con RUES para cobertura amplia',
      'No consultar Excel de SIIS en cada búsqueda — usar snapshot controlado en Supabase',
      'Snapshot 2024 cargado exitosamente (10.000 registros) — monitorear actualización anual',
    ],
  },
  {
    key: 'co_datos_gov',
    name: 'datos.gov.co',
    sellupUse: 'technical_container',
    aiFlowStatus: 'not_applicable',
    connectionMode: 'not_applicable',
    nextAction: 'No mostrar como fuente directa del wizard',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'public_dataset',
    url: 'https://www.datos.gov.co/',
    automationLevel: 'low',
    recommendedUse:
      'Proveedor técnico de datasets públicos de Colombia sobre Socrata/SODA. No debe usarse como fuente monolítica de discovery; las capacidades operativas deben implementarse mediante datasets específicos validados.',
    limitations: [
      'Portal heterogéneo con miles de datasets; la calidad depende de cada dataset.',
      'No usar como fuente genérica de prospectos.',
      'Cada dataset requiere validación individual de cobertura, columnas, actualización y filtros.',
      'Algunos datasets son regionales, desactualizados o no empresariales.',
      'Usar subfuentes específicas para discovery, enriquecimiento, validación o señales.',
    ],
    riskNotes: [
      'Riesgo crítico: tratar datos.gov.co como fuente única puede producir resultados caóticos.',
      'Se deben separar datasets operativos con source_key propio.',
      'Validar estado, cobertura y fecha de actualización por dataset.',
      'En datasets de empresas, filtrar registros activos cuando aplique.',
    ],
  },
  {
    key: 'co_personas_juridicas_cc',
    name: 'Personas Jurídicas Cámaras de Comercio',
    sellupUse: 'legal_validation',
    aiFlowStatus: 'connected',
    connectionMode: 'automatic_enrichment',
    nextAction: 'Conectada a enrichment por NIT',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.datos.gov.co/resource/c82u-588k.json',
    automationLevel: 'high',
    recommendedUse:
      'Discovery secundario y validación parcial de personas jurídicas publicadas por cámaras de comercio en datos.gov.co. Útil para verificar NIT, razón social, estado de matrícula, CIIU y renovación.',
    limitations: [
      'Cobertura parcial: solo cámaras que publican en datos.gov.co.',
      'No reemplaza RUES como fuente principal nacional.',
      'Puede mezclar registros activos y cancelados; requiere filtrar estado_matricula = ACTIVA.',
      'No debe usarse como discovery universal de Colombia.',
    ],
    riskNotes: [
      'Validar cobertura por cámara antes de usar como fuente nacional.',
      'Usar como complemento de RUES y otras fuentes oficiales.',
      'Requiere normalización de NIT, razón social y estado de matrícula.',
      'Endpoint Socrata validado: https://www.datos.gov.co/resource/c82u-588k.json',
    ],
  },
  {
    key: 'co_secop2_proveedores',
    name: 'SECOP II Proveedores Registrados',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'connected',
    connectionMode: 'automatic_enrichment',
    nextAction: 'Conectada a enrichment B2G por NIT',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.datos.gov.co/resource/qmzu-gj57.json',
    automationLevel: 'high',
    recommendedUse:
      'Señal comercial B2G y enriquecimiento de empresas registradas como proveedoras del Estado. Útil para identificar empresas activas en contratación pública, datos de contacto, categoría principal, tipo de empresa y representante legal.',
    limitations: [
      'No es fuente de discovery universal.',
      'Solo cubre empresas registradas como proveedoras del Estado.',
      'Debe filtrarse esta_activa cuando aplique.',
      'Puede solaparse con co_secop2, que representa compras públicas/contratos.',
    ],
    riskNotes: [
      'Usar como señal comercial post-discovery, no como única fuente de prospección.',
      'Complementa co_secop2: proveedores registrados vs procesos/contratos.',
      'Endpoint Socrata validado: https://www.datos.gov.co/resource/qmzu-gj57.json',
    ],
  },
  {
    key: 'co_rues',
    name: 'RUES (Registro Único Empresarial)',
    sellupUse: 'legal_validation',
    aiFlowStatus: 'connected',
    connectionMode: 'wizard_discovery',
    nextAction: 'Mantener como fuente estructurada legal parcial',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.rues.org.co/',
    automationLevel: 'high',
    recommendedUse:
      'Fuente oficial de referencia para validación legal y discovery empresarial en Colombia. En SellUp el canal automático actual usa el dataset Socrata c82u-588k publicado en datos.gov.co, útil para discovery inicial, validación parcial de NIT, matrícula mercantil, estado de matrícula, cámara de comercio, CIIU y fechas de renovación.',
    limitations: [
      'El canal automático actual no representa el RUES nacional completo.',
      'El dataset Socrata c82u-588k tiene cobertura parcial según las cámaras que publican datos.',
      'No reemplaza una consulta nacional completa o convenio oficial con RUES/Confecámaras.',
      'No incluye datos comerciales completos como teléfono, email, sitio web o decisores.',
      'La consulta directa a rues.org.co puede requerir interacción de navegador/captcha y no debe automatizarse mediante scraping.',
      'Puede requerir deduplicación por NIT si en el futuro se incorporan datasets de múltiples cámaras.',
    ],
    riskNotes: [
      'Riesgo principal: asumir cobertura nacional completa cuando el canal automático actual es parcial.',
      'Usar el canal Socrata para discovery controlado y validación parcial, no como única prueba legal definitiva.',
      'Mantener rues.org.co como referencia manual/oficial, no como canal de scraping.',
      'Endpoint automático actual: https://www.datos.gov.co/resource/c82u-588k.json',
      'Dataset relacionado también usado por co_personas_juridicas_cc para enriquecimiento post-discovery por NIT.',
    ],
  },
  {
    key: 'co_secop2',
    name: 'SECOP II (Compras Públicas)',
    sellupUse: 'not_for_ai_flow',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Usar solo como referencia contextual. Para enrichment automático usar co_secop2_proveedores.',
    countryCodes: ['CO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'procurement',
    url: 'https://www.secop.gov.co/',
    automationLevel: 'low',
    recommendedUse: 'Señal contextual de contratación pública / mercado B2G. No usar como adapter automático. Para proveedor registrado usar co_secop2_proveedores. No duplicar lógica.',
    limitations: [
      'No tiene adapter propio.',
      'Puede confundirse con co_secop2_proveedores.',
      'No debe entrar al flujo automático del Agente 1.',
      'Solo empresas que venden al Estado colombiano.',
    ],
    riskNotes: [
      'No usar como fuente automática de discovery ni enrichment.',
      'Para proveedor registrado y datos estructurados de contratación, usar co_secop2_proveedores.',
      'Mantener co_secop2 como señal contextual, no como adapter operativo.',
    ],
  },
  {
    key: 'co_minsalud_reps',
    name: 'MinSalud REPS',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected',
    connectionMode: 'automatic_enrichment',
    nextAction: 'Conectada a enrichment salud por NIT',
    countryCodes: ['CO'],
    sectors: ['salud', 'health', 'farmaceutico', 'pharmaceutical', 'clinica', 'hospital', 'ips', 'eps', 'laboratorio'],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.reps.gov.co/',
    automationLevel: 'high',
    recommendedUse:
      'Fuente P0 para sector salud: discovery sectorial y validación/enriquecimiento de prestadores habilitados. Dataset Socrata REPS validado (c36g-9fc2) con NIT, razón social, naturaleza jurídica, clase prestador, departamento, municipio, dirección, teléfono, email, sede, código habilitación.',
    limitations: ['Solo sector salud — no multisectorial.'],
    riskNotes: [
      'Endpoint Socrata validado: https://www.datos.gov.co/resource/c36g-9fc2.json',
      'Validar cobertura y actualización antes de uso en producción.',
    ],
  },
  {
    key: 'co_superfinanciera',
    name: 'Superfinanciera Colombia',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected',
    connectionMode: 'automatic_enrichment',
    nextAction: 'Conectada a enrichment financiero por NIT',
    countryCodes: ['CO'],
    sectors: ['financiero', 'fintech', 'banca', 'banco', 'seguros', 'financial', 'banking', 'insurance', 'aseguradora'],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.superfinanciera.gov.co/',
    automationLevel: 'high',
    recommendedUse:
      'Fuente P0 para sector financiero supervisado: bancos, aseguradoras, fiduciarias, fondos. Dataset Socrata validado (sr9n-792w) para entidades vigiladas con NIT, razón social, tipo entidad, ciudad, dirección, email, web, representante legal.',
    limitations: ['Solo sector financiero regulado — no multisectorial.'],
    riskNotes: [
      'Endpoint Socrata validado: https://www.datos.gov.co/resource/sr9n-792w.json',
      'Validar cobertura y actualización antes de uso en producción.',
    ],
  },

  // ── Colombia — Innovación / Emprendimiento ──────────────────────────────────
  {
    key: 'co_innpulsa',
    name: 'iNNpulsa Colombia (MinComercio)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual innovación',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'innovacion', 'startups', 'emprendimiento', 'technology', 'innovation', 'startup_ecosystem'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'other',
    url: 'https://www.innpulsacolombia.com/',
    automationLevel: 'manual',
    recommendedUse:
      'Señal comercial cualitativa para identificar empresas innovadoras, startups, emprendimientos o beneficiarias de programas públicos de innovación/emprendimiento. Útil como contexto comercial y priorización manual, no como fuente automática de discovery o validación legal.',
    limitations: [
      'No tiene API pública de empresas.',
      'No existe dataset público estructurado en datos.gov.co validado para beneficiarios iNNpulsa.',
      'No tiene directorio público estable de empresas beneficiarias.',
      'No sirve para discovery principal ni validación legal/NIT.',
      'La información pública está dispersa en convocatorias, PDFs, noticias o páginas institucionales.',
      'La cobertura es acotada a programas específicos y puede estar desactualizada.',
    ],
    riskNotes: [
      'No automatizar extracción desde el sitio institucional ni paneles internos.',
      'Mantener como señal manual hasta contar con API, dataset público o acceso formal autorizado.',
      'Los datos de beneficiarios pueden estar incompletos, no estandarizados o sin clasificación sectorial.',
      'No usar como fuente de creación masiva de prospectos.',
      'Reevaluar si iNNpulsa publica datasets estructurados o acceso oficial.',
    ],
  },

  // ── Colombia — Tecnología (Hito 16Y.1) ─────────────────────────────────────
  {
    key: 'co_fedesoft',
    name: 'Fedesoft (Federación Colombiana de Software y TI)',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'paused',
    connectionMode: 'not_connected',
    nextAction: 'Pausada por bloqueo upstream (captcha/protección SiteGround). No debe correr automáticamente hasta tener snapshot cargado o ruta estable.',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'software', 'tic', 'servicios_ti', 'technology', 'software_development', 'it_services'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.fedesoft.org/',
    automationLevel: 'low',
    recommendedUse: 'Señal sectorial tech / software Colombia. Útil como fuente futura o contextual. No usar automáticamente en wizard mientras upstream esté bloqueado. Requiere snapshot controlado o archivo manual verificable antes de reactivar.',
    limitations: [
      'Upstream bloquea carga automática desde Node por captcha/protección SiteGround.',
      'No depender de consulta live.',
      'No marcar como connected hasta tener snapshot cargado o alternativa estable.',
      'Cobertura acotada a empresas afiliadas a Fedesoft; no representa todo el universo de empresas TI en Colombia.',
      'No reemplaza RUES ni co_personas_juridicas_cc para validación legal/NIT.',
    ],
    riskNotes: [
      'No usar como live dependency del wizard — la carga se pausa si Fedesoft responde con captcha/protección SiteGround.',
      'Usar exclusivamente snapshot controlado si se reactiva; no consultar en vivo contra el upstream.',
      'Conector REST y ETL snapshot existen, pero el bloqueo actual es upstream (captcha), no falta de desarrollo.',
      'Puede usarse como señal contextual si se obtiene data manualmente.',
      'Reevaluar cuando SiteGround deje de bloquear o se tenga acceso alternativo autorizado.',
    ],
  },
  {
    key: 'co_colombia_fintech',
    name: 'Colombia Fintech (Asociación Fintech de Colombia)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual fintech',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'fintech', 'financiero', 'pagos', 'technology', 'payments', 'financial_technology'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.colombiafintech.co/',
    automationLevel: 'low',
    recommendedUse:
      'Señal sectorial manual para identificar empresas vinculadas al ecosistema fintech colombiano. Útil como contexto comercial y priorización cualitativa cuando una empresa ya fue identificada por fuentes con NIT, como RUES, cámaras o Superfinanciera. No debe usarse como fuente automática de discovery ni como validación legal.',
    limitations: [
      'No expone NIT en el directorio público ni en la API REST disponible.',
      'No permite validación legal ni deduplicación fiscal confiable.',
      'La API REST WordPress es parcial y no expone todos los campos útiles como ciudad, website, vertical o contacto.',
      'Parte del contenido de perfiles puede estar protegido por login.',
      'No representa todo el universo fintech colombiano; cubre principalmente miembros afiliados.',
      'No debe usarse como fuente automática de creación masiva de prospectos.',
    ],
    riskNotes: [
      'Riesgo principal: sin NIT no hay anclaje confiable contra RUES, cámaras o Superfinanciera.',
      'No automatizar extracción por HTML mientras no exista dataset estructurado o API completa.',
      'Mantener como señal manual/gremial hasta contar con una fuente pública con NIT.',
      'Evitar tratar todos los miembros como fintechs puras; algunos pueden ser consultoras, aliados, universidades u otros actores de cadena de valor.',
      'Reevaluar si Colombia Fintech publica dataset abierto, descarga estructurada o API con NIT y verticales.',
      'Preservar gating fintech actual en query-builder si existe, pero no ampliar automatización.',
    ],
  },
  {
    key: 'co_colombia_digital',
    name: 'Colombia Digital',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: referencia editorial TIC',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'transformacion_digital', 'tic', 'technology', 'digital_transformation', 'ict'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.colombiadigital.net/',
    automationLevel: 'manual',
    recommendedUse: 'Referencia editorial/manual sobre transformación digital y ecosistema TIC colombiano. Puede servir como contexto sectorial cualitativo, pero no como fuente de discovery, validación legal, enriquecimiento automático o creación de prospectos.',
    limitations: [
      'No es un directorio de empresas.',
      'No expone NIT ni identificadores legales de terceros.',
      'No tiene API pública ni descarga estructurada para empresas.',
      'No sirve para discovery ni validación legal.',
      'Los casos públicos disponibles son pocos y principalmente de entidades públicas.',
      'El contenido es principalmente editorial, institucional o de casos de éxito.',
    ],
    riskNotes: [
      'Riesgo principal: confundir Colombia Digital con un directorio del ecosistema digital cuando en realidad no publica una base empresarial estructurada.',
      'No automatizar extracción desde contenido editorial.',
      'No usar como fuente de creación masiva de prospectos.',
      'Mantener solo como referencia manual de contexto TIC.',
      'El dominio colombiadigital.net debe seguir bloqueado como candidato empresarial en filtros pre-LLM.',
      'Reevaluar únicamente si se publica un dataset estructurado, API oficial o directorio con NIT.',
    ],
  },
  {
    key: 'co_andicom',
    name: 'ANDICOM (Congreso TIC Colombia / CINTEL)',
    sellupUse: 'contextual_signal',
    aiFlowStatus: 'source_guided',
    connectionMode: 'source_guided_query',
    nextAction: 'Mantener solo como señal contextual Tavily',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'telecomunicaciones', 'software', 'servicios_ti', 'technology', 'telecommunications', 'ict'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.andicom.co/',
    automationLevel: 'low',
    recommendedUse: 'Señal contextual de búsqueda para identificar empresas visibles en el ecosistema TIC colombiano a través de sponsors, expositores o participación en ANDICOM/CINTEL. Útil para source-guided queries de tecnología en Colombia, pero no como fuente estructurada de discovery, validación legal, enrichment automático o creación de prospectos.',
    limitations: [
      'No expone NIT ni identificadores legales de empresas.',
      'No tiene API pública ni descarga estructurada de sponsors/expositores.',
      'La información disponible depende de la edición anual del evento y puede cambiar.',
      'Los listados públicos son principalmente logos, nombres comerciales y enlaces web.',
      'Puede incluir multinacionales, entidades públicas, gremios, speakers o aliados que no son prospectos colombianos directos.',
      'No debe usarse como fuente única de discovery ni como validación legal.',
    ],
    riskNotes: [
      'Riesgo principal: sin NIT no hay anclaje fiscal ni deduplicación confiable contra RUES, cámaras o SIIS.',
      'Mantener únicamente como señal contextual para búsquedas web guiadas.',
      'No desarrollar pipeline estructurado mientras no exista API, dataset o listado con NIT.',
      'Evitar scraping agresivo de HTML, imágenes o logos del evento.',
      'Preservar filtros para que andicom.co y CINTEL no aparezcan como empresas candidatas.',
      'Reevaluar solo si ANDICOM/CINTEL publica un listado estructurado con NIT, razón social y año de participación.',
    ],
  },
  {
    key: 'co_ruta_n',
    name: 'Ruta N (Ecosistema Innovación Medellín)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual Medellín/startups',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'innovacion', 'startups', 'software', 'technology', 'innovation', 'startup_ecosystem'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'other',
    url: 'https://www.rutanmedellin.org/',
    automationLevel: 'manual',
    recommendedUse: 'Señal manual cualitativa para identificar startups, empresas innovadoras o actores relacionados con el ecosistema Ruta N en Medellín/Antioquia. Puede servir como contexto comercial local, pero no como fuente automática de discovery, validación legal, enrichment o creación de prospectos.',
    limitations: [
      'No tiene API pública ni dataset estructurado de empresas.',
      'No expone NIT ni identificadores legales.',
      'No existe directorio público empresarial consumible automáticamente.',
      'La información útil suele estar en noticias, convocatorias, logos o contenido editorial no estructurado.',
      'StartIA requiere login y no ofrece API pública validada.',
      'Cobertura limitada a Medellín/Antioquia y a programas puntuales.',
    ],
    riskNotes: [
      'Riesgo principal: sin NIT no hay anclaje fiscal ni deduplicación confiable contra RUES, cámaras o SIIS.',
      'No automatizar scraping de noticias, logos o contenido editorial.',
      'No usar como fuente de creación masiva de prospectos.',
      'Mantener solo como señal manual/local de innovación.',
      'Preservar el bloqueo de rutanmedellin.org como candidato empresarial.',
      'Reevaluar únicamente si Ruta N, StartIA o Alcaldía de Medellín publican API pública, dataset estructurado o directorio con NIT.',
    ],
  },
  {
    key: 'co_microsoft_partners',
    name: 'Microsoft Partner Directory Colombia',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Post-MVP: posible enrichment manual cloud',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'cloud', 'software', 'integradores', 'technology', 'cloud_computing', 'it_services', 'enterprise_software'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'commercial_provider',
    url: 'https://www.microsoft.com/en-us/solution-providers/home',
    automationLevel: 'low',
    recommendedUse:
      'Señal sectorial/manual para identificar empresas tecnológicas o integradores relacionados con el ecosistema Microsoft en Colombia. Puede servir como enriquecimiento futuro post-discovery para candidatos ya identificados por fuentes con NIT, agregando contexto de partner Microsoft, soluciones cloud, designaciones o especializaciones. No debe usarse como fuente automática de discovery, validación legal ni creación de prospectos.',
    limitations: [
      'No expone NIT/RUT ni identificadores legales.',
      'No expone razón social legal.',
      'No tiene API pública estable ni descarga estructurada del directorio.',
      'La fuente pública funciona como React SPA y no debe consumirse mediante scraping frágil.',
      'Puede incluir partners multinacionales o empresas que atienden Colombia sin ser empresas colombianas.',
      'No permite deduplicación fiscal confiable contra RUES, cámaras, SIIS o SECOP.',
    ],
    riskNotes: [
      'Riesgo principal: sin NIT no hay anclaje fiscal ni deduplicación confiable.',
      'No usar como fuente de discovery automático ni como source-guided query independiente.',
      'No desarrollar conector mientras no exista API pública, dataset estructurado o acceso formal autorizado.',
      'Evitar scraping de la React SPA o endpoints internos no documentados.',
      'Usar solo como señal/enrichment futuro post-discovery por matching conservador nombre+ciudad.',
      'Patrón similar a AWS Partners: útil como señal cloud, débil como fuente de datos.',
    ],
  },
  {
    key: 'co_aws_partners',
    name: 'AWS Partner Network Colombia',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Post-MVP: posible enrichment manual cloud',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'cloud', 'infraestructura_ti', 'technology', 'cloud_computing', 'infrastructure', 'devops'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'commercial_provider',
    url: 'https://partners.amazonaws.com/',
    automationLevel: 'low',
    recommendedUse: 'Señal sectorial/manual para identificar empresas tecnológicas o integradores relacionados con el ecosistema AWS en Colombia. Puede servir como enriquecimiento futuro post-discovery para candidatos ya identificados por fuentes con NIT, agregando contexto de partner AWS, competencias, tier, certificaciones o especializaciones cloud. No debe usarse como fuente automática de discovery, validación legal ni creación de prospectos.',
    limitations: [
      'No expone NIT/RUT ni identificadores legales.',
      'No expone razón social legal.',
      'No tiene API pública oficial/documentada ni descarga estructurada para uso productivo.',
      'La fuente pública depende de una SPA y endpoints internos no garantizados.',
      'Puede incluir multinacionales o partners que atienden Colombia sin ser empresas colombianas.',
      'No permite deduplicación fiscal confiable contra RUES, cámaras, SIIS o SECOP.',
    ],
    riskNotes: [
      'Riesgo principal: sin NIT no hay anclaje fiscal ni deduplicación confiable.',
      'No usar como fuente de discovery automático ni como source-guided query independiente.',
      'No desarrollar conector mientras no exista API pública, dataset estructurado o acceso formal autorizado.',
      'Evitar scraping o dependencia productiva de endpoints internos no documentados de AWS.',
      'Usar solo como señal/enrichment futuro post-discovery mediante matching conservador por nombre, website o ciudad.',
      'Patrón similar a Microsoft Partners: útil como señal cloud, débil como fuente de datos.',
    ],
  },
  {
    key: 'co_getonboard',
    name: 'GetOnBoard Colombia',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual hiring tech',
    countryCodes: ['CO'],
    sectors: ['tecnologia', 'software', 'startups', 'talento_tech', 'technology', 'software_development', 'tech_talent'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'other',
    url: 'https://www.getonbrd.com/',
    automationLevel: 'low',
    recommendedUse: 'Identificar empleadores tech activos en Colombia a través de vacantes publicadas. Señal indirecta de empresa tech con capacidad de contratación.',
    limitations: ['Señal de actividad laboral, no directorio formal de empresas', 'Cobertura limitada a empresas que publican en la plataforma'],
  },

  // ── México ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_denue',
    name: 'DENUE / INEGI API',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected',
    connectionMode: 'wizard_discovery',
    nextAction: 'Conectada en wizard discovery y enriquecimiento post-approval contextual (México.2B). No valida RFC. source_type=official_business_directory. legal_validation_status=not_applicable. tax_validation_status=not_applicable. human_review_required siempre.',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://www.inegi.org.mx/servicios/api_denue.html',
    automationLevel: 'high',
    recommendedUse:
      'Fuente oficial INEGI con 5M+ establecimientos. Sirve para discovery estructurado por municipio/SCIAN/tamaño y enrichment contextual de candidatos mexicanos. Ayuda a validar la existencia de establecimientos físicos. No entrega RFC ni resuelve identidad fiscal — la resolución de RFC requiere revisión humana.',
    limitations: [
      'No incluye RFC en la respuesta de API — no resuelve identidad fiscal.',
      'Es registro de establecimiento físico, no necesariamente la razón social fiscal.',
      'Puede devolver múltiples establecimientos para una misma marca o grupo empresarial.',
      'Datos con actualización cada 1-2 años — puede incluir establecimientos ya cerrados.',
      'Requiere token de acceso INEGI con rate limit por consulta.',
    ],
    riskNotes: [
      'No usar como fuente fiscal — no escribe tax_identifier.',
      'No enviar a HubSpot como RFC validado bajo ninguna circunstancia.',
      'Usar solo como contexto estructurado para revisión humana posterior.',
      'Mantener tax_identifier_resolution.status = not_resolvable_automatically para México.',
    ],
  },
  {
    key: 'mx_datos_gob',
    name: 'datos.gob.mx (Portal Datos Abiertos México)',
    sellupUse: 'technical_container',
    aiFlowStatus: 'not_applicable',
    connectionMode: 'not_applicable',
    nextAction: 'No mostrar como fuente directa del wizard. Si aparece un dataset útil, crear subfuente específica con su propia key.',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'public_dataset',
    url: 'https://datos.gob.mx/',
    automationLevel: 'low',
    recommendedUse:
      'Portal agregador de datasets públicos mexicanos. No usar como fuente directa del wizard — es un contenedor técnico. Si se identifica un dataset útil (DENUE histórico, SIEM, sectorial), crear una subfuente específica con su propia key y validación individual.',
    limitations: [
      'No es un dataset único — agrega miles de datasets con calidad variable.',
      'No hay dataset RFC empresarial útil para MVP.',
      'Cada dataset requiere validación individual de cobertura, columnas, fecha de actualización y filtros.',
      'Algunos datasets son regionales, desactualizados o no empresariales.',
    ],
    riskNotes: [
      'No tratar como fuente directa de discovery — puede producir resultados caóticos si se usa sin validación.',
      'Validar estado, cobertura y fecha de actualización por dataset antes de crear subfuente.',
    ],
  },
  {
    key: 'mx_siem',
    name: 'SIEM (Sistema de Información Empresarial Mexicano)',
    sellupUse: 'not_for_ai_flow',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Solo referencia manual. No automatizar en MVP. Sin API pública usable.',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'official_registry',
    url: 'http://www.siem.gob.mx/',
    automationLevel: 'manual',
    recommendedUse:
      'Solo referencia manual si el equipo comercial necesita consultarlo. No automatizar en MVP. Registro con Cámara de Comercio para PYMES.',
    limitations: [
      'Sin API pública usable para automatización.',
      'Registro pagado o vía cámaras — no acceso libre masivo.',
      'Puede tener datos con 1-2 años de antigüedad para PYMES.',
      'No apto para resolución automática de RFC.',
      'Cobertura menor que DENUE.',
    ],
    riskNotes: [
      'No conectar al flujo automático del Agente 1 en MVP.',
      'No usar para resolución de RFC.',
    ],
  },
  {
    key: 'mx_canaive',
    name: 'CANAIVE (Cámara Nacional de la Industria del Vestido)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual sector textil/moda.',
    countryCodes: ['MX'],
    sectors: ['textil', 'manufactura textil', 'moda', 'clothing', 'garment', 'apparel', 'textile', 'vestido', 'confeccion'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.canaive.org.mx/',
    automationLevel: 'manual',
    recommendedUse:
      'Señal manual sector textil/moda mexicano. Directorio de empresas afiliadas. No usar para discovery automático ni para resolución de RFC.',
    limitations: [
      'Solo afiliados a la cámara — no representa todo el sector.',
      'Sin API — consulta manual.',
      'No entrega RFC.',
    ],
    riskNotes: [
      'No automatizar discovery desde esta fuente.',
      'No usar para resolución de RFC.',
    ],
  },
  {
    key: 'mx_amia',
    name: 'AMIA (Asociación Mexicana de la Industria Automotriz)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual sector automotriz.',
    countryCodes: ['MX'],
    sectors: ['automotriz', 'automotive', 'autopartes', 'auto parts', 'vehiculo', 'vehicle', 'manufactura automotriz'],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.amia.com.mx/',
    automationLevel: 'manual',
    recommendedUse:
      'Señal manual sector automotriz mexicano. OEMs y Tier-1. No usar para discovery automático ni para resolución de RFC.',
    limitations: [
      'Solo miembros asociados.',
      'Sin API — consulta directa.',
      'No entrega RFC.',
    ],
    riskNotes: [
      'No automatizar discovery desde esta fuente.',
      'No usar para resolución de RFC.',
    ],
  },

  // ── México — Compras Públicas y Asociaciones Sectoriales ───────────────────
  {
    key: 'mx_compranet',
    name: 'CompraNet (Compras Gubernamentales México)',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Investigar https://comprasmx.buengobierno.gob.mx/datos-abiertos para confirmar nuevo endpoint post-migración antes de conectar.',
    countryCodes: ['MX'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'procurement',
    url: 'https://compranet.hacienda.gob.mx/',
    automationLevel: 'low',
    recommendedUse:
      'Señal B2G potencial de proveedores del Estado mexicano. No activar automáticamente hasta reconfirmar endpoint nuevo de Compras MX / CompraNet 5.0.',
    limitations: [
      'Endpoint anterior caído o migrado — sin confirmación de acceso a datos estructurados.',
      'Cobertura limitada a proveedores con contratos con el gobierno federal mexicano.',
      'Requiere validación de datos abiertos post-migración a CompraNet 5.0.',
      'No entrega RFC de forma confiable.',
    ],
    riskNotes: [
      'No conectar al flujo automático hasta confirmar endpoint operativo.',
      'No usar para resolución de RFC.',
      'Fuente pública — sin costo ni ToS restrictivo conocido una vez validado el endpoint.',
    ],
  },
  {
    key: 'mx_amiti',
    name: 'AMITI (Asociación Mexicana de la Industria de Tecnologías de la Información)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual sector tecnología. Directorio pequeño.',
    countryCodes: ['MX'],
    sectors: ['tecnologia', 'software', 'tic', 'servicios_ti', 'technology', 'it_services', 'software_development'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.amiti.org.mx/',
    automationLevel: 'manual',
    recommendedUse:
      'Señal manual sector tecnología mexicano. ~200 empresas afiliadas. No usar para discovery masivo ni para resolución de RFC.',
    limitations: [
      'Solo ~200 afiliados — directorio pequeño, no fuente masiva.',
      'Sin API — consulta manual del directorio web.',
      'RFC no disponible en directorio público.',
    ],
    riskNotes: [
      'No automatizar discovery desde esta fuente.',
      'No usar para resolución de RFC.',
    ],
  },
  {
    key: 'mx_fintech_mx',
    name: 'Fintech México (Asociación FinTech de México)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Sin acción: señal manual sector fintech. Validar URL activa antes de reactivar.',
    countryCodes: ['MX'],
    sectors: ['tecnologia', 'fintech', 'financiero', 'pagos', 'technology', 'payments', 'financial_technology'],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.fintechmx.com/',
    automationLevel: 'manual',
    recommendedUse:
      'Señal manual sector fintech mexicano. Directorio de empresas miembro. No usar para discovery masivo ni para resolución de RFC.',
    limitations: [
      'Volumen reducido — directorio de miembros, no fuente masiva.',
      'Sin API pública — consulta manual del directorio.',
      'Pendiente validación de URL activa y cobertura del directorio.',
      'No entrega RFC.',
    ],
    riskNotes: [
      'Verificar URL y disponibilidad del directorio antes de cualquier uso.',
      'No automatizar discovery desde esta fuente.',
      'No usar para resolución de RFC.',
    ],
  },

  // ── Chile ───────────────────────────────────────────────────────────────────
  {
    key: 'cl_res',
    name: 'RES / datos.gob.cl',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected',
    connectionMode: 'wizard_discovery',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://datos.gob.cl/',
    automationLevel: 'high',
    recommendedUse: 'Discovery principal en Chile. Portal de datos abiertos con datasets de empresas activas por sector.',
    limitations: [
      'No incluye sector, giro, CIIU ni actividad económica; requiere validación posterior de industria/fit.',
      'No incluye contactos comerciales, correos, teléfonos ni decisores.',
      'Puede incluir empresas recién constituidas, microempresas o sociedades con capital muy bajo.',
      'Puede incluir EIRL u otros tipos donde el RUT asociado requiera revisión para no confundir persona natural con empresa.',
      'No debe usarse como fuente única para priorización comercial sin señales adicionales.',
      'No existe aún enrichment adapter Chile ni resolvedor automático de RUT en SellUp.',
    ],
    riskNotes: [
      'Usar como discovery estructurado inicial de empresas chilenas, no como validación completa de ICP.',
      'No inferir sector ni tamaño comercial únicamente desde RES.',
      'Requiere revisión humana o señales complementarias para industria, fit y prioridad comercial.',
      'No usar como sustituto del SII para validación tributaria.',
      'No escribir RUT como tax_identifier fuera de un flujo controlado y auditado.',
    ],
  },
  {
    key: 'cl_chilecompra_ocds',
    name: 'ChileCompra / Mercado Público OCDS',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'connected_post_approval',
    connectionMode: 'offline_signal',
    nextAction:
      'Conectada como señal comercial post-approval. No requiere credenciales. Enriquece metadata.source_enrichment.cl_chilecompra_ocds en candidatos CL con RUT tras aprobación.',
    countryCodes: ['CL'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://datos-abiertos.chilecompra.cl/',
    automationLevel: 'high',
    recommendedUse:
      'Inteligencia comercial B2G en Chile a partir de datos abiertos OCDS de Mercado Público. Permite observar la demanda pública chilena: organismos compradores, montos licitados, rubros por clasificación UNSPSC y proveedores adjudicados cuando la licitación tiene adjudicación. Es una señal de mercado, no un generador de prospectos: no crea cuentas ni candidatos automáticamente y no reemplaza a Tavily, Apollo ni Lusha. Los compradores son entidades públicas; los proveedores privados solo aparecen en adjudicaciones.',
    limitations: [
      'Patrón N+1: el detalle requiere una llamada por proceso.',
      'El listado solo trae ocid y urlTender; los datos ricos viven únicamente en el detalle.',
      'Los compradores públicos no son prospectos privados B2B.',
      'Los proveedores privados solo aparecen en awards de licitaciones adjudicadas.',
      'No incluye website ni contacto comercial confiable del proveedor.',
      'Las clasificaciones UNSPSC requieren mapping sectorial para ser útiles en SellUp.',
      'Volumen alto: miles de procesos por mes.',
      'Rate limits del API OCDS desconocidos.',
    ],
    riskNotes: [
      'No crear cuentas automáticamente desde esta fuente.',
      'No crear candidatos automáticamente desde esta fuente.',
      'Deduplicar por ocid y por RUT, nunca solo por nombre.',
      'Usar exclusivamente como señal B2G de inteligencia de demanda.',
      'Diferenciar del connector ChileCompra legacy con ticket/Clave Única.',
    ],
  },

  // ── República Dominicana ────────────────────────────────────────────────────
  {
    key: 'rd_dgii_bulk',
    name: 'DGII Padrón RNC (República Dominicana)',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected_post_approval',
    connectionMode: 'offline_signal',
    nextAction:
      'Conectada como señal tributaria offline. Snapshot RNC jurídicos cargado. No requiere credenciales. Útil para validación RNC y enriquecimiento post-approval en flujos RD.',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://dgii.gov.do/',
    automationLevel: 'high',
    recommendedUse:
      'Padrón de contribuyentes jurídicos (RNC) de la DGII. 493.548 empresas con razón social, estado tributario y actividad económica (texto libre). Fuente legal/tributaria para validar RNC y enriquecer cuentas RD post-approval. No usar para personas físicas (Cédula) ni como discovery abierto.',
    limitations: [
      'Solo RNC jurídicos (9 dígitos) — cédulas/personas físicas (11 dígitos) fuera de scope',
      'Actividad económica en texto libre DGII — no hay CIIU oficial en esta versión del snapshot',
      'No sector oficial ni CIIU normalizado para MVP',
      'Snapshot estático — requiere re-carga manual para actualizar',
      'No apto para discovery masivo sin filtro de estado tributario',
    ],
    riskNotes: [
      'No crear cuentas ni candidatos automáticamente desde esta fuente',
      'No usar cédulas/identificadores de 11 dígitos — fuera de scope',
      'Validar estado tributario antes de prospectar (ACTIVO vs DADO DE BAJA)',
      'No hay CIIU oficial — no inferir sector únicamente desde actividad económica texto libre',
    ],
  },
  {
    key: 'do_camaratic',
    name: 'Cámara de Comercio y Producción (CAMARATIC)',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_applicable',
    nextAction: 'Directorio web CAMARATIC para consulta manual. Sin API pública. No automatizable en MVP.',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://camaratic.do/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas afiliadas a la principal cámara de comercio dominicana. Fuente de empresas activas en RD.',
    limitations: ['Solo miembros afiliados a CAMARATIC', 'Sin API pública'],
  },
  {
    key: 'do_camara_sto_domingo',
    name: 'Cámara de Comercio de Santo Domingo',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_applicable',
    nextAction: 'Directorio web CCSD para consulta manual. Cobertura regional Santo Domingo. Sin API pública confirmada.',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccsd.com.do/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional para zona metropolitana. Directorio de empresas afiliadas en Santo Domingo.',
    limitations: ['Solo afiliados CCSD', 'Sin API — consulta manual'],
  },

  {
    key: 'do_dgcp',
    name: 'DGCP (Dirección General de Contrataciones Públicas RD)',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'eligible_not_connected',
    connectionMode: 'not_connected',
    nextAction: 'Señal B2G disponible en portal OCDS DGCP. Requiere validación de endpoint API o descarga antes de conectar.',
    countryCodes: ['DO'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://datosabiertos.dgcp.gob.do/datos-abiertos/tablas',
    automationLevel: 'medium',
    recommendedUse: 'Proveedores del Estado dominicano con RNC. Datos desde 2005. Señal de empresa activa con historial contractual B2G en República Dominicana. Portal de datos abiertos OCDS.',
    limitations: [
      'Solo empresas proveedoras del Estado dominicano — no representa el universo empresarial completo de RD',
      'Portal SPA (React) — extracción requiere inspeccionar API subyacente o usar datos.gob.do',
      'Volumen moderado — decenas de miles de proveedores registrados, no millones',
    ],
    riskNotes: [
      'Miembro Open Contracting Partnership (OCDS) — datos bajo estándares abiertos, riesgo legal bajo',
    ],
  },

  {
    key: 'pe_sunat_bulk',
    name: 'SUNAT Padrón RUC Bulk (Descarga masiva)',
    sellupUse: 'enrichment',
    aiFlowStatus: 'connected_post_approval',
    connectionMode: 'offline_signal',
    nextAction: 'Snapshot SUNAT cargado (2.317.298 registros, cobertura completa). Enrichment legal post-approval activo. Sin credenciales requeridas.',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'http://www2.sunat.gob.pe/padron_reducido_ruc.zip',
    automationLevel: 'high',
    recommendedUse: 'Descarga masiva del Padrón Reducido RUC. 11–14M registros: RUC, razón social, estado contribuyente, condición domicilio, UBIGEO. Sin auth. Complementar con pe_sunat para enriquecimiento CIIU individual.',
    limitations: [
      'Padrón reducido no incluye actividad CIIU — usar consulta SOL individual para obtener sector',
      'Incluye personas naturales con RUC; filtrar por tipo de contribuyente para empresas jurídicas',
      'ZIP ~387 MB; actualización variable — verificar fecha del archivo antes de procesar',
    ],
    riskNotes: [
      'Filtrar estado: ACTIVO antes de prospectar',
      'Amparado por Resolución de Superintendencia N° 304-2024/SUNAT — uso público permitido',
    ],
  },
  {
    key: 'pe_sunat',
    name: 'SUNAT Padrón RUC',
    sellupUse: 'validation_only',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Consulta web individual RUC para verificación tributaria, no discovery masivo',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'validation_only',
    type: 'official_registry',
    url: 'https://e-consultaruc.sunat.gob.pe/',
    automationLevel: 'medium',
    recommendedUse: 'Fuente principal en Perú. Padrón RUC con razón social, estado activo, actividad CIIU.',
    limitations: ['Sin API oficial para consulta masiva', 'Solo datos tributarios básicos'],
    riskNotes: ['Verificar estado: Activo antes de prospectar'],
  },
  {
    key: 'pe_seace',
    name: 'OSCE / SEACE (Contrataciones del Estado)',
    sellupUse: 'commercial_signal',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Señal B2G futura — requiere validación de acceso a datos abiertos OSCE/SEACE',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.seace.gob.pe/',
    automationLevel: 'high',
    recommendedUse: 'Discovery de proveedores del Estado peruano. Señal de empresa activa con historial B2G.',
    limitations: ['Solo empresas que contratan con el Estado'],
  },
  {
    key: 'pe_produce',
    name: 'PRODUCE Manufactura',
    sellupUse: 'manual_reference',
    aiFlowStatus: 'manual_only',
    connectionMode: 'not_connected',
    nextAction: 'Pendiente validación — fuente sectorial manufactura peruana sin API confirmada',
    countryCodes: ['PE'],
    sectors: ['manufactura', 'manufacturing', 'industria', 'industrial', 'produccion', 'production', 'planta'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'public_dataset',
    url: 'https://www.gob.pe/produce',
    automationLevel: 'medium',
    recommendedUse: 'Discovery en sector manufactura peruano. Padrones y estadísticas de empresas manufactureras.',
    limitations: ['Solo sector manufactura'],
  },

  {
    key: 'pe_migo_api',
    name: 'Migo API Perú RUC Lookup',
    sellupUse: 'validation_only',
    aiFlowStatus: 'eligible_not_connected',
    connectionMode: 'not_connected',
    nextAction:
      'Requiere API Key en panel de credenciales. Útil para validar RUC peruano, estado del contribuyente, condición de domicilio y dirección. No devuelve CIIU según spike real Perú.3N-R.',
    countryCodes: ['PE'],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'connection_required',
    type: 'commercial_provider',
    url: 'https://docs.migo.pe',
    automationLevel: 'high',
    recommendedUse:
      'Consulta privada bajo demanda para validar RUC peruano, razón social, estado del contribuyente, condición de domicilio y dirección. No devuelve CIIU ni actividad económica en el endpoint validado (spike real Perú.3N-R). No usar como fuente sectorial ni para discovery. Puede ser redundante frente a SUNAT Padrón Reducido para estado/condición.',
    limitations: [
      'No útil para CIIU/actividad económica según spike real Perú.3N-R (MIGO_NOT_USEFUL_FOR_CIIU)',
      'No usar como fuente sectorial ni como discovery',
      'Puede ser redundante frente a SUNAT Padrón Reducido para estado/condición',
      'API privada de tercero — requiere plan de pago',
      'Depende de disponibilidad y ToS de Migo API',
    ],
    riskNotes: [
      'Evaluar ToS y costos antes de usar en producción',
      'No exponer API key en frontend ni logs',
      'Validar rate limits del plan contratado',
      'No almacenar datos de representantes legales ni domicilio fiscal',
    ],
  },

  // ── Ecuador ─────────────────────────────────────────────────────────────────
  {
    key: 'ec_scvs',
    name: 'SCVS / Supercias Ecuador',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'pending_validation',
    type: 'official_registry',
    url: 'https://www.supercias.gob.ec/',
    automationLevel: 'medium',
    recommendedUse: 'Registro de compañías ecuatorianas. Razón social, objeto social, representante legal.',
    limitations: ['Solo empresas obligadas a reportar a Supercias', 'Excluye microempresas'],
  },
  {
    key: 'ec_sercop',
    name: 'SERCOP (Compras Públicas Ecuador)',
    countryCodes: ['EC'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'operational_verified',
    type: 'procurement',
    url: 'https://www.sercop.gob.ec/',
    automationLevel: 'high',
    recommendedUse: 'Identificar proveedores del Estado ecuatoriano. Señal de empresa activa.',
    limitations: ['Solo empresas contratistas del Estado'],
  },
  {
    key: 'ec_ekos',
    name: 'EKOS Ecuador',
    countryCodes: ['EC'],
    sectors: ['manufactura', 'tecnologia', 'agronegocio', 'servicios'],
    priority: 'P1',
    operationalStatus: 'pending_validation',
    type: 'commercial_provider',
    url: 'https://www.ekosnegocios.com/',
    automationLevel: 'medium',
    recommendedUse: 'Base de datos de empresas ecuatorianas. Directorio con información de contacto y rubro empresarial.',
    limitations: ['Datos de fuente comercial tercero', 'Cobertura parcial de mercado ecuatoriano'],
  },

  // ── Guatemala ───────────────────────────────────────────────────────────────
  {
    key: 'gt_camara_comercio',
    name: 'Cámara de Comercio de Guatemala',
    countryCodes: ['GT'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.camaracomercio.com.gt/',
    automationLevel: 'manual',
    recommendedUse: 'Directorio de empresas afiliadas a la Cámara. Identificar empresas activas en Guatemala.',
    limitations: ['Solo empresas afiliadas', 'Sin API — consulta manual o directorio web'],
  },

  // ── Honduras ────────────────────────────────────────────────────────────────
  {
    key: 'hn_ccic',
    name: 'Cámara de Comercio e Industrias de Cortés',
    countryCodes: ['HN'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccic.hn/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional. Directorio de empresas en zona industrial de Cortés.',
    limitations: ['Solo empresas afiliadas CCIC', 'Zona geográfica limitada (Cortés)'],
  },
  {
    key: 'hn_ccit',
    name: 'Cámara de Comercio e Industrias de Tegucigalpa',
    countryCodes: ['HN'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'manual_signal_only',
    type: 'industry_association',
    url: 'https://www.ccit.hn/',
    automationLevel: 'manual',
    recommendedUse: 'Cámara de comercio regional. Directorio de empresas en capital hondureña.',
    limitations: ['Solo empresas afiliadas CCIT', 'Zona geográfica limitada (Tegucigalpa)'],
  },

  // ── Brasil ──────────────────────────────────────────────────────────────────
  {
    key: 'br_receita_dados_abertos',
    name: 'Receita Federal CNPJ Dados Abertos (Bulk)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P0',
    operationalStatus: 'operational_verified',
    type: 'official_registry',
    url: 'https://dadosabertos.rfb.gov.br/CNPJ/',
    automationLevel: 'high',
    recommendedUse: 'Fuente principal para ingesta masiva/offline de CNPJ. Dataset más completo de LATAM — ~60M CNPJs (~22M activos). Archivos ZIP: CNPJ, razão social, CNAE, município, situação cadastral, capital social, porte, quadro societário. Filtrar CNAE 62xx para tecnología. Usar esta fuente como punto de entrada para cualquier pipeline bulk de Brasil.',
    limitations: [
      'Descarga ~4.7 GB comprimido / ~17 GB descomprimido — procesamiento batch offline obligatorio',
      'Acceso desde fuera de Brasil puede dar timeout; usar mirror: dados.gov.br o arquivos.receitafederal.gov.br',
      'No incluye datos de contacto (teléfono/email) en la mayoría de registros',
      'Licencia CC BY-ND 3.0 — no permite derivados; verificar uso comercial con legal antes de producción',
    ],
    riskNotes: [
      'Filtrar por situação cadastral: Ativa',
      'Verificar disponibilidad de mirror antes de procesar en producción',
    ],
  },
  {
    key: 'br_receita_cnpj',
    name: 'Receita Federal CNPJ (Referencia institucional)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'validation_only',
    type: 'official_registry',
    url: 'https://www.gov.br/receitafederal/',
    automationLevel: 'low',
    recommendedUse: 'Referencia institucional y validación puntual de CNPJ. No duplicar ingesta bulk si br_receita_dados_abertos está activa — esta fuente es complementaria para consultas individuales o verificación de registros específicos.',
    limitations: ['Sin descarga masiva directa desde el portal web', 'Datos de contacto mínimos en la fuente oficial'],
    riskNotes: ['No usar como pipeline de discovery masivo; usar br_receita_dados_abertos para ingesta bulk'],
  },
  {
    key: 'br_cnpj_ws',
    name: 'cnpj.ws (API tercero)',
    countryCodes: ['BR'],
    sectors: [],
    priority: 'P1',
    operationalStatus: 'connection_required',
    type: 'commercial_provider',
    url: 'https://www.cnpj.ws/',
    automationLevel: 'high',
    recommendedUse: 'API REST sobre datos CNPJ. Más conveniente que Receita Federal directa para integraciones.',
    limitations: ['Tercero no oficial sobre datos de Receita Federal'],
    riskNotes: ['Validar TOS y SLA antes de usar en producción'],
  },

  // ── Globales / Fallback ─────────────────────────────────────────────────────
  {
    key: 'global_opencorporates',
    name: 'OpenCorporates',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'connection_required',
    type: 'public_dataset',
    url: 'https://opencorporates.com/',
    automationLevel: 'medium',
    recommendedUse: 'Fallback global para países sin fuente P0. Cubre 130+ jurisdicciones con datos básicos de registro.',
    limitations: ['Cobertura desigual en LatAm', 'API requiere plan de pago para volumen', 'Datos pueden estar desactualizados'],
    riskNotes: [
      'Requiere plan/API de pago para volumen; no usar como fuente automática de discovery sin validación comercial y legal previa.',
    ],
  },
  {
    key: 'global_apollo',
    name: 'Apollo.io',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'connection_required',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Fallback pagado cuando fuentes públicas no alcanzan el objetivo de cantidad. Cobertura débil en LatAm vs USA.',
    limitations: ['Cobertura débil en LatAm', 'Datos de contacto con 25-40% de rebote esperado', 'Costo por crédito'],
    riskNotes: ['Solo usar como último recurso explícito autorizado', 'No usar como primera fuente de discovery'],
  },
  {
    key: 'global_lusha',
    name: 'Lusha',
    countryCodes: [],
    sectors: [],
    priority: 'P2',
    operationalStatus: 'validation_only',
    type: 'commercial_provider',
    url: null,
    automationLevel: 'high',
    recommendedUse: 'Enriquecimiento de datos de contacto (teléfono, email directo) bajo demanda ÚNICAMENTE.',
    limitations: ['Nunca usar para discovery de empresas', 'Solo enriquecimiento de contactos ya identificados'],
    riskNotes: ['Excluida de discovery — no aparece en recommendedSources'],
  },
];
